hostname r4
!
router bgp 65003
 bgp router-id 10.255.0.4
 no bgp ebgp-requires-policy
 neighbor 10.0.14.3 remote-as 65001
 neighbor 10.255.0.3 remote-as 65002
 neighbor 10.255.0.3 ebgp-multihop 3
 neighbor 10.255.0.3 update-source lo
 !
 address-family ipv4 unicast
  network 10.4.0.0/22
  network 10.4.0.0/24
  network 10.4.1.0/24
  network 10.4.2.0/24
  network 10.4.3.0/24
  neighbor 10.0.14.3 activate
  neighbor 10.255.0.3 activate
 exit-address-family
!
