"""
ROCA (Return of Coppersmith's Attack) key detector and factorizer.

Detects RSA keys generated by a flawed algorithm where primes are of the form
    p = g^a mod M
where g=65537 and M is a product of 39 specific small primes. The multiplicative
order of g modulo M is 360360, so there are only 360360 candidate prime values.
Since M > p for these key sizes, the primes equal g^a mod M exactly (no additive
multiple of M needed). Factoring enumerates all 360360 candidates and checks
divisibility.

"""

import json
import math
import time


def order_mod(g, p):
    """Compute the multiplicative order of g modulo p."""
    if p <= 2:
        return 1
    x = g % p
    if x == 0:
        return 0
    cur = x
    o = 1
    while cur != 1:
        cur = (cur * x) % p
        o += 1
    return o


def lcm(a, b):
    return a * b // math.gcd(a, b)


# ---------------------------------------------------------------------------
# ROCA parameters
# ---------------------------------------------------------------------------

G = 65537

# The 39 characteristic primes used in the Infineon key generation
ROCA_PRIMES = [
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 53, 61, 67, 71,
    73, 79, 89, 97, 127, 131, 157, 181, 199, 211, 241, 281, 313, 331,
    353, 379, 397, 421, 461, 463, 491,
]

# M = product of the 39 characteristic primes
M = 1
for _p in ROCA_PRIMES:
    M *= _p

# Total multiplicative order of G modulo M = lcm of orders mod each prime
TOTAL_ORDER = 1
for _p in ROCA_PRIMES:
    TOTAL_ORDER = lcm(TOTAL_ORDER, order_mod(G, _p))
# TOTAL_ORDER == 360360


# ---------------------------------------------------------------------------
# ROCA detection
# ---------------------------------------------------------------------------

def detect_roca(n):
    """Check if RSA modulus n has the ROCA fingerprint.

    For each characteristic prime p (excluding 2), check whether n mod p
    lies in the subgroup generated by G modulo p. If so for ALL primes,
    the key is ROCA-vulnerable.
    """
    for p in ROCA_PRIMES:
        if p == 2:
            continue  # n is always odd for RSA
        n_mod_p = n % p
        # Compute set of powers of G mod p
        powers = set()
        x = 1
        for _ in range(p):
            powers.add(x)
            x = (x * G) % p
        if n_mod_p not in powers:
            return False
    return True


# ---------------------------------------------------------------------------
# ROCA factorization
# ---------------------------------------------------------------------------

def factor_roca(n):
    """Factor ROCA-vulnerable RSA modulus n.

    Since M > p for the key sizes used (~240-bit primes, M is ~241 bits),
    the vulnerable primes satisfy p = G^a mod M exactly.
    We enumerate all candidate exponents a in [0, TOTAL_ORDER) and check
    if G^a mod M divides n.
    """
    g_a = 1
    for a in range(TOTAL_ORDER):
        if g_a > 1 and n % g_a == 0:
            q = n // g_a
            if q > 1:
                return g_a, q
        g_a = (g_a * G) % M
    return None, None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    with open("/app/keys.json") as f:
        keys = json.load(f)

    results = {}
    for key_entry in keys:
        kid = key_entry["id"]
        n = int(key_entry["n"], 16)

        print(f"Processing {kid} ({n.bit_length()}-bit)...")

        if detect_roca(n):
            print(f"  {kid}: ROCA-vulnerable, factoring...")
            t0 = time.time()
            p, q = factor_roca(n)
            elapsed = time.time() - t0
            if p is not None:
                print(f"  {kid}: factored in {elapsed:.1f}s")
                print(f"    p = {p}")
                print(f"    q = {q}")
                results[kid] = {
                    "vulnerable": True,
                    "p": str(p),
                    "q": str(q),
                }
            else:
                print(f"  {kid}: FAILED to factor after {elapsed:.1f}s")
                results[kid] = {"vulnerable": True, "p": None, "q": None}
        else:
            print(f"  {kid}: not vulnerable")
            results[kid] = {"vulnerable": False}

    with open("/app/results.json", "w") as f:
        json.dump(results, f, indent=2)

    print(f"\nResults written to /app/results.json")


if __name__ == "__main__":
    main()
