#!/usr/bin/env python3
"""
Generate a PARI/GP script to solve the ECDLP on each prime-order
reduction of the curve and combine results via CRT.

Usage: python3 write_gp_script.py <factor_of_n>
"""

import json
import sys


def main():
    factor = int(sys.argv[1])

    with open("/app/challenge/public_params.json") as f:
        params = json.load(f)

    n = int(params["n"])
    A = int(params["A"])
    B = int(params["B"])
    C = int(params["C"])
    Gx = int(params["G"]["x"])
    Gy = int(params["G"]["y"])
    Qx = int(params["Q"]["x"])
    Qy = int(params["Q"]["y"])

    p = factor
    q = n // p
    assert p * q == n, f"Factor {p} does not divide n"

    # Ensure p < q for consistency
    if p > q:
        p, q = q, p

    gp_script = r"""
\\ ECDLP solver via Pohlig-Hellman on reduced curves
\\ Generated by write_gp_script.py
{{
  p = {p};
  q = {q};

  \\ Define curve mod p: y^2 = x^3 + A*x^2 + B*x + C
  \\ PARI ellinit takes [a1, a2, a3, a4, a6]
  Ep = ellinit([0, Mod({A}, p), 0, Mod({B}, p), Mod({C}, p)]);
  Gp = [Mod({Gx}, p), Mod({Gy}, p)];
  Qp = [Mod({Qx}, p), Mod({Qy}, p)];

  \\ Curve order (should be p+1 for CM curve with p ≡ 3 mod 4)
  ordp = ellcard(Ep);

  \\ Solve ECDLP on E(Fp)
  sp = elllog(Ep, Qp, Gp, ordp);

  \\ Define curve mod q
  Eq = ellinit([0, Mod({A}, q), 0, Mod({B}, q), Mod({C}, q)]);
  Gq = [Mod({Gx}, q), Mod({Gy}, q)];
  Qq = [Mod({Qx}, q), Mod({Qy}, q)];

  ordq = ellcard(Eq);

  \\ Solve ECDLP on E(Fq)
  sq = elllog(Eq, Qq, Gq, ordq);

  \\ Combine via CRT
  s = lift(chinese(Mod(sp, ordp), Mod(sq, ordq)));

  print(s);
}}
""".format(
        p=p, q=q,
        A=A, B=B, C=C,
        Gx=Gx, Gy=Gy,
        Qx=Qx, Qy=Qy,
    )

    with open("/tmp/solver.gp", "w") as f:
        f.write(gp_script)

    print(f"[*] PARI/GP script written to /tmp/solver.gp", file=sys.stderr)
    print(f"[*] p = {p} ({p.bit_length()} bits)", file=sys.stderr)
    print(f"[*] q = {q} ({q.bit_length()} bits)", file=sys.stderr)


if __name__ == "__main__":
    main()
