#' Compare quartet states by explicit enumeration
#'
#' Uses explicit enumeration to compare two lists of quartet states
#' (Estabrook et al. 1985), detailing how many are identical and how many
#' are unresolved.
#'
#' @param x,cf List of quartet states, perhaps generated by QuartetStates().
#'
#' @return Returns a named vector of seven integers corresponding to the
#'   quantities of Estabrook et al. (1985):
#'   \describe{
#'     \item{N}{2 * Q: the total number of quartet _statements_ for the given
#'       number of trees.}
#'     \item{Q}{Total number of quartets: choose(n_tips, 4).}
#'     \item{s}{Number of quartets resolved in the same manner in both trees.}
#'     \item{d}{Number of quartets resolved differently in both trees.}
#'     \item{r1}{Number of quartets resolved in tree 1 but unresolved in tree 2.}
#'     \item{r2}{Number of quartets resolved in tree 2 but unresolved in tree 1.}
#'     \item{u}{Number of quartets unresolved in both trees.}
#'   }
#'
#' @references
#'   Estabrook, G. F., McMorris, F. R., & Meacham, C. A. (1985).
#'   Comparison of undirected phylogenetic trees based on subtrees of four
#'   evolutionary units. Systematic Zoology, 34(2), 193-200.
#'
#' @export
CompareQuartets <- function (x, cf) {
  x_resolved <- as.logical(x)
  cf_resolved <- as.logical(cf)
  both_resolved <- x_resolved & cf_resolved
  n_both_resolved <- sum(both_resolved)
  n_same <- sum(x[both_resolved] == cf[both_resolved])
  c(
    N = 2L * length(x),
    Q = length(x),
    s = n_same,
    d = n_both_resolved - n_same,
    r1 = sum(x_resolved) - n_both_resolved,
    r2 = sum(cf_resolved) - n_both_resolved,
    u = sum(!x_resolved & !cf_resolved)
  )
}

#' Compare one tree's quartets against others'
#'
#' CompareQuartetsMulti() counts how many quartets in one tree are resolved
#' in the same way or different ways in a forest of comparison trees.
#'
#' @param x Object of class phylo representing the tree of interest.
#' @param cf Comparison tree of class phylo, or list thereof, each with the
#'   same leaves as x.
#'
#' @return CompareQuartetsMulti() returns a named integer vector specifying
#'   the number of quartets whose resolution in x matches all or any of the
#'   resolutions in cf.
#'
#'   Named elements are:
#'   \describe{
#'     \item{N}{The total number of quartet _statements_ for the given number
#'       of n-leaf trees, i.e. n_trees * Q.}
#'     \item{Q}{The total number of quartets for n leaves.}
#'     \item{s_all}{The number of quartets that are resolved identically in
#'       all trees.}
#'     \item{s_any}{The number of quartets that are resolved in x, and
#'       identically in at least one of cf.}
#'     \item{d_all}{The number of quartets that are resolved in every tree in
#'       cf, but never in the same way as they are resolved in x.}
#'     \item{d_any}{The number of quartets in x that are resolved differently
#'       (i.e. contradicted) in at least one tree in cf.}
#'     \item{r1_all}{The number of quartets that are resolved in x, but not
#'       in any of cf.}
#'     \item{r1_any}{The number of quartets that are resolved in x, but
#'       unresolved in at least one of cf.}
#'     \item{r2_all}{The number of quartets that are resolved in all of cf,
#'       but not in x.}
#'     \item{r2_any}{The number of quartets that are resolved in at least one
#'       of cf, but not in x.}
#'     \item{u_all}{The number of quartets that are unresolved in all trees.}
#'     \item{u_any}{The number of quartets that are unresolved in x and at
#'       least one tree in cf.}
#'     \item{x_only}{The number of quartets in x that are not resolved the
#'       same way in any of cf.}
#'   }
#'
#' @export
CompareQuartetsMulti <- function (x, cf) {

  input <- QuartetStates(x, asRaw = TRUE)
  nIn <- length(input)
  if (inherits(cf, "phylo")) {
    cf <- list(cf)
  }
  xLabels <- x$tip.label
  xSorted <- sort(xLabels)
  cfTips <- vapply(cf, NTip, 0L)
  if (!all(cfTips == length(xLabels))) {
    stop("All trees must contain the same number of leaves.")
  }

  nCf <- length(cf)
  comparison <- vapply(cf, QuartetStates, input, asRaw = TRUE)

  xResolved <- as.logical(input)
  cfResolved <- comparison != as.raw(0)
  cfResolvedSums <- .rowSums(cfResolved, nIn, nCf)
  cfAnyResolved <- as.logical(cfResolvedSums)
  cfAllResolved <- cfResolvedSums == nCf

  equal <- comparison == input
  same <- .rowSums(equal, nIn, nCf)
  anySame <- as.logical(same)
  allSame <- same == nCf
  different <- .rowSums(!equal & cfResolved, nIn, nCf)

  # Return:
  c(
    N = (length(cf) + 1L) * nIn,
    Q = length(input),
    s_all = sum(xResolved & allSame),
    s_any = sum(xResolved & anySame),
    d_all = sum(xResolved & !anySame & cfAllResolved),
    d_any = sum(xResolved & different),
    r1_all = sum(xResolved & !cfAnyResolved),
    r1_any = sum(xResolved & !cfAllResolved),
    r2_all = sum(!xResolved & cfAllResolved),
    r2_any = sum(!xResolved & cfAnyResolved),
    u_all = sum(!xResolved & allSame),
    u_any = sum(!xResolved & anySame),
    x_only = sum(xResolved & !anySame)
  )
}
