"""
Generalized Moving Peaks Benchmark (GMPB)

Dynamic optimization benchmark with cone-shaped peaks that shift positions,
change heights, and change widths over time. Evaluates solver ability to
track the changing global optimum across environment transitions.

Landscape: f(x) = max_{p=1..P} [ h_p - w_p * ||x - c_p|| ]

Each peak p has:
  - c_p: center position in R^D
  - h_p: height (fitness at center)
  - w_p: width (controls steepness)

At each environment change:
  - Positions shift via correlated random walk (shift_severity controls step size)
  - Heights perturbed randomly within [height_range]
  - Widths perturbed randomly within [width_range]

Offline error = mean of current errors across ALL fitness evaluations,
where current_error(i) = max(0, f(x_opt) - best_found_so_far).
best_found_so_far resets to -inf after each environment change.

Reference: IEEE CEC Competition on Dynamic Optimization Problems
Generated by Generalized Moving Peaks Benchmark (GMPB)
"""


import numpy as np


class GMPBConfig:
    """Configuration for a GMPB problem instance.

    Attributes:
        num_peaks: Number of peaks in the landscape.
        dimension: Dimensionality of the search space.
        change_frequency: Number of fitness evaluations between environment changes.
        shift_severity: Euclidean distance each peak shifts per change.
        num_environments: Total number of environments in a run.
        bounds: (lower, upper) bounds for each dimension.
        height_range: (min, max) peak height.
        width_range: (min, max) peak width.
        height_severity: Std dev of height perturbation per change.
        width_severity: Std dev of width perturbation per change.
        correlation: Correlation coefficient for shift direction (0=random, 1=same).
    """

    def __init__(self, num_peaks, dimension, change_frequency, shift_severity,
                 num_environments=20, bounds=(-50.0, 50.0),
                 height_range=(30.0, 70.0), width_range=(1.0, 12.0),
                 height_severity=7.0, width_severity=1.0,
                 correlation=0.5):
        self.num_peaks = num_peaks
        self.dimension = dimension
        self.change_frequency = change_frequency
        self.shift_severity = shift_severity
        self.num_environments = num_environments
        self.bounds = bounds
        self.height_range = height_range
        self.width_range = width_range
        self.height_severity = height_severity
        self.width_severity = width_severity
        self.correlation = correlation


class GMPB:
    """Generalized Moving Peaks Benchmark.

    Usage:
        config = GMPBConfig(num_peaks=10, dimension=5, change_frequency=5000,
                           shift_severity=1.0, num_environments=20)
        gmpb = GMPB(config, seed=42)

        for env in range(config.num_environments):
            for _ in range(config.change_frequency):
                x = ...  # candidate solution, numpy array of shape (D,)
                fitness = gmpb.evaluate(x)
            if env < config.num_environments - 1:
                gmpb.change_environment()

        print(f"Offline error: {gmpb.offline_error()}")
    """

    def __init__(self, config, seed=42):
        self.config = config
        self.rng = np.random.RandomState(seed)

        # Peak state: (P, D), (P,), (P,), (P, D)
        self.positions = None
        self.heights = None
        self.widths = None
        self.prev_shifts = None

        # Evaluation tracking
        self.eval_count = 0
        self.current_env = 0
        self.best_fitness = -np.inf
        self.current_errors = []
        self._optimum = None  # (position, fitness)

        self._initialize()

    def _initialize(self):
        """Initialize peak positions, heights, widths, and shift directions."""
        c = self.config
        P, D = c.num_peaks, c.dimension
        lo, hi = c.bounds

        self.positions = self.rng.uniform(lo, hi, (P, D))
        self.heights = self.rng.uniform(c.height_range[0], c.height_range[1], P)
        self.widths = self.rng.uniform(c.width_range[0], c.width_range[1], P)

        # Initial shift directions (random unit vectors scaled by shift_severity)
        self.prev_shifts = self.rng.randn(P, D)
        norms = np.linalg.norm(self.prev_shifts, axis=1, keepdims=True)
        norms = np.maximum(norms, 1e-10)
        self.prev_shifts = self.prev_shifts / norms * c.shift_severity

        self._update_optimum()

    def _update_optimum(self):
        """Identify the global optimum (peak with highest height)."""
        idx = int(np.argmax(self.heights))
        self._optimum = (self.positions[idx].copy(), float(self.heights[idx]))

    def get_optimum(self):
        """Return (position, fitness) of the current global optimum.

        The global optimum is at the center of the highest peak,
        where fitness equals the peak's height.
        """
        return self._optimum

    def evaluate(self, x):
        """Evaluate fitness at point x.

        Fitness is the maximum over all cone-shaped peaks:
            f(x) = max_p [ h_p - w_p * ||x - c_p|| ]

        Args:
            x: numpy array of shape (dimension,). Clipped to bounds.

        Returns:
            float: Fitness value. Higher is better.
        """
        x = np.asarray(x, dtype=np.float64)
        lo, hi = self.config.bounds
        x = np.clip(x, lo, hi)

        # Distance from x to each peak center
        diffs = x[np.newaxis, :] - self.positions  # (P, D)
        dists = np.linalg.norm(diffs, axis=1)       # (P,)

        # Cone peak: h_p - w_p * dist
        peak_values = self.heights - self.widths * dists
        fitness = float(np.max(peak_values))

        # Track best found in current environment
        if fitness > self.best_fitness:
            self.best_fitness = fitness

        # Record current error
        error = max(0.0, self._optimum[1] - self.best_fitness)
        self.current_errors.append(error)

        self.eval_count += 1
        return fitness

    def change_environment(self):
        """Transition to the next environment.

        Each peak undergoes:
        1. Position shift via correlated random walk (length = shift_severity)
        2. Height perturbation (Gaussian, clipped to height_range)
        3. Width perturbation (Gaussian, clipped to width_range)

        After the change, best_fitness resets to -inf.
        """
        c = self.config
        P, D = c.num_peaks, c.dimension
        lo, hi = c.bounds

        # Correlated shift directions
        random_dirs = self.rng.randn(P, D)
        norms = np.linalg.norm(random_dirs, axis=1, keepdims=True)
        norms = np.maximum(norms, 1e-10)
        random_dirs = random_dirs / norms

        new_shifts = (c.correlation * self.prev_shifts +
                      (1 - c.correlation) * c.shift_severity * random_dirs)
        shift_norms = np.linalg.norm(new_shifts, axis=1, keepdims=True)
        shift_norms = np.maximum(shift_norms, 1e-10)
        new_shifts = new_shifts / shift_norms * c.shift_severity

        # Apply shifts with boundary reflection
        new_pos = self.positions + new_shifts
        for p in range(P):
            for d in range(D):
                iters = 0
                while (new_pos[p, d] < lo or new_pos[p, d] > hi) and iters < 100:
                    if new_pos[p, d] < lo:
                        new_pos[p, d] = 2 * lo - new_pos[p, d]
                        new_shifts[p, d] = -new_shifts[p, d]
                    if new_pos[p, d] > hi:
                        new_pos[p, d] = 2 * hi - new_pos[p, d]
                        new_shifts[p, d] = -new_shifts[p, d]
                    iters += 1

        self.positions = new_pos
        self.prev_shifts = new_shifts

        # Perturb heights and widths
        self.heights = np.clip(
            self.heights + c.height_severity * self.rng.randn(P),
            c.height_range[0], c.height_range[1])
        self.widths = np.clip(
            self.widths + c.width_severity * self.rng.randn(P),
            c.width_range[0], c.width_range[1])

        self._update_optimum()
        self.current_env += 1
        self.best_fitness = -np.inf

    def offline_error(self):
        """Compute offline error: mean of all recorded current errors.

        Returns:
            float: Average current error across all evaluations.
        """
        if not self.current_errors:
            return float('inf')
        return float(np.mean(self.current_errors))
