#!/usr/bin/env python3
"""
Generate a correct AES-128 decryption Verilog module.
Implements the FIPS 197 Inverse Cipher (Section 5.3).

Architecture:
  - Phase 1 (KEY_EXPAND): Pre-expand all 11 round keys (10 cycles)
  - Phase 2 (DECRYPT): Apply inverse rounds using keys in reverse order (10 cycles)
  - Phase 3 (DONE): Output decrypted plaintext (1 cycle)
"""

# ================================================================
# Standard AES forward S-box (FIPS 197)
# ================================================================
SBOX = [
    0x63, 0x7c, 0x77, 0x7b, 0xf2, 0x6b, 0x6f, 0xc5,
    0x30, 0x01, 0x67, 0x2b, 0xfe, 0xd7, 0xab, 0x76,
    0xca, 0x82, 0xc9, 0x7d, 0xfa, 0x59, 0x47, 0xf0,
    0xad, 0xd4, 0xa2, 0xaf, 0x9c, 0xa4, 0x72, 0xc0,
    0xb7, 0xfd, 0x93, 0x26, 0x36, 0x3f, 0xf7, 0xcc,
    0x34, 0xa5, 0xe5, 0xf1, 0x71, 0xd8, 0x31, 0x15,
    0x04, 0xc7, 0x23, 0xc3, 0x18, 0x96, 0x05, 0x9a,
    0x07, 0x12, 0x80, 0xe2, 0xeb, 0x27, 0xb2, 0x75,
    0x09, 0x83, 0x2c, 0x1a, 0x1b, 0x6e, 0x5a, 0xa0,
    0x52, 0x3b, 0xd6, 0xb3, 0x29, 0xe3, 0x2f, 0x84,
    0x53, 0xd1, 0x00, 0xed, 0x20, 0xfc, 0xb1, 0x5b,
    0x6a, 0xcb, 0xbe, 0x39, 0x4a, 0x4c, 0x58, 0xcf,
    0xd0, 0xef, 0xaa, 0xfb, 0x43, 0x4d, 0x33, 0x85,
    0x45, 0xf9, 0x02, 0x7f, 0x50, 0x3c, 0x9f, 0xa8,
    0x51, 0xa3, 0x40, 0x8f, 0x92, 0x9d, 0x38, 0xf5,
    0xbc, 0xb6, 0xda, 0x21, 0x10, 0xff, 0xf3, 0xd2,
    0xcd, 0x0c, 0x13, 0xec, 0x5f, 0x97, 0x44, 0x17,
    0xc4, 0xa7, 0x7e, 0x3d, 0x64, 0x5d, 0x19, 0x73,
    0x60, 0x81, 0x4f, 0xdc, 0x22, 0x2a, 0x90, 0x88,
    0x46, 0xee, 0xb8, 0x14, 0xde, 0x5e, 0x0b, 0xdb,
    0xe0, 0x32, 0x3a, 0x0a, 0x49, 0x06, 0x24, 0x5c,
    0xc2, 0xd3, 0xac, 0x62, 0x91, 0x95, 0xe4, 0x79,
    0xe7, 0xc8, 0x37, 0x6d, 0x8d, 0xd5, 0x4e, 0xa9,
    0x6c, 0x56, 0xf4, 0xea, 0x65, 0x7a, 0xae, 0x08,
    0xba, 0x78, 0x25, 0x2e, 0x1c, 0xa6, 0xb4, 0xc6,
    0xe8, 0xdd, 0x74, 0x1f, 0x4b, 0xbd, 0x8b, 0x8a,
    0x70, 0x3e, 0xb5, 0x66, 0x48, 0x03, 0xf6, 0x0e,
    0x61, 0x35, 0x57, 0xb9, 0x86, 0xc1, 0x1d, 0x9e,
    0xe1, 0xf8, 0x98, 0x11, 0x69, 0xd9, 0x8e, 0x94,
    0x9b, 0x1e, 0x87, 0xe9, 0xce, 0x55, 0x28, 0xdf,
    0x8c, 0xa1, 0x89, 0x0d, 0xbf, 0xe6, 0x42, 0x68,
    0x41, 0x99, 0x2d, 0x0f, 0xb0, 0x54, 0xbb, 0x16,
]

# ================================================================
# Compute inverse S-box
# ================================================================
INV_SBOX = [0] * 256
for i in range(256):
    INV_SBOX[SBOX[i]] = i


def gen_case_entries(name, table):
    """Generate Verilog case statement entries for a 256-element table."""
    lines = []
    for row in range(64):
        parts = []
        for col in range(4):
            idx = row * 4 + col
            parts.append("8'h%02x: %s=8'h%02x" % (idx, name, table[idx]))
        lines.append("                " + "; ".join(parts) + ";")
    return "\n".join(lines)


# ================================================================
# Build Verilog module
# ================================================================
inv_sbox_cases = gen_case_entries("inv_sbox", INV_SBOX)
fwd_sbox_cases = gen_case_entries("sbox", SBOX)

VERILOG_TEMPLATE = r"""`timescale 1ns/1ps
// AES-128 Decryption Module - Inverse Cipher (FIPS 197 Section 5.3)
// Generated by gen_decrypt.py

module aes128_decrypt(
    input              clk,
    input              rst,
    input              start,
    input      [127:0] ciphertext,
    input      [127:0] key_in,
    output reg [127:0] plaintext,
    output reg         done
);

    // ================================================================
    // Inverse S-Box (computed from forward S-box)
    // ================================================================
    function [7:0] inv_sbox;
        input [7:0] in;
        begin
            case (in)
@@INV_SBOX@@
                default: inv_sbox = 8'h00;
            endcase
        end
    endfunction

    // ================================================================
    // Forward S-Box (needed for key expansion)
    // ================================================================
    function [7:0] sbox;
        input [7:0] in;
        begin
            case (in)
@@FWD_SBOX@@
                default: sbox = 8'h00;
            endcase
        end
    endfunction

    // ================================================================
    // GF(2^8) Arithmetic for InvMixColumns
    // Irreducible polynomial: x^8 + x^4 + x^3 + x + 1 (0x11b)
    // ================================================================
    function [7:0] xtime;
        input [7:0] b;
        begin
            xtime = {b[6:0], 1'b0} ^ (8'h1b & {8{b[7]}});
        end
    endfunction

    // Multiply by 0x09 in GF(2^8): 9 = 8 + 1
    function [7:0] gf_mul9;
        input [7:0] b;
        reg [7:0] t2, t4, t8;
        begin
            t2 = xtime(b);
            t4 = xtime(t2);
            t8 = xtime(t4);
            gf_mul9 = t8 ^ b;
        end
    endfunction

    // Multiply by 0x0b in GF(2^8): 11 = 8 + 2 + 1
    function [7:0] gf_mul11;
        input [7:0] b;
        reg [7:0] t2, t4, t8;
        begin
            t2 = xtime(b);
            t4 = xtime(t2);
            t8 = xtime(t4);
            gf_mul11 = t8 ^ t2 ^ b;
        end
    endfunction

    // Multiply by 0x0d in GF(2^8): 13 = 8 + 4 + 1
    function [7:0] gf_mul13;
        input [7:0] b;
        reg [7:0] t2, t4, t8;
        begin
            t2 = xtime(b);
            t4 = xtime(t2);
            t8 = xtime(t4);
            gf_mul13 = t8 ^ t4 ^ b;
        end
    endfunction

    // Multiply by 0x0e in GF(2^8): 14 = 8 + 4 + 2
    function [7:0] gf_mul14;
        input [7:0] b;
        reg [7:0] t2, t4, t8;
        begin
            t2 = xtime(b);
            t4 = xtime(t2);
            t8 = xtime(t4);
            gf_mul14 = t8 ^ t4 ^ t2;
        end
    endfunction

    // ================================================================
    // InvSubBytes: Apply inverse S-box to every byte
    // ================================================================
    function [127:0] inv_sub_bytes;
        input [127:0] state;
        begin
            inv_sub_bytes = {
                inv_sbox(state[127:120]), inv_sbox(state[119:112]),
                inv_sbox(state[111:104]), inv_sbox(state[103:96]),
                inv_sbox(state[95:88]),   inv_sbox(state[87:80]),
                inv_sbox(state[79:72]),   inv_sbox(state[71:64]),
                inv_sbox(state[63:56]),   inv_sbox(state[55:48]),
                inv_sbox(state[47:40]),   inv_sbox(state[39:32]),
                inv_sbox(state[31:24]),   inv_sbox(state[23:16]),
                inv_sbox(state[15:8]),    inv_sbox(state[7:0])
            };
        end
    endfunction

    // ================================================================
    // InvShiftRows: Circular right-shift each row by its index
    // ================================================================
    function [127:0] inv_shift_rows;
        input [127:0] state;
        reg [7:0] s0, s1, s2, s3, s4, s5, s6, s7;
        reg [7:0] s8, s9, s10, s11, s12, s13, s14, s15;
        begin
            s0 =state[127:120]; s1 =state[119:112];
            s2 =state[111:104]; s3 =state[103:96];
            s4 =state[95:88];   s5 =state[87:80];
            s6 =state[79:72];   s7 =state[71:64];
            s8 =state[63:56];   s9 =state[55:48];
            s10=state[47:40];   s11=state[39:32];
            s12=state[31:24];   s13=state[23:16];
            s14=state[15:8];    s15=state[7:0];

            // Column-major state matrix after InvShiftRows:
            //   col0  col1  col2  col3
            //   s0    s4    s8    s12     row 0: no shift
            //   s13   s1    s5    s9      row 1: right-shift by 1
            //   s10   s14   s2    s6      row 2: right-shift by 2
            //   s7    s11   s15   s3      row 3: right-shift by 3
            inv_shift_rows = {
                s0,  s13, s10, s7,
                s4,  s1,  s14, s11,
                s8,  s5,  s2,  s15,
                s12, s9,  s6,  s3
            };
        end
    endfunction

    // ================================================================
    // InvMixColumns: Inverse MDS matrix multiplication
    // Matrix: [[0e,0b,0d,09],[09,0e,0b,0d],[0d,09,0e,0b],[0b,0d,09,0e]]
    // ================================================================
    function [127:0] inv_mix_columns;
        input [127:0] state;
        reg [7:0] s0, s1, s2, s3, s4, s5, s6, s7;
        reg [7:0] s8, s9, s10, s11, s12, s13, s14, s15;
        reg [7:0] r0, r1, r2, r3, r4, r5, r6, r7;
        reg [7:0] r8, r9, r10, r11, r12, r13, r14, r15;
        begin
            s0 =state[127:120]; s1 =state[119:112];
            s2 =state[111:104]; s3 =state[103:96];
            s4 =state[95:88];   s5 =state[87:80];
            s6 =state[79:72];   s7 =state[71:64];
            s8 =state[63:56];   s9 =state[55:48];
            s10=state[47:40];   s11=state[39:32];
            s12=state[31:24];   s13=state[23:16];
            s14=state[15:8];    s15=state[7:0];

            // Column 0
            r0  = gf_mul14(s0)  ^ gf_mul11(s1)  ^ gf_mul13(s2)  ^ gf_mul9(s3);
            r1  = gf_mul9(s0)   ^ gf_mul14(s1)  ^ gf_mul11(s2)  ^ gf_mul13(s3);
            r2  = gf_mul13(s0)  ^ gf_mul9(s1)   ^ gf_mul14(s2)  ^ gf_mul11(s3);
            r3  = gf_mul11(s0)  ^ gf_mul13(s1)  ^ gf_mul9(s2)   ^ gf_mul14(s3);
            // Column 1
            r4  = gf_mul14(s4)  ^ gf_mul11(s5)  ^ gf_mul13(s6)  ^ gf_mul9(s7);
            r5  = gf_mul9(s4)   ^ gf_mul14(s5)  ^ gf_mul11(s6)  ^ gf_mul13(s7);
            r6  = gf_mul13(s4)  ^ gf_mul9(s5)   ^ gf_mul14(s6)  ^ gf_mul11(s7);
            r7  = gf_mul11(s4)  ^ gf_mul13(s5)  ^ gf_mul9(s6)   ^ gf_mul14(s7);
            // Column 2
            r8  = gf_mul14(s8)  ^ gf_mul11(s9)  ^ gf_mul13(s10) ^ gf_mul9(s11);
            r9  = gf_mul9(s8)   ^ gf_mul14(s9)  ^ gf_mul11(s10) ^ gf_mul13(s11);
            r10 = gf_mul13(s8)  ^ gf_mul9(s9)   ^ gf_mul14(s10) ^ gf_mul11(s11);
            r11 = gf_mul11(s8)  ^ gf_mul13(s9)  ^ gf_mul9(s10)  ^ gf_mul14(s11);
            // Column 3
            r12 = gf_mul14(s12) ^ gf_mul11(s13) ^ gf_mul13(s14) ^ gf_mul9(s15);
            r13 = gf_mul9(s12)  ^ gf_mul14(s13) ^ gf_mul11(s14) ^ gf_mul13(s15);
            r14 = gf_mul13(s12) ^ gf_mul9(s13)  ^ gf_mul14(s14) ^ gf_mul11(s15);
            r15 = gf_mul11(s12) ^ gf_mul13(s13) ^ gf_mul9(s14)  ^ gf_mul14(s15);

            inv_mix_columns = {r0,r1,r2,r3,r4,r5,r6,r7,r8,r9,r10,r11,r12,r13,r14,r15};
        end
    endfunction

    // ================================================================
    // Key Expansion Round Constants (same as encryption)
    // ================================================================
    function [7:0] rcon;
        input [3:0] round;
        begin
            case (round)
                4'd1:  rcon = 8'h01;
                4'd2:  rcon = 8'h02;
                4'd3:  rcon = 8'h04;
                4'd4:  rcon = 8'h08;
                4'd5:  rcon = 8'h10;
                4'd6:  rcon = 8'h20;
                4'd7:  rcon = 8'h40;
                4'd8:  rcon = 8'h80;
                4'd9:  rcon = 8'h1b;
                4'd10: rcon = 8'h36;
                default: rcon = 8'h00;
            endcase
        end
    endfunction

    // ================================================================
    // Key Expansion: derive next round key (same algorithm as encryption)
    // ================================================================
    function [127:0] next_round_key;
        input [127:0] prev_key;
        input [3:0] round;
        reg [31:0] w0, w1, w2, w3, temp;
        begin
            w0 = prev_key[127:96];
            w1 = prev_key[95:64];
            w2 = prev_key[63:32];
            w3 = prev_key[31:0];

            // RotWord (left rotate by 1 byte) + SubWord
            temp = {sbox(w3[23:16]), sbox(w3[15:8]), sbox(w3[7:0]), sbox(w3[31:24])};
            temp[31:24] = temp[31:24] ^ rcon(round);

            w0 = w0 ^ temp;
            w1 = w1 ^ w0;
            w2 = w2 ^ w1;
            w3 = w3 ^ w2;

            next_round_key = {w0, w1, w2, w3};
        end
    endfunction

    // ================================================================
    // FSM: KEY_EXPAND -> DECRYPT -> DONE
    // ================================================================
    localparam IDLE = 2'd0, KEY_EXPAND = 2'd1, DECRYPT = 2'd2, DONE_ST = 2'd3;

    reg [1:0]   fsm;
    reg [3:0]   expand_cnt;
    reg [3:0]   round_cnt;
    reg [127:0] state_reg;
    reg [127:0] round_keys [0:10];

    always @(posedge clk) begin
        if (rst) begin
            fsm        <= IDLE;
            done       <= 1'b0;
            plaintext  <= 128'd0;
            expand_cnt <= 4'd0;
            round_cnt  <= 4'd0;
            state_reg  <= 128'd0;
        end else begin
            case (fsm)
                IDLE: begin
                    done <= 1'b0;
                    if (start) begin
                        round_keys[0] <= key_in;
                        expand_cnt    <= 4'd1;
                        fsm           <= KEY_EXPAND;
                    end
                end

                KEY_EXPAND: begin
                    round_keys[expand_cnt] <= next_round_key(
                        round_keys[expand_cnt - 4'd1], expand_cnt
                    );
                    if (expand_cnt == 4'd10) begin
                        // All keys expanded; initial AddRoundKey with key[10]
                        state_reg <= ciphertext ^ next_round_key(
                            round_keys[4'd9], 4'd10
                        );
                        round_cnt <= 4'd9;
                        fsm       <= DECRYPT;
                    end else begin
                        expand_cnt <= expand_cnt + 4'd1;
                    end
                end

                DECRYPT: begin
                    if (round_cnt > 4'd0) begin
                        // Rounds 9..1: InvShiftRows, InvSubBytes, AddRoundKey, InvMixColumns
                        state_reg <= inv_mix_columns(
                            inv_sub_bytes(inv_shift_rows(state_reg))
                            ^ round_keys[round_cnt]
                        );
                        round_cnt <= round_cnt - 4'd1;
                    end else begin
                        // Final round: InvShiftRows, InvSubBytes, AddRoundKey(key[0])
                        state_reg <= inv_sub_bytes(inv_shift_rows(state_reg))
                                     ^ round_keys[0];
                        fsm       <= DONE_ST;
                    end
                end

                DONE_ST: begin
                    plaintext <= state_reg;
                    done      <= 1'b1;
                    fsm       <= IDLE;
                end

                default: fsm <= IDLE;
            endcase
        end
    end

endmodule
"""

verilog = VERILOG_TEMPLATE.replace("@@INV_SBOX@@", inv_sbox_cases)
verilog = verilog.replace("@@FWD_SBOX@@", fwd_sbox_cases)

with open("/app/aes128_decrypt.v", "w") as f:
    f.write(verilog)

print("Generated /app/aes128_decrypt.v")
print("  - Inverse S-box: 256 entries computed from forward S-box")
print("  - GF(2^8) multiplication: gf_mul9, gf_mul11, gf_mul13, gf_mul14")
print("  - InvShiftRows: circular right-shift rows by 0/1/2/3")
print("  - InvMixColumns: inverse MDS matrix with {0e,0b,0d,09}")
print("  - FSM: IDLE -> KEY_EXPAND (10 cyc) -> DECRYPT (10 cyc) -> DONE")
