<?xml version="1.0" encoding="UTF-8"?>
<project name="wtinylfu-sim" default="build" basedir="/app">

  <property name="src.dir" value="${basedir}/src/main/java"/>
  <property name="build.dir" value="${basedir}/classes"/>

  <target name="clean">
    <delete dir="${build.dir}"/>
  </target>

  <target name="compile">
    <mkdir dir="${build.dir}"/>
    <javac srcdir="${src.dir}" destdir="${build.dir}"
           includeantruntime="false" debug="true"/>
  </target>

  <target name="build" depends="compile"/>

</project>
