
PAGE_SIZE = 4096
MAX_ORDER = 10
TOTAL_PAGES = 16384

ZONE_DMA = 0
ZONE_NORMAL = 1
ZONE_HIGHMEM = 2
NR_ZONES = 3

ZONE_RANGES = {
    ZONE_DMA: (0, 1024),
    ZONE_NORMAL: (1024, 12288),
    ZONE_HIGHMEM: (12288, 16384),
}

MIGRATE_UNMOVABLE = 0
MIGRATE_MOVABLE = 1
MIGRATE_RECLAIMABLE = 2
NR_MIGRATE_TYPES = 3

ZONE_FALLBACK = {
    ZONE_DMA: [],
    ZONE_NORMAL: [ZONE_DMA],
    ZONE_HIGHMEM: [ZONE_NORMAL, ZONE_DMA],
}

MIGRATE_FALLBACK = {
    MIGRATE_UNMOVABLE: [MIGRATE_RECLAIMABLE, MIGRATE_MOVABLE],
    MIGRATE_MOVABLE: [MIGRATE_RECLAIMABLE, MIGRATE_UNMOVABLE],
    MIGRATE_RECLAIMABLE: [MIGRATE_MOVABLE, MIGRATE_UNMOVABLE],
}
