#!/usr/bin/env python3
"""
Generate C source with Unicode Word_Break property lookup tables.

Reads WordBreakProperty.txt and emoji-data.txt from /app/data/
and outputs word_tables.c with binary-search lookup functions.

"""

import os
import re

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data')

# Category name -> integer ID mapping.
# word_segment.py must use the same mapping.
CATEGORIES = {
    'Other': 0,
    'CR': 1,
    'LF': 2,
    'Newline': 3,
    'Extend': 4,
    'ZWJ': 5,
    'Regional_Indicator': 6,
    'Format': 7,
    'Katakana': 8,
    'Hebrew_Letter': 9,
    'ALetter': 10,
    'Single_Quote': 11,
    'Double_Quote': 12,
    'MidNumLet': 13,
    'MidLetter': 14,
    'MidNum': 15,
    'Numeric': 16,
    'ExtendNumLet': 17,
    'WSegSpace': 18,
}


def parse_ranges(filepath, filter_prop=None):
    """Parse a Unicode data file, returning sorted (lo, hi, property) list."""
    pattern = re.compile(
        r'^\s*([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*([\w_]+)'
    )
    ranges = []
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            comment_pos = line.find('#')
            if comment_pos >= 0:
                line = line[:comment_pos].strip()
            if not line:
                continue
            m = pattern.match(line)
            if not m:
                continue
            lo = int(m.group(1), 16)
            hi = int(m.group(2), 16) if m.group(2) else lo
            prop = m.group(3)
            if 0xD800 <= lo <= 0xDFFF:
                continue
            if filter_prop is not None and prop != filter_prop:
                continue
            ranges.append((lo, hi, prop))
    ranges.sort(key=lambda x: x[0])
    return ranges


def merge_adjacent(ranges):
    """Merge adjacent ranges sharing the same category."""
    if not ranges:
        return []
    merged = [list(ranges[0])]
    for lo, hi, cat in ranges[1:]:
        prev = merged[-1]
        if cat == prev[2] and lo == prev[1] + 1:
            prev[1] = hi
        else:
            merged.append([lo, hi, cat])
    return [tuple(r) for r in merged]


def generate_c(wb_ranges, ep_ranges, output_path):
    """Generate C source file with lookup tables and binary search functions."""
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('/* Auto-generated by gen_word_tables.py — DO NOT EDIT */\n')
        f.write('#include <stdint.h>\n\n')

        # Category ID defines
        for name, val in sorted(CATEGORIES.items(), key=lambda x: x[1]):
            f.write(f'#define WB_{name.upper()} {val}\n')
        f.write('\n')

        # Struct types
        f.write('typedef struct { uint32_t lo; uint32_t hi; int cat; } WBRange;\n')
        f.write('typedef struct { uint32_t lo; uint32_t hi; } EPRange;\n\n')

        # Word break property table
        f.write(f'static const WBRange wb_table[] = {{\n')
        for lo, hi, cat in wb_ranges:
            cat_id = CATEGORIES.get(cat, 0)
            f.write(f'    {{0x{lo:04X}, 0x{hi:04X}, {cat_id}}},\n')
        f.write('};\n')
        f.write(f'static const int wb_table_len = {len(wb_ranges)};\n\n')

        # Extended_Pictographic table
        f.write(f'static const EPRange ep_table[] = {{\n')
        for lo, hi, _ in ep_ranges:
            f.write(f'    {{0x{lo:04X}, 0x{hi:04X}}},\n')
        f.write('};\n')
        f.write(f'static const int ep_table_len = {len(ep_ranges)};\n\n')

        # Binary search: word_break_property
        f.write('''int word_break_property(uint32_t cp) {
    int lo = 0, hi = wb_table_len - 1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        if (cp < wb_table[mid].lo) hi = mid - 1;
        else if (cp > wb_table[mid].hi) lo = mid + 1;
        else return wb_table[mid].cat;
    }
    return WB_OTHER;
}

''')
        # Binary search: is_extended_pictographic
        f.write('''int is_extended_pictographic(uint32_t cp) {
    int lo = 0, hi = ep_table_len - 1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        if (cp < ep_table[mid].lo) hi = mid - 1;
        else if (cp > ep_table[mid].hi) lo = mid + 1;
        else return 1;
    }
    return 0;
}
''')


def main():
    # Parse Word_Break properties
    wbp_path = os.path.join(DATA_DIR, 'WordBreakProperty.txt')
    wb_ranges = parse_ranges(wbp_path)
    wb_ranges = merge_adjacent(wb_ranges)

    # Parse Extended_Pictographic
    emoji_path = os.path.join(DATA_DIR, 'emoji-data.txt')
    ep_ranges = parse_ranges(emoji_path, filter_prop='Extended_Pictographic')
    ep_ranges = merge_adjacent(ep_ranges)

    # Generate C source
    output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'word_tables.c')
    generate_c(wb_ranges, ep_ranges, output_path)
    print(f'Generated {output_path}: {len(wb_ranges)} WB ranges, {len(ep_ranges)} EP ranges')


if __name__ == '__main__':
    main()
