#!/usr/bin/env python3
"""rex -- Extended Regular Expression Analyzer CLI

"""
import sys


def main():
    if len(sys.argv) < 2:
        print("Usage: rex <subcommand> [args...]", file=sys.stderr)
        sys.exit(1)

    # TODO: implement subcommand dispatch per SPEC.md
    # Subcommands: match, empty, universal, equivalent, dot, compile, flex-spec
    raise NotImplementedError("CLI not yet implemented")


if __name__ == "__main__":
    main()
