#!/usr/bin/env python3
"""Fix the iptables template: move the REJECT rule after all ACCEPT rules.

The original template places the catch-all REJECT rule before the
per-network and per-port ACCEPT rules, causing all intended traffic
to be rejected by the first matching rule in the iptables chain.
"""


TEMPLATE_PATH = '/app/roles/hardened_lamp/templates/iptables.sh.j2'

CORRECTED_TEMPLATE = r'''#!/bin/bash
# Firewall configuration generated by Ansible
# Do not edit manually

# Flush existing rules
iptables -F INPUT
iptables -F OUTPUT
iptables -F FORWARD

# Allow loopback
iptables -A INPUT -i lo -j ACCEPT

# Allow established connections
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Allow traffic from trusted networks
{% for net in firewall_trusted_networks %}
iptables -A INPUT -s {{ net | cidr_to_network }} -j ACCEPT
{% endfor %}

# Allow specific ports
{% for rule in firewall_allowed_ports %}
iptables -A INPUT -p {{ rule.protocol }} --dport {{ rule.port }} -j ACCEPT -m comment --comment "{{ rule.comment }}"
{% endfor %}

# Reject all other incoming traffic
iptables -A INPUT -j REJECT --reject-with icmp-host-prohibited

# Set default policies
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

echo "Firewall rules applied successfully"
'''

with open(TEMPLATE_PATH, 'w') as f:
    f.write(CORRECTED_TEMPLATE)
