
"""
Verification tests for the VLIW SIMD kernel optimization task.
Tests correctness (bit-exact match with reference), performance (< 17000 cycles),
and profiling artifacts (profile report generated by vliw_profiler.py).
"""

import sys
import os
import json
import random
from copy import copy

sys.path.insert(0, "/app")

from problem import (
    Machine, Tree, Input, build_mem_image, reference_kernel2, N_CORES
)
from perf_takehome import KernelBuilder, BASELINE


def _run_kernel(forest_height, rounds, batch_size):
    """Run optimized kernel and return (correct, cycles)."""
    forest = Tree.generate(forest_height)
    inp = Input.generate(forest, batch_size, rounds)
    mem = build_mem_image(forest, inp)
    ref_mem = copy(mem)

    kb = KernelBuilder()
    kb.build_kernel(forest.height, len(forest.values), len(inp.indices), rounds)

    machine = Machine(mem, kb.instrs, kb.debug_info(), n_cores=N_CORES)
    machine.enable_pause = False
    machine.enable_debug = False
    machine.run()

    for rm in reference_kernel2(ref_mem):
        pass

    inp_values_p = ref_mem[6]
    inp_indices_p = ref_mem[5]
    n_vals = len(inp.values)
    n_idxs = len(inp.indices)

    values_correct = (
        machine.mem[inp_values_p: inp_values_p + n_vals]
        == ref_mem[inp_values_p: inp_values_p + n_vals]
    )
    indices_correct = (
        machine.mem[inp_indices_p: inp_indices_p + n_idxs]
        == ref_mem[inp_indices_p: inp_indices_p + n_idxs]
    )

    return values_correct and indices_correct, machine.cycle


class TestKernelCorrectness:
    """Verify the optimized kernel produces bit-exact output across random seeds."""

    def test_correctness_seed_42(self):
        random.seed(42)
        correct, cycles = _run_kernel(10, 16, 256)
        assert correct, f"Output mismatch at seed 42 ({cycles} cycles)"

    def test_correctness_seed_99(self):
        random.seed(99)
        correct, cycles = _run_kernel(10, 16, 256)
        assert correct, f"Output mismatch at seed 99 ({cycles} cycles)"

    def test_correctness_seed_7(self):
        random.seed(7)
        correct, cycles = _run_kernel(10, 16, 256)
        assert correct, f"Output mismatch at seed 7 ({cycles} cycles)"

    def test_correctness_seed_2024(self):
        random.seed(2024)
        correct, cycles = _run_kernel(10, 16, 256)
        assert correct, f"Output mismatch at seed 2024 ({cycles} cycles)"

    def test_correctness_seed_314159(self):
        random.seed(314159)
        correct, cycles = _run_kernel(10, 16, 256)
        assert correct, f"Output mismatch at seed 314159 ({cycles} cycles)"

    def test_correctness_seed_555(self):
        random.seed(555)
        correct, cycles = _run_kernel(10, 16, 256)
        assert correct, f"Output mismatch at seed 555 ({cycles} cycles)"

    def test_correctness_small_tree(self):
        """Test with a smaller tree to catch edge cases."""
        random.seed(123)
        correct, cycles = _run_kernel(4, 8, 256)
        assert correct, f"Output mismatch on small tree ({cycles} cycles)"

    def test_correctness_large_rounds(self):
        """Test with more rounds."""
        random.seed(123)
        correct, cycles = _run_kernel(10, 32, 256)
        assert correct, f"Output mismatch on 32 rounds ({cycles} cycles)"


class TestKernelPerformance:
    """Verify the optimized kernel meets the cycle count target."""

    def test_under_17000_cycles(self):
        random.seed(123)
        correct, cycles = _run_kernel(10, 16, 256)
        assert correct, "Output incorrect -- cannot evaluate performance"
        assert cycles < 17000, (
            f"Kernel took {cycles} cycles, target is < 17000. "
            f"Speedup: {BASELINE / cycles:.1f}x (need > {BASELINE / 17000:.1f}x)"
        )


class TestProfileReport:
    """Verify the profile report was generated using the vliw_profiler.py tool."""

    def test_report_exists(self):
        assert os.path.exists("/app/profile_report.json"), (
            "Profile report not found at /app/profile_report.json. "
            "Generate with: python3 /app/vliw_profiler.py report -o /app/profile_report.json"
        )

    def test_report_valid_json(self):
        with open("/app/profile_report.json") as f:
            report = json.load(f)
        assert isinstance(report, dict), "Report must be a JSON object"

    def test_report_structure(self):
        with open("/app/profile_report.json") as f:
            report = json.load(f)
        required_keys = [
            "profiler_version", "results", "slot_utilization",
            "configuration", "summary"
        ]
        for key in required_keys:
            assert key in report, f"Missing required key in report: {key}"
        assert "cycles" in report["results"], "Missing cycles in results"
        assert "correct" in report["results"], "Missing correct flag in results"
        assert "speedup" in report["results"], "Missing speedup in results"

    def test_report_shows_correct(self):
        with open("/app/profile_report.json") as f:
            report = json.load(f)
        assert report["results"]["correct"] is True, (
            "Profile report indicates kernel output is incorrect"
        )

    def test_report_cycles_consistent(self):
        """Verify the reported cycle count matches actual kernel execution."""
        with open("/app/profile_report.json") as f:
            report = json.load(f)
        reported_cycles = report["results"]["cycles"]

        # Run the kernel independently to cross-check the report
        seed = report["configuration"].get("seed", 123)
        random.seed(seed)
        correct, actual_cycles = _run_kernel(
            report["configuration"]["tree_height"],
            report["configuration"]["rounds"],
            report["configuration"]["batch_size"]
        )
        assert reported_cycles == actual_cycles, (
            f"Report claims {reported_cycles} cycles but kernel actually produces "
            f"{actual_cycles} cycles. Regenerate the report with: "
            "python3 /app/vliw_profiler.py report -o /app/profile_report.json"
        )

    def test_report_utilization_data(self):
        """Verify slot utilization data is present for all engines."""
        with open("/app/profile_report.json") as f:
            report = json.load(f)
        util = report["slot_utilization"]
        for engine in ["alu", "valu", "load", "store", "flow"]:
            assert engine in util, f"Missing utilization data for engine: {engine}"
            assert "slots_used" in util[engine], f"Missing slots_used for {engine}"
            assert "utilization_pct" in util[engine], (
                f"Missing utilization_pct for {engine}"
            )
            assert isinstance(util[engine]["slots_used"], int), (
                f"slots_used for {engine} must be an integer"
            )

    def test_report_performance_target(self):
        """Verify the profile report confirms the performance target is met."""
        with open("/app/profile_report.json") as f:
            report = json.load(f)
        cycles = report["results"]["cycles"]
        assert cycles < 17000, (
            f"Profile report shows {cycles} cycles, target is < 17000"
        )
