#!/usr/bin/env python3
"""
Generate the P-256 Montgomery arithmetic C implementation,
Makefile, and toolchain helper scripts.
"""

import os
import stat

P256 = 2**256 - 2**224 + 2**192 + 2**96 - 1
R = 2**256
MASK64 = (1 << 64) - 1

# Compute R^2 mod p
R2 = pow(R, 2, P256)
R2_limbs = [(R2 >> (64 * i)) & MASK64 for i in range(4)]

# Compute R mod p (Montgomery representation of 1)
R_mod_p = R % P256
R_mod_p_limbs = [(R_mod_p >> (64 * i)) & MASK64 for i in range(4)]

# Compute -p^{-1} mod 2^64 (Montgomery constant n0')
p0 = P256 & MASK64
p0_inv = pow(p0, -1, 2**64)
n0_prime = (-p0_inv) % (2**64)

# Compute p - 2 for Fermat's little theorem inversion
pm2 = P256 - 2
pm2_limbs = [(pm2 >> (64 * i)) & MASK64 for i in range(4)]

# P-256 limbs
p_limbs = [(P256 >> (64 * i)) & MASK64 for i in range(4)]

# =====================================================================
# 1. Generate p256_mont.c
# =====================================================================

c_code = f"""/*
 * P-256 Montgomery-domain field arithmetic.
 * Generated by solve script with computed constants.
 *
 * p_256 = 2^256 - 2^224 + 2^192 + 2^96 - 1
 * R = 2^256, n0' = -p^{{-1}} mod 2^64 = {n0_prime}
 */

#include <stdint.h>
#include <string.h>

typedef unsigned __int128 uint128_t;

static const uint64_t P[4] = {{
    0x{p_limbs[0]:016X}ULL, 0x{p_limbs[1]:016X}ULL,
    0x{p_limbs[2]:016X}ULL, 0x{p_limbs[3]:016X}ULL
}};

/* R^2 mod p_256 — precomputed for tomont conversion */
static const uint64_t R2_MOD_P[4] = {{
    0x{R2_limbs[0]:016X}ULL, 0x{R2_limbs[1]:016X}ULL,
    0x{R2_limbs[2]:016X}ULL, 0x{R2_limbs[3]:016X}ULL
}};

/* R mod p_256 — Montgomery representation of 1 */
static const uint64_t MONT_ONE[4] = {{
    0x{R_mod_p_limbs[0]:016X}ULL, 0x{R_mod_p_limbs[1]:016X}ULL,
    0x{R_mod_p_limbs[2]:016X}ULL, 0x{R_mod_p_limbs[3]:016X}ULL
}};

/* p_256 - 2, for Fermat's little theorem inversion */
static const uint64_t PM2[4] = {{
    0x{pm2_limbs[0]:016X}ULL, 0x{pm2_limbs[1]:016X}ULL,
    0x{pm2_limbs[2]:016X}ULL, 0x{pm2_limbs[3]:016X}ULL
}};

static void mul_4x4(uint64_t r[8], const uint64_t a[4], const uint64_t b[4]) {{
    memset(r, 0, 8 * sizeof(uint64_t));
    for (int i = 0; i < 4; i++) {{
        uint64_t carry = 0;
        for (int j = 0; j < 4; j++) {{
            uint128_t acc = (uint128_t)a[i] * b[j] + r[i + j] + carry;
            r[i + j] = (uint64_t)acc;
            carry = (uint64_t)(acc >> 64);
        }}
        r[i + 4] = carry;
    }}
}}

static void mont_reduce(uint64_t z[4], const uint64_t t_in[8]) {{
    uint64_t t[9];
    memcpy(t, t_in, 8 * sizeof(uint64_t));
    t[8] = 0;

    for (int i = 0; i < 4; i++) {{
        uint64_t m = t[i]; /* n0' = 1 for P-256 */
        uint64_t carry = 0;
        for (int j = 0; j < 4; j++) {{
            uint128_t acc = (uint128_t)m * P[j] + t[i + j] + carry;
            t[i + j] = (uint64_t)acc;
            carry = (uint64_t)(acc >> 64);
        }}
        for (int j = i + 4; j <= 8; j++) {{
            uint128_t acc = (uint128_t)t[j] + carry;
            t[j] = (uint64_t)acc;
            carry = (uint64_t)(acc >> 64);
            if (!carry) break;
        }}
    }}

    uint64_t borrow = 0;
    uint64_t diff[4];
    for (int j = 0; j < 4; j++) {{
        uint64_t tmp = t[j + 4] - P[j];
        uint64_t b1 = (t[j + 4] < P[j]) ? 1 : 0;
        diff[j] = tmp - borrow;
        uint64_t b2 = (tmp < borrow) ? 1 : 0;
        borrow = b1 | b2;
    }}

    int use_orig = (t[8] == 0 && borrow != 0);
    for (int j = 0; j < 4; j++) {{
        z[j] = use_orig ? t[j + 4] : diff[j];
    }}
}}

void p256_montmul(uint64_t z[4], const uint64_t x[4], const uint64_t y[4]) {{
    uint64_t a[4], b[4];
    memcpy(a, x, 32);
    memcpy(b, y, 32);
    uint64_t t[8];
    mul_4x4(t, a, b);
    mont_reduce(z, t);
}}

void p256_montsqr(uint64_t z[4], const uint64_t x[4]) {{
    p256_montmul(z, x, x);
}}

void p256_montadd(uint64_t z[4], const uint64_t x[4], const uint64_t y[4]) {{
    uint64_t a[4], b[4];
    memcpy(a, x, 32);
    memcpy(b, y, 32);

    uint64_t sum[4];
    uint64_t carry = 0;
    for (int j = 0; j < 4; j++) {{
        uint128_t s = (uint128_t)a[j] + b[j] + carry;
        sum[j] = (uint64_t)s;
        carry = (uint64_t)(s >> 64);
    }}

    uint64_t borrow = 0;
    uint64_t diff[4];
    for (int j = 0; j < 4; j++) {{
        uint64_t tmp = sum[j] - P[j];
        uint64_t b1 = (sum[j] < P[j]) ? 1 : 0;
        diff[j] = tmp - borrow;
        uint64_t b2 = (tmp < borrow) ? 1 : 0;
        borrow = b1 | b2;
    }}

    int need_sub = (carry != 0) || (borrow == 0);
    for (int j = 0; j < 4; j++) {{
        z[j] = need_sub ? diff[j] : sum[j];
    }}
}}

void p256_montsub(uint64_t z[4], const uint64_t x[4], const uint64_t y[4]) {{
    uint64_t a[4], b[4];
    memcpy(a, x, 32);
    memcpy(b, y, 32);

    uint64_t diff[4];
    uint64_t borrow = 0;
    for (int j = 0; j < 4; j++) {{
        uint64_t tmp = a[j] - b[j];
        uint64_t b1 = (a[j] < b[j]) ? 1 : 0;
        diff[j] = tmp - borrow;
        uint64_t b2 = (tmp < borrow) ? 1 : 0;
        borrow = b1 | b2;
    }}

    if (borrow) {{
        uint64_t carry = 0;
        for (int j = 0; j < 4; j++) {{
            uint128_t s = (uint128_t)diff[j] + P[j] + carry;
            diff[j] = (uint64_t)s;
            carry = (uint64_t)(s >> 64);
        }}
    }}

    memcpy(z, diff, 32);
}}

void p256_tomont(uint64_t z[4], const uint64_t x[4]) {{
    p256_montmul(z, x, R2_MOD_P);
}}

void p256_frommont(uint64_t z[4], const uint64_t x[4]) {{
    uint64_t one[4] = {{1, 0, 0, 0}};
    p256_montmul(z, x, one);
}}

void p256_inv(uint64_t z[4], const uint64_t x[4]) {{
    uint64_t result[4];
    memcpy(result, MONT_ONE, 32);

    uint64_t base[4];
    memcpy(base, x, 32);

    int started = 0;
    for (int i = 3; i >= 0; i--) {{
        for (int bit = 63; bit >= 0; bit--) {{
            if (started) {{
                p256_montsqr(result, result);
            }}
            if ((PM2[i] >> bit) & 1) {{
                if (started) {{
                    p256_montmul(result, result, base);
                }} else {{
                    memcpy(result, base, 32);
                    started = 1;
                }}
            }}
        }}
    }}

    memcpy(z, result, 32);
}}
"""

with open("/app/p256_mont.c", "w") as f:
    f.write(c_code)

print("Generated /app/p256_mont.c")
print(f"  p_256 = {hex(P256)}")
print(f"  R^2 mod p = {hex(R2)}")
print(f"  n0' = {n0_prime}")

# =====================================================================
# 2. Generate Makefile
# =====================================================================

makefile = """CC = gcc
CFLAGS = -O2
LIB_SO = libp256mont.so
LIB_A = libp256mont.a
OBJ = p256_mont.o

.PHONY: all static check-symbols analyze verify-prime clean

all: $(LIB_SO)

static: $(LIB_A)

$(LIB_SO): p256_mont.c p256_mont.h
\t$(CC) -shared -fPIC $(CFLAGS) -o $@ $<

$(OBJ): p256_mont.c p256_mont.h
\t$(CC) -c -fPIC $(CFLAGS) -o $@ $<

$(LIB_A): $(OBJ)
\tar rcs $@ $<

check-symbols: $(LIB_SO)
\tnm -D $(LIB_SO) | grep ' T p256_' | awk '{print $$3}' | sort > symbol_manifest.txt

analyze: $(LIB_SO)
\tpython3 /app/_analyze.py

verify-prime:
\tpython3 /app/_verify_prime.py

clean:
\trm -f $(LIB_SO) $(LIB_A) $(OBJ) symbol_manifest.txt build_analysis.json prime_verification.txt
"""

with open("/app/Makefile", "w") as f:
    f.write(makefile)

print("Generated /app/Makefile")

# =====================================================================
# 3. Generate _analyze.py helper
# =====================================================================

analyze_py = '''#!/usr/bin/env python3
"""
Analyze the built shared library using objdump and size.
Produces build_analysis.json with instruction count and section sizes.
"""
import subprocess
import json
import re

# Count instructions in p256_montmul via objdump -d
objdump_out = subprocess.check_output(
    ["objdump", "-d", "libp256mont.so"]
).decode()

in_func = False
instr_count = 0
for line in objdump_out.split("\\n"):
    if "<p256_montmul>" in line and ":" in line:
        in_func = True
        continue
    if in_func:
        stripped = line.strip()
        if stripped == "":
            if instr_count > 0:
                break
        elif re.match(r"[0-9a-f]+:", stripped):
            instr_count += 1
        elif not stripped.startswith("..."):
            break

# Get section sizes via size
size_out = subprocess.check_output(["size", "libp256mont.so"]).decode()
size_line = size_out.strip().split("\\n")[1]
parts = size_line.split()

result = {
    "montmul_instruction_count": instr_count,
    "text_size": int(parts[0]),
    "data_size": int(parts[1]),
    "bss_size": int(parts[2])
}

with open("build_analysis.json", "w") as f:
    json.dump(result, f, indent=2)

print(f"Analysis: {instr_count} instructions in p256_montmul, "
      f"text={parts[0]}, data={parts[1]}, bss={parts[2]}")
'''

with open("/app/_analyze.py", "w") as f:
    f.write(analyze_py)
os.chmod("/app/_analyze.py", os.stat("/app/_analyze.py").st_mode | stat.S_IEXEC)

print("Generated /app/_analyze.py")

# =====================================================================
# 4. Generate _verify_prime.py helper
# =====================================================================

verify_prime_py = '''#!/usr/bin/env python3
"""
Extract the P-256 field prime from openssl ecparam output and verify
it matches the constant used in the library implementation.
"""
import subprocess
import re

# Known P-256 prime
p_256 = 2**256 - 2**224 + 2**192 + 2**96 - 1

# Extract curve parameters from openssl
try:
    output = subprocess.check_output(
        ["openssl", "ecparam", "-name", "prime256v1",
         "-param_enc", "explicit", "-text", "-noout"],
        stderr=subprocess.STDOUT
    ).decode()
except subprocess.CalledProcessError as e:
    print(f"openssl failed: {e}")
    with open("prime_verification.txt", "w") as f:
        f.write("MISMATCH\\n")
    exit(1)

# Parse the Prime field from the text output
# Format is colon-separated hex bytes on indented lines after "Prime:"
in_prime = False
hex_parts = []
for line in output.split("\\n"):
    stripped = line.strip()
    if stripped.startswith("Prime"):
        in_prime = True
        continue
    if in_prime:
        if line.startswith("    ") or line.startswith("\\t"):
            clean = stripped.replace(":", "").replace(" ", "")
            if clean and all(c in "0123456789abcdef" for c in clean):
                hex_parts.append(clean)
            else:
                if hex_parts:
                    break
        else:
            break

if not hex_parts:
    print("Failed to parse prime from openssl output")
    with open("prime_verification.txt", "w") as f:
        f.write("MISMATCH\\n")
    exit(1)

hex_str = "".join(hex_parts)
extracted_prime = int(hex_str, 16)

result = "MATCH" if extracted_prime == p_256 else "MISMATCH"
with open("prime_verification.txt", "w") as f:
    f.write(result + "\\n")

print(f"OpenSSL prime: {hex(extracted_prime)}")
print(f"Library prime: {hex(p_256)}")
print(f"Result: {result}")
'''

with open("/app/_verify_prime.py", "w") as f:
    f.write(verify_prime_py)
os.chmod("/app/_verify_prime.py", os.stat("/app/_verify_prime.py").st_mode | stat.S_IEXEC)

print("Generated /app/_verify_prime.py")
print("All solution files generated successfully.")
