"""Tests for metabolic assessment pipeline.

Compares solver's /app/results.json against precomputed reference
values in /tmp/ref_values.json (generated by compute_ref.py).
"""


import json
import os

import pytest

TOLERANCE = 1e-4
ENVELOPE_TOL = 0.05


@pytest.fixture(scope="module")
def results():
    path = "/app/results.json"
    assert os.path.exists(path), f"{path} not found"
    with open(path) as f:
        data = json.load(f)
    return data


@pytest.fixture(scope="module")
def ref():
    path = "/tmp/ref_values.json"
    assert os.path.exists(path), (
        f"{path} not found — compute_ref.py must run before pytest"
    )
    with open(path) as f:
        data = json.load(f)
    return data


# ---- Structure tests ----

def test_results_is_dict(results):
    assert isinstance(results, dict)


def test_required_keys(results):
    required = [
        "aerobic_growth",
        "anaerobic_growth",
        "essential_genes",
        "essential_reactions",
        "isozyme_buffered",
        "carbon_utilization",
        "flux_ranges",
        "synthetic_lethals",
        "chokepoint_metabolites",
        "production_envelope",
    ]
    for key in required:
        assert key in results, f"Missing key: {key}"


# ---- Growth rates ----

def test_aerobic_growth(results, ref):
    assert abs(results["aerobic_growth"] - ref["aerobic"]) < TOLERANCE, (
        f"Expected ~{ref['aerobic']:.6f}, got {results['aerobic_growth']}"
    )


def test_anaerobic_growth(results, ref):
    assert abs(results["anaerobic_growth"] - ref["anaerobic"]) < TOLERANCE, (
        f"Expected ~{ref['anaerobic']:.6f}, got {results['anaerobic_growth']}"
    )


def test_aerobic_greater_than_anaerobic(results):
    assert results["aerobic_growth"] > results["anaerobic_growth"], (
        f"Aerobic ({results['aerobic_growth']}) should exceed "
        f"anaerobic ({results['anaerobic_growth']})"
    )


# ---- Essential genes ----

def test_essential_genes_sorted(results):
    genes = results["essential_genes"]
    assert genes == sorted(genes), "essential_genes must be sorted"


def test_essential_genes_match(results, ref):
    assert results["essential_genes"] == ref["essential_genes"], (
        f"Expected {ref['essential_genes']}, got {results['essential_genes']}"
    )


# ---- Essential reactions ----

def test_essential_reactions_sorted(results):
    rxns = results["essential_reactions"]
    assert rxns == sorted(rxns), "essential_reactions must be sorted"


def test_essential_reactions_match(results, ref):
    assert results["essential_reactions"] == ref["essential_reactions"], (
        f"Expected {ref['essential_reactions']}, "
        f"got {results['essential_reactions']}"
    )


def test_essential_reactions_no_exchange(results):
    for rxn_id in results["essential_reactions"]:
        assert not rxn_id.startswith("EX_"), (
            f"Exchange reaction {rxn_id} should not be in essential_reactions"
        )


# ---- Isozyme-buffered reactions ----

def test_isozyme_buffered_sorted(results):
    buf = results["isozyme_buffered"]
    assert buf == sorted(buf), "isozyme_buffered must be sorted"


def test_isozyme_buffered_match(results, ref):
    assert results["isozyme_buffered"] == ref["isozyme_buffered"], (
        f"Expected {ref['isozyme_buffered']}, "
        f"got {results['isozyme_buffered']}"
    )


def test_isozyme_buffered_subset_of_essential(results):
    ess_set = set(results["essential_reactions"])
    for rxn_id in results["isozyme_buffered"]:
        assert rxn_id in ess_set, (
            f"{rxn_id} in isozyme_buffered but not in essential_reactions"
        )


# ---- Carbon utilization ----

def test_carbon_utilization_keys(results, ref):
    expected = set(ref["carbon"].keys())
    actual = set(results["carbon_utilization"].keys())
    assert actual == expected, (
        f"Expected carbon keys {expected}, got {actual}"
    )


def test_carbon_utilization_values(results, ref):
    for src, expected_val in ref["carbon"].items():
        actual_val = results["carbon_utilization"][src]
        assert abs(actual_val - expected_val) < TOLERANCE, (
            f"Carbon {src}: expected {expected_val:.6f}, got {actual_val}"
        )


# ---- Flux ranges ----

def test_flux_ranges_keys(results, ref):
    expected = set(ref["fva"].keys())
    actual = set(results["flux_ranges"].keys())
    assert actual == expected, (
        f"Expected flux range keys {expected}, got {actual}"
    )


def test_flux_ranges_structure(results):
    for rxn_id, entry in results["flux_ranges"].items():
        assert "minimum" in entry, f"Missing 'minimum' for {rxn_id}"
        assert "maximum" in entry, f"Missing 'maximum' for {rxn_id}"


def test_flux_ranges_values(results, ref):
    for rxn_id, expected in ref["fva"].items():
        actual = results["flux_ranges"][rxn_id]
        assert abs(actual["minimum"] - expected["minimum"]) < TOLERANCE, (
            f"Flux {rxn_id} min: expected {expected['minimum']:.6f}, "
            f"got {actual['minimum']}"
        )
        assert abs(actual["maximum"] - expected["maximum"]) < TOLERANCE, (
            f"Flux {rxn_id} max: expected {expected['maximum']:.6f}, "
            f"got {actual['maximum']}"
        )


def test_flux_ranges_min_leq_max(results):
    for rxn_id, entry in results["flux_ranges"].items():
        assert entry["minimum"] <= entry["maximum"] + TOLERANCE, (
            f"Flux {rxn_id}: min ({entry['minimum']}) > max ({entry['maximum']})"
        )


# ---- Synthetic lethals ----

def test_synthetic_lethals_match(results, ref):
    assert results["synthetic_lethals"] == ref["synthetic_lethals"], (
        f"Synthetic lethals mismatch.\n"
        f"Expected {len(ref['synthetic_lethals'])} pairs: "
        f"{ref['synthetic_lethals']}\n"
        f"Got {len(results['synthetic_lethals'])} pairs: "
        f"{results['synthetic_lethals']}"
    )


def test_synthetic_lethals_pair_format(results):
    for pair in results["synthetic_lethals"]:
        assert len(pair) == 2, f"Pair should have 2 elements: {pair}"
        assert pair == sorted(pair), f"Pair not sorted: {pair}"


def test_synthetic_lethals_outer_sorted(results):
    pairs = results["synthetic_lethals"]
    assert pairs == sorted(pairs), "Outer list of synthetic lethals not sorted"


# ---- Chokepoint metabolites ----

def test_chokepoint_metabolites_sorted(results):
    cp = results["chokepoint_metabolites"]
    assert cp == sorted(cp), "chokepoint_metabolites must be sorted"


def test_chokepoint_metabolites_match(results, ref):
    assert results["chokepoint_metabolites"] == ref["chokepoint_metabolites"], (
        f"Expected {ref['chokepoint_metabolites']}, "
        f"got {results['chokepoint_metabolites']}"
    )


def test_chokepoint_metabolites_are_cytoplasmic(results):
    for met_id in results["chokepoint_metabolites"]:
        assert met_id.endswith("_c"), (
            f"Chokepoint {met_id} should be cytoplasmic (ending in _c)"
        )


# ---- Production envelope ----

def test_envelope_length(results):
    env = results["production_envelope"]
    assert len(env["growth_rates"]) == 11, (
        f"Expected 11 growth rates, got {len(env['growth_rates'])}"
    )
    assert len(env["max_ethanol"]) == 11, (
        f"Expected 11 max_ethanol, got {len(env['max_ethanol'])}"
    )


def test_envelope_growth_rates(results, ref):
    actual = results["production_envelope"]["growth_rates"]
    expected = ref["production_envelope"]["growth_rates"]
    for i in range(11):
        assert abs(actual[i] - expected[i]) < TOLERANCE, (
            f"Growth rate [{i}]: expected {expected[i]:.6f}, got {actual[i]}"
        )


def test_envelope_ethanol_values(results, ref):
    actual = results["production_envelope"]["max_ethanol"]
    expected = ref["production_envelope"]["max_ethanol"]
    for i in range(11):
        assert abs(actual[i] - expected[i]) < ENVELOPE_TOL, (
            f"Max ethanol [{i}]: expected {expected[i]:.4f}, got {actual[i]}"
        )


def test_envelope_zero_growth_positive_ethanol(results):
    env = results["production_envelope"]
    assert env["max_ethanol"][0] > 1.0, (
        f"At zero growth, ethanol should be positive, got {env['max_ethanol'][0]}"
    )


def test_envelope_growth_monotonic(results):
    gr = results["production_envelope"]["growth_rates"]
    for i in range(1, len(gr)):
        assert gr[i] >= gr[i - 1] - TOLERANCE, (
            f"Growth rates not monotonic at index {i}"
        )
