#!/usr/bin/env python3
"""
FL2 Proxy Server - Bot Management Module

The FL2 proxy is Cloudflare's next-generation HTTP proxy written in Rust.
This Python simulation models the proxy's bot management feature loading
and request scoring behavior.

Each module running on the proxy has memory limits to avoid unbounded
consumption and to pre-allocate memory as a performance optimization.
The bot management system has a limit on the number of ML features that
can be used at runtime (MAX_FEATURES = 200), which is used for memory
pre-allocation of the feature scoring array.
"""

import json
import sys
import logging
from datetime import datetime

logging.basicConfig(
    filename='/app/logs/proxy.log',
    level=logging.INFO,
    format='%(asctime)s %(levelname)s %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)

MAX_FEATURES = 200  # Pre-allocation limit for performance optimization
FEATURE_FILE = "/app/features/bot_features.json"


class BotScoringModule:
    """Bot management ML scoring module.

    Loads feature configuration and scores incoming requests for
    bot likelihood. Features are pre-allocated in memory for
    performance optimization during request processing.
    """

    def __init__(self):
        self.features = None
        self.feature_memory = None  # Pre-allocated scoring memory slots

    def load_features(self, feature_file_path):
        """Load bot management feature configuration.

        Pre-allocates memory for features based on MAX_FEATURES limit.
        The feature file is generated by the feature pipeline and
        contains the ML model's input feature definitions.

        Raises:
            RuntimeError: If feature count exceeds MAX_FEATURES limit.
        """
        with open(feature_file_path, 'r') as f:
            config = json.load(f)

        features = config.get("features", [])
        feature_count = len(features)

        logger.info(f"Loading {feature_count} features from {feature_file_path}")

        # Pre-allocate memory for features - HARD LIMIT
        # This mirrors the Rust code: Vec::with_capacity(MAX_FEATURES)
        # followed by Result::unwrap() on the bounds check
        if feature_count > MAX_FEATURES:
            error_msg = (
                f"Feature count {feature_count} exceeds maximum allowed "
                f"{MAX_FEATURES}. Cannot pre-allocate memory for feature scoring."
            )
            logger.error(error_msg)
            raise RuntimeError(
                f"called Result::unwrap() on an Err value: "
                f"FeatureLimitExceeded({{count: {feature_count}, "
                f"max: {MAX_FEATURES}}})"
            )

        # Pre-allocate scoring memory
        self.feature_memory = [0.0] * MAX_FEATURES
        self.features = features

        logger.info(f"Successfully loaded {feature_count} features")
        return True

    def score_request(self, request_data):
        """Score a request for bot likelihood.

        Args:
            request_data: Dictionary of feature name -> value pairs.

        Returns:
            Float score between 0.0 and 100.0.
        """
        if self.features is None:
            raise RuntimeError("Features not loaded")

        score = 0.0
        for i, feature in enumerate(self.features):
            if feature["enabled"]:
                value = request_data.get(feature["name"], 0)
                self.feature_memory[i] = value * feature["weight"]
                score += self.feature_memory[i]

        num_features = len(self.features) if self.features else 1
        return min(max(score / num_features, 0.0), 100.0)


class ProxyServer:
    """FL2 Proxy Server simulation.

    Handles HTTP request processing through the bot management
    scoring pipeline. Loads feature configuration on startup
    and scores each incoming request.
    """

    def __init__(self):
        self.bot_module = BotScoringModule()
        self.running = False
        self.request_count = 0
        self.error_count = 0

    def initialize(self):
        """Initialize the proxy server and load all modules.

        On failure, the server panics (simulating Rust's unwrap behavior)
        and exits with a non-zero status code.
        """
        logger.info("Initializing FL2 proxy server...")

        try:
            self.bot_module.load_features(FEATURE_FILE)
            self.running = True
            logger.info("FL2 proxy server initialized successfully")
            return True
        except RuntimeError as e:
            logger.error(f"FL2 proxy initialization failed: {e}")
            # Simulate Rust panic behavior - hard crash, no recovery
            logger.critical(
                f"thread fl2_worker_thread panicked: {e}\n"
                f"note: run with `RUST_BACKTRACE=1` for a backtrace"
            )
            raise SystemExit(1)
        except Exception as e:
            logger.error(f"Unexpected error during initialization: {e}")
            raise

    def handle_request(self, request_data):
        """Handle an incoming HTTP request through the bot scoring pipeline."""
        if not self.running:
            return {"status": 503, "error": "Service Unavailable"}

        self.request_count += 1

        try:
            bot_score = self.bot_module.score_request(request_data)
            return {
                "status": 200,
                "bot_score": bot_score,
                "request_id": self.request_count
            }
        except Exception as e:
            self.error_count += 1
            logger.error(f"Request handling error: {e}")
            return {"status": 500, "error": "Internal Server Error"}

    def get_status(self):
        """Return current server status."""
        return {
            "running": self.running,
            "requests_processed": self.request_count,
            "errors": self.error_count,
            "features_loaded": (
                len(self.bot_module.features)
                if self.bot_module.features else 0
            )
        }


def main():
    server = ProxyServer()
    server.initialize()

    # Simulate handling some requests
    test_requests = [
        {"user_agent_entropy": 0.5, "request_rate_1m": 10},
        {"user_agent_entropy": 0.9, "request_rate_1m": 1000},
        {"user_agent_entropy": 0.1, "request_rate_1m": 1},
    ]

    for req in test_requests:
        result = server.handle_request(req)
        print(f"Request result: {result}")

    print(f"Server status: {server.get_status()}")


if __name__ == "__main__":
    main()
