#!/usr/bin/env python3
"""
Generate the correct fir_engine.sv implementation.

Architecture:
  - Dual-bank (shadow + active) coefficient storage for atomic reconfiguration.
  - cfg_wr writes to shadow bank; cfg_done copies shadow -> active in one cycle.
  - NUM_TAPS-stage delay line shift register, clocked on din_valid.
  - Combinational MAC: sum of tap[i] * active_coeff[i].
  - 2-stage valid shift register for 1-cycle output latency.
  - Coefficient banks have no async reset (survive rst_n).
"""

NUM_TAPS = 8

sv_source = """\
// fir_engine.sv — generated by solve.sh

module fir_engine
  import fir_pkg::*;
(
  input  logic                        clk,
  input  logic                        rst_n,
  input  logic                        cfg_wr,
  input  logic [2:0]                  cfg_addr,
  input  logic signed [COEFF_W-1:0]   cfg_data,
  input  logic                        cfg_done,
  input  logic signed [DATA_W-1:0]    din,
  input  logic                        din_valid,
  output logic signed [ACC_W-1:0]     dout,
  output logic                        dout_valid
);

  // ---- Dual-bank coefficient storage ----
  // Shadow bank: written by cfg_wr, not visible to datapath.
  // Active bank: copied from shadow on cfg_done strobe.
  // Neither bank has async reset — coefficients survive rst_n.
  logic signed [COEFF_W-1:0] shadow_bank [0:NUM_TAPS-1];
  logic signed [COEFF_W-1:0] active_bank [0:NUM_TAPS-1];

  always_ff @(posedge clk) begin
    if (cfg_wr)
      shadow_bank[cfg_addr] <= cfg_data;
  end

  always_ff @(posedge clk) begin
    if (cfg_done) begin
      for (int i = 0; i < NUM_TAPS; i++)
        active_bank[i] <= shadow_bank[i];
    end
  end

  // ---- Delay line (tap shift register) ----
  // Shifts on din_valid; cleared by async reset.
  logic signed [DATA_W-1:0] tap [0:NUM_TAPS-1];

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      for (int i = 0; i < NUM_TAPS; i++)
        tap[i] <= '0;
    end else if (din_valid) begin
      tap[0] <= din;
      for (int i = 1; i < NUM_TAPS; i++)
        tap[i] <= tap[i-1];
    end
  end

  // ---- Combinational multiply-accumulate ----
  logic signed [ACC_W-1:0] mac;

  always_comb begin
    mac = '0;
    for (int i = 0; i < NUM_TAPS; i++)
      mac = mac + (tap[i] * active_bank[i]);
  end

  // ---- Output pipeline (1-cycle latency) ----
  // valid_sr[0] captures din_valid; valid_sr[1] drives dout_valid.
  // dout is registered when valid_sr[0] is high, so dout_valid
  // aligns with the registered MAC result one cycle after din_valid.
  logic [1:0] valid_sr;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      valid_sr <= '0;
      dout     <= '0;
    end else begin
      valid_sr <= {valid_sr[0], din_valid};
      if (valid_sr[0])
        dout <= mac;
    end
  end

  assign dout_valid = valid_sr[1];

endmodule
"""

with open("/app/src/fir_engine.sv", "w") as f:
    f.write(sv_source)

print(f"Generated fir_engine.sv ({len(sv_source.splitlines())} lines)")
