/* CTR_DRBG C Library - AES-256 Implementation */
#ifndef CTRDRBG_H
#define CTRDRBG_H

#include <stdint.h>
#include <stddef.h>

typedef struct {
    uint8_t key[32];
    uint8_t v[16];
    int keylen;
    int seedlen;
    int use_df;
} CTR_DRBG_CTX;

/* Initialize a CTR_DRBG context.
 * keylen: AES key length in bytes (16, 24, or 32)
 * use_df: 1 to use derivation function, 0 for no-df mode */
void ctr_drbg_init(CTR_DRBG_CTX *ctx, int keylen, int use_df);

/* Instantiate the DRBG with entropy, nonce, and optional personalization.
 * Returns 0 on success, -1 on error. */
int ctr_drbg_instantiate(CTR_DRBG_CTX *ctx,
                         const uint8_t *entropy, size_t entropy_len,
                         const uint8_t *nonce, size_t nonce_len,
                         const uint8_t *pers, size_t pers_len);

/* Generate pseudorandom bytes.
 * output: buffer to receive generated bytes
 * output_len: number of bytes to generate
 * additional: optional additional input (NULL if none)
 * additional_len: length of additional input (0 if none)
 * Returns 0 on success, -1 on error. */
int ctr_drbg_generate(CTR_DRBG_CTX *ctx,
                      uint8_t *output, size_t output_len,
                      const uint8_t *additional, size_t additional_len);

/* Retrieve current internal state for testing.
 * key_out: buffer of at least keylen bytes (NULL to skip)
 * v_out: buffer of at least 16 bytes (NULL to skip) */
void ctr_drbg_get_state(const CTR_DRBG_CTX *ctx,
                        uint8_t *key_out, uint8_t *v_out);

#endif
