#!/usr/bin/env bash
set -euo pipefail
umask 077

fail() {
    printf '{"code":"%s","state":"error"}\n' "$1" >&2
    exit 2
}

(( $# == 0 )) || fail arguments_forbidden
required=(
    QWEN_RECOVERED_SFT_PROJECT_DIR
    QWEN_RECOVERED_SFT_EXPECTED_PROJECT_REVISION
    QWEN_RECOVERED_SFT_EXPECTED_FINALIZER_SHA256
    QWEN_RECOVERED_SFT_EXPECTED_WORKER_SHA256
    QWEN_RECOVERED_SFT_PACKAGE_MANIFEST
    QWEN_RECOVERED_SFT_EXPECTED_PACKAGE_MANIFEST_SHA256
    QWEN_RECOVERED_SFT_SOURCE_DIR
    QWEN_RECOVERED_SFT_EXPECTED_RESULTS_SHA256
    QWEN_RECOVERED_SFT_EXPECTED_MERGE_MANIFEST_SHA256
    QWEN_RECOVERED_SFT_EXPECTED_RECOVERED_CERTIFICATE_SHA256
    QWEN_RECOVERED_SFT_RETRY_CERTIFICATE
    QWEN_RECOVERED_SFT_EXPECTED_RETRY_CERTIFICATE_SHA256
    QWEN_RECOVERED_SFT_SUPERSEDING_CERTIFICATE
    QWEN_RECOVERED_SFT_EXPECTED_SUPERSEDING_CERTIFICATE_SHA256
    QWEN_RECOVERED_SFT_POSTRUN_RECEIPT
    QWEN_RECOVERED_SFT_EXPECTED_POSTRUN_RECEIPT_SHA256
    QWEN_RECOVERED_SFT_CANONICAL_TASK_FILE
    QWEN_RECOVERED_SFT_EXPECTED_CANONICAL_TASK_FILE_SHA256
    QWEN_RECOVERED_SFT_TASKSET_ID
    QWEN_RECOVERED_SFT_DATASET_REVISION
    QWEN_RECOVERED_SFT_OUTPUT_ROOT
    QWEN_RECOVERED_SFT_OUTPUT_DIR
    QWEN_RECOVERED_SFT_EXPECTED_COUNT
    QWEN_RECOVERED_SFT_EXPECTED_POSITIVE
    QWEN_RECOVERED_SFT_EXPECTED_ZERO
    QWEN_RECOVERED_SFT_EXPECTED_ERROR
    QWEN_RECOVERED_SFT_EXPECTED_SELECTED_POSITIVE
    QWEN_RECOVERED_SFT_EXPECTED_STRICT_FAILURES
    QWEN_RECOVERED_SFT_VALIDATION_PERMYRIAD
    QWEN_RECOVERED_SFT_SPLIT_SALT
    QWEN_RECOVERED_SFT_JOBID_FILE
)
for variable in "${required[@]}"; do
    value=${!variable:-}
    [[ -n $value && $value != *,* && $value != *$'\n'* && $value != *$'\r'* ]] \
        || fail required_environment_invalid
done
[[ -n ${TMUX:-} && -n ${TMUX_PANE:-} \
    && $(tmux display-message -p -t "$TMUX_PANE" '#S:#W.#P') == swebench_vmvm:Launcher.0 ]] \
    || fail launcher_pane_mismatch
[[ $QWEN_RECOVERED_SFT_EXPECTED_PROJECT_REVISION =~ ^[0-9a-f]{40}$ \
    && $QWEN_RECOVERED_SFT_DATASET_REVISION =~ ^[0-9a-f]{40}$ ]] \
    || fail revision_invalid
for variable in \
    QWEN_RECOVERED_SFT_EXPECTED_FINALIZER_SHA256 \
    QWEN_RECOVERED_SFT_EXPECTED_WORKER_SHA256 \
    QWEN_RECOVERED_SFT_EXPECTED_PACKAGE_MANIFEST_SHA256 \
    QWEN_RECOVERED_SFT_EXPECTED_RESULTS_SHA256 \
    QWEN_RECOVERED_SFT_EXPECTED_MERGE_MANIFEST_SHA256 \
    QWEN_RECOVERED_SFT_EXPECTED_RECOVERED_CERTIFICATE_SHA256 \
    QWEN_RECOVERED_SFT_EXPECTED_RETRY_CERTIFICATE_SHA256 \
    QWEN_RECOVERED_SFT_EXPECTED_SUPERSEDING_CERTIFICATE_SHA256 \
    QWEN_RECOVERED_SFT_EXPECTED_POSTRUN_RECEIPT_SHA256 \
    QWEN_RECOVERED_SFT_EXPECTED_CANONICAL_TASK_FILE_SHA256; do
    [[ ${!variable} =~ ^[0-9a-f]{64}$ ]] || fail digest_invalid
done
for variable in \
    QWEN_RECOVERED_SFT_EXPECTED_COUNT \
    QWEN_RECOVERED_SFT_EXPECTED_POSITIVE \
    QWEN_RECOVERED_SFT_EXPECTED_ZERO \
    QWEN_RECOVERED_SFT_EXPECTED_ERROR \
    QWEN_RECOVERED_SFT_EXPECTED_SELECTED_POSITIVE \
    QWEN_RECOVERED_SFT_EXPECTED_STRICT_FAILURES \
    QWEN_RECOVERED_SFT_VALIDATION_PERMYRIAD; do
    [[ ${!variable} =~ ^[0-9]+$ ]] || fail count_invalid
done
(( QWEN_RECOVERED_SFT_EXPECTED_COUNT > 0 \
    && QWEN_RECOVERED_SFT_EXPECTED_POSITIVE + QWEN_RECOVERED_SFT_EXPECTED_ZERO \
        + QWEN_RECOVERED_SFT_EXPECTED_ERROR == QWEN_RECOVERED_SFT_EXPECTED_COUNT \
    && QWEN_RECOVERED_SFT_EXPECTED_SELECTED_POSITIVE == QWEN_RECOVERED_SFT_EXPECTED_POSITIVE \
    && QWEN_RECOVERED_SFT_VALIDATION_PERMYRIAD < 10000 )) \
    || fail count_contract_invalid
[[ $QWEN_RECOVERED_SFT_EXPECTED_PACKAGE_MANIFEST_SHA256 == c66c279e7cdc7fce30c07f7378d8dc37ce409f6b5d3f764cc15f74119c58f5d9 \
    && $QWEN_RECOVERED_SFT_EXPECTED_RESULTS_SHA256 == 6ecc98adc68b8cad0ba15f160c108e64fe69da89321cd179bbb2dd1a78dd7d31 \
    && $QWEN_RECOVERED_SFT_EXPECTED_MERGE_MANIFEST_SHA256 == 979093d477b46aa1fd4ec098bc1fdce042d9e98cf5bcfc9353e66f4fd7b8f0f1 \
    && $QWEN_RECOVERED_SFT_EXPECTED_RECOVERED_CERTIFICATE_SHA256 == b4732854e7fa8d7d1f5b7772a8a2f1b6708bfd2bccffe5a16f0d50b850e8c228 \
    && $QWEN_RECOVERED_SFT_EXPECTED_RETRY_CERTIFICATE_SHA256 == 1ce10c6cc6815866acfa1d8a0474eaca919030d466eea0d28e2c2ff428656b75 \
    && $QWEN_RECOVERED_SFT_EXPECTED_SUPERSEDING_CERTIFICATE_SHA256 == 025474d6384c5ccbae9159f064c252d9664849a7a1e8f258917c51a7f8366798 \
    && $QWEN_RECOVERED_SFT_EXPECTED_POSTRUN_RECEIPT_SHA256 == 950f3713806a54576fac28b9557dc697d385be18f0eb95c37d30a43a20d2fd3b \
    && $QWEN_RECOVERED_SFT_EXPECTED_CANONICAL_TASK_FILE_SHA256 == 5b2ed7c5b166a6570b46d3dacff680c5ba6ff22f7e02e57e273eb442e6842b8c \
    && $QWEN_RECOVERED_SFT_TASKSET_ID == terminal-bench-vmvm \
    && $QWEN_RECOVERED_SFT_DATASET_REVISION == ac1f30b9ac0e6c6a20a9fe423900d9ed28a6d366 \
    && $QWEN_RECOVERED_SFT_EXPECTED_COUNT == 2499 \
    && $QWEN_RECOVERED_SFT_EXPECTED_POSITIVE == 1588 \
    && $QWEN_RECOVERED_SFT_EXPECTED_ZERO == 887 \
    && $QWEN_RECOVERED_SFT_EXPECTED_ERROR == 24 \
    && $QWEN_RECOVERED_SFT_EXPECTED_SELECTED_POSITIVE == 1588 \
    && $QWEN_RECOVERED_SFT_EXPECTED_STRICT_FAILURES == 279 \
    && $QWEN_RECOVERED_SFT_VALIDATION_PERMYRIAD == 500 \
    && $QWEN_RECOVERED_SFT_SPLIT_SALT == terminal-bench-vmvm-sft-v1 ]] \
    || fail recovered_v6_identity_mismatch

project=$(realpath -e -- "$QWEN_RECOVERED_SFT_PROJECT_DIR")
workflow="$project/user/tianhaowu/terminal_bench_vmvm"
finalizer="$workflow/finalize_qwen_recovered_sft.py"
worker="$workflow/finalize_qwen_recovered_sft.sbatch"
[[ -f $finalizer && ! -L $finalizer && -f $worker && ! -L $worker \
    && "$(git -C "$project" rev-parse --show-toplevel)" == "$project" \
    && "$(git -C "$project" rev-parse HEAD)" == "$QWEN_RECOVERED_SFT_EXPECTED_PROJECT_REVISION" \
    && "$(git -C "$project" rev-parse --abbrev-ref HEAD)" == HEAD \
    && -z "$(git -C "$project" status --porcelain=v1 --untracked-files=all)" \
    && "$(sha256sum "$finalizer" | cut -d' ' -f1)" == "$QWEN_RECOVERED_SFT_EXPECTED_FINALIZER_SHA256" \
    && "$(sha256sum "$worker" | cut -d' ' -f1)" == "$QWEN_RECOVERED_SFT_EXPECTED_WORKER_SHA256" ]] \
    || fail source_identity_invalid
[[ ! -e $QWEN_RECOVERED_SFT_OUTPUT_DIR && ! -L $QWEN_RECOVERED_SFT_OUTPUT_DIR \
    && ! -e $QWEN_RECOVERED_SFT_JOBID_FILE && ! -L $QWEN_RECOVERED_SFT_JOBID_FILE ]] \
    || fail output_exists
jobid_parent=$(realpath -e -- "$(dirname -- "$QWEN_RECOVERED_SFT_JOBID_FILE")")
[[ $QWEN_RECOVERED_SFT_JOBID_FILE == "$jobid_parent/$(basename -- "$QWEN_RECOVERED_SFT_JOBID_FILE")" ]] \
    || fail jobid_path_invalid
reservation="$QWEN_RECOVERED_SFT_JOBID_FILE.lock"
mkdir -m 700 -- "$reservation" 2>/dev/null || fail submission_already_reserved
submitted=0
cleanup() {
    status=$?
    trap - EXIT INT TERM
    if [[ $submitted == 0 ]]; then
        rmdir -- "$reservation" 2>/dev/null || true
    fi
    exit "$status"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

export_names=(
    QWEN_RECOVERED_SFT_PROJECT_DIR
    QWEN_RECOVERED_SFT_EXPECTED_PROJECT_REVISION
    QWEN_RECOVERED_SFT_EXPECTED_FINALIZER_SHA256
    QWEN_RECOVERED_SFT_PACKAGE_MANIFEST
    QWEN_RECOVERED_SFT_EXPECTED_PACKAGE_MANIFEST_SHA256
    QWEN_RECOVERED_SFT_SOURCE_DIR
    QWEN_RECOVERED_SFT_EXPECTED_RESULTS_SHA256
    QWEN_RECOVERED_SFT_EXPECTED_MERGE_MANIFEST_SHA256
    QWEN_RECOVERED_SFT_EXPECTED_RECOVERED_CERTIFICATE_SHA256
    QWEN_RECOVERED_SFT_RETRY_CERTIFICATE
    QWEN_RECOVERED_SFT_EXPECTED_RETRY_CERTIFICATE_SHA256
    QWEN_RECOVERED_SFT_SUPERSEDING_CERTIFICATE
    QWEN_RECOVERED_SFT_EXPECTED_SUPERSEDING_CERTIFICATE_SHA256
    QWEN_RECOVERED_SFT_POSTRUN_RECEIPT
    QWEN_RECOVERED_SFT_EXPECTED_POSTRUN_RECEIPT_SHA256
    QWEN_RECOVERED_SFT_CANONICAL_TASK_FILE
    QWEN_RECOVERED_SFT_EXPECTED_CANONICAL_TASK_FILE_SHA256
    QWEN_RECOVERED_SFT_TASKSET_ID
    QWEN_RECOVERED_SFT_DATASET_REVISION
    QWEN_RECOVERED_SFT_OUTPUT_ROOT
    QWEN_RECOVERED_SFT_OUTPUT_DIR
    QWEN_RECOVERED_SFT_EXPECTED_COUNT
    QWEN_RECOVERED_SFT_EXPECTED_POSITIVE
    QWEN_RECOVERED_SFT_EXPECTED_ZERO
    QWEN_RECOVERED_SFT_EXPECTED_ERROR
    QWEN_RECOVERED_SFT_EXPECTED_SELECTED_POSITIVE
    QWEN_RECOVERED_SFT_EXPECTED_STRICT_FAILURES
    QWEN_RECOVERED_SFT_VALIDATION_PERMYRIAD
    QWEN_RECOVERED_SFT_SPLIT_SALT
)
exports=NONE
for variable in "${export_names[@]}"; do
    exports+=",$variable=${!variable}"
done

submitted=1
jobid=$(sbatch --parsable --export="$exports" "$worker")
jobid=${jobid%%;*}
[[ $jobid =~ ^[1-9][0-9]*$ ]] || fail submission_receipt_invalid
if ! (set -o noclobber; printf '%s\n' "$jobid" >"$QWEN_RECOVERED_SFT_JOBID_FILE"); then
    fail submission_receipt_write_failed
fi
chmod 0600 "$QWEN_RECOVERED_SFT_JOBID_FILE"
rmdir -- "$reservation"
submitted=2
trap - EXIT INT TERM
printf '{"job_id":%s,"state":"submitted"}\n' "$jobid"
