
-- Club Analytics Pipeline
-- Fix all five views and the stored function below to produce correct results.

-- Drop existing objects to allow re-creation
DROP FUNCTION IF EXISTS cd.member_value_score(INT) CASCADE;
DROP VIEW IF EXISTS cd.booking_anomaly_report CASCADE;
DROP VIEW IF EXISTS cd.revenue_rolling_stats CASCADE;
DROP VIEW IF EXISTS cd.daily_facility_revenue CASCADE;
DROP VIEW IF EXISTS cd.member_network_stats CASCADE;
DROP VIEW IF EXISTS cd.facility_monthly_analysis CASCADE;

-- ============================================================
-- View 1: cd.daily_facility_revenue
-- For every (facility, date) pair from 2012-07-01 to 2013-01-31,
-- compute the total revenue. Days with no bookings should show
-- revenue = 0.
-- Columns: facility_name, facid, date, revenue
-- ============================================================
CREATE OR REPLACE VIEW cd.daily_facility_revenue AS
SELECT
    f.name AS facility_name,
    f.facid,
    CAST(b.starttime AS date) AS date,
    SUM(CASE
        WHEN b.memid = 0 THEN b.slots * f.guestcost
        ELSE b.slots * f.membercost
    END) AS revenue
FROM cd.facilities f
INNER JOIN cd.bookings b ON f.facid = b.facid
GROUP BY f.name, f.facid, CAST(b.starttime AS date)
ORDER BY f.name, date;


-- ============================================================
-- View 2: cd.revenue_rolling_stats
-- For each facility and date in Aug-Sep 2012, compute:
-- 15-day rolling average (current day + 14 preceding), rolling
-- population std dev, and z-score. The rolling window must use
-- July data for lookback.
-- Columns: facility_name, facid, date, revenue, rolling_avg,
--          rolling_stddev, zscore
-- ============================================================
CREATE OR REPLACE VIEW cd.revenue_rolling_stats AS
SELECT
    facility_name,
    facid,
    date,
    revenue,
    AVG(revenue) OVER (
        PARTITION BY facid
        ORDER BY date
        ROWS BETWEEN 15 PRECEDING AND CURRENT ROW
    ) AS rolling_avg,
    STDDEV(revenue) OVER (
        PARTITION BY facid
        ORDER BY date
        ROWS BETWEEN 15 PRECEDING AND CURRENT ROW
    ) AS rolling_stddev,
    (revenue - AVG(revenue) OVER (
        PARTITION BY facid
        ORDER BY date
        ROWS BETWEEN 15 PRECEDING AND CURRENT ROW
    )) / NULLIF(STDDEV(revenue) OVER (
        PARTITION BY facid
        ORDER BY date
        ROWS BETWEEN 15 PRECEDING AND CURRENT ROW
    ), 0) AS zscore
FROM cd.daily_facility_revenue
WHERE date >= '2012-08-01' AND date < '2012-10-01'
ORDER BY facility_name, date;


-- ============================================================
-- View 3: cd.member_network_stats
-- For each member, compute their recommendation network stats.
-- Uses recursive CTE to traverse the recommendation tree
-- DOWNWARD (finding who each member recommended, transitively).
-- Columns: memid, firstname, surname, direct_referrals,
--          total_network_size, max_depth, network_revenue
-- network_revenue = total revenue generated by all descendants
-- ============================================================
CREATE OR REPLACE VIEW cd.member_network_stats AS
WITH RECURSIVE network AS (
    -- Base case: start with each member
    SELECT
        m.memid AS root_member,
        m.memid AS current_member,
        0 AS depth
    FROM cd.members m

    UNION ALL

    -- Traverse the recommendation chain
    SELECT
        n.root_member,
        m.recommendedby,
        n.depth + 1
    FROM network n
    INNER JOIN cd.members m ON m.memid = n.current_member
    WHERE m.recommendedby IS NOT NULL
)
SELECT
    m.memid,
    m.firstname,
    m.surname,
    COUNT(DISTINCT n.current_member) AS direct_referrals,
    COUNT(DISTINCT n.current_member) AS total_network_size,
    COALESCE(MAX(n.depth), 0) AS max_depth,
    0::numeric AS network_revenue
FROM cd.members m
LEFT JOIN network n ON n.root_member = m.memid AND n.current_member != m.memid
GROUP BY m.memid, m.firstname, m.surname
ORDER BY m.memid;


-- ============================================================
-- View 4: cd.facility_monthly_analysis
-- Monthly revenue, utilization, rankings, and growth per facility.
-- utilization = (slots_used / total_available_slots) * 100
-- Available = 25 half-hour slots per day * days in month
-- Columns: facility_name, month, total_revenue, utilization_pct,
--          revenue_rank, prev_month_revenue, growth_pct, category
-- category: NTILE(3) by revenue within each month ->
--           'high'/'medium'/'low'
-- ============================================================
CREATE OR REPLACE VIEW cd.facility_monthly_analysis AS
SELECT
    f.name AS facility_name,
    DATE_TRUNC('month', b.starttime) AS month,
    SUM(CASE
        WHEN b.memid = 0 THEN b.slots * f.guestcost
        ELSE b.slots * f.membercost
    END) AS total_revenue,
    ROUND(100.0 * SUM(b.slots) / (30 * 25), 1) AS utilization_pct,
    RANK() OVER (
        PARTITION BY DATE_TRUNC('month', b.starttime)
        ORDER BY SUM(CASE
            WHEN b.memid = 0 THEN b.slots * f.guestcost
            ELSE b.slots * f.membercost
        END) DESC
    ) AS revenue_rank,
    NULL::numeric AS prev_month_revenue,
    NULL::numeric AS growth_pct,
    'medium' AS category
FROM cd.facilities f
INNER JOIN cd.bookings b ON f.facid = b.facid
GROUP BY f.name, f.facid, DATE_TRUNC('month', b.starttime)
ORDER BY facility_name, month;


-- ============================================================
-- View 5: cd.booking_anomaly_report
-- Identifies anomalous revenue days from revenue_rolling_stats
-- where |zscore| > 1.5 and determines the dominant booker.
-- Depends on cd.revenue_rolling_stats being correct.
-- Columns: facility_name, facid, date, revenue, zscore,
--          anomaly_type, dominant_booker, dominant_pct
-- ============================================================
CREATE OR REPLACE VIEW cd.booking_anomaly_report AS
SELECT
    r.facility_name,
    r.facid,
    r.date,
    r.revenue,
    r.zscore,
    'anomaly' AS anomaly_type,
    'Unknown' AS dominant_booker,
    0::numeric AS dominant_pct
FROM cd.revenue_rolling_stats r
WHERE r.zscore > 1.5;


-- ============================================================
-- Function: cd.member_value_score(p_memid INT)
-- Computes a composite value score for a member.
-- Depends on cd.member_network_stats being correct.
-- Formula: ROUND((direct_revenue + 0.5 * network_revenue)
--          / GREATEST(tenure_months, 1), 2)
-- tenure_months = complete months from joindate to 2013-02-01
-- ============================================================
CREATE OR REPLACE FUNCTION cd.member_value_score(p_memid INT)
RETURNS NUMERIC AS $$
DECLARE
    v_direct_revenue NUMERIC;
    v_network_revenue NUMERIC;
    v_tenure_months INT;
BEGIN
    SELECT COALESCE(SUM(b.slots * f.guestcost), 0)
    INTO v_direct_revenue
    FROM cd.bookings b
    JOIN cd.facilities f ON f.facid = b.facid
    WHERE b.memid = p_memid;

    SELECT COALESCE(network_revenue, 0)
    INTO v_network_revenue
    FROM cd.member_network_stats
    WHERE memid = p_memid;

    SELECT EXTRACT(YEAR FROM AGE(CURRENT_DATE, joindate)) * 12 +
           EXTRACT(MONTH FROM AGE(CURRENT_DATE, joindate))
    INTO v_tenure_months
    FROM cd.members
    WHERE memid = p_memid;

    RETURN ROUND((v_direct_revenue + v_network_revenue) / v_tenure_months, 2);
END;
$$ LANGUAGE plpgsql;
