
import sys
sys.path.insert(0, '/app')

import pytest
import subprocess
import json
import tempfile
import os


def oracle_apply(text_name, *files):
    """Run the Yjs oracle to apply binary updates and return the text."""
    result = subprocess.run(
        ['node', '/app/yjs_oracle.js', 'apply', text_name] + list(files),
        capture_output=True, text=True, timeout=30
    )
    if result.returncode != 0:
        raise RuntimeError(f"Oracle failed: {result.stderr}")
    return json.loads(result.stdout)['text']


def write_tmp_bin(data):
    """Write binary data to a temp file, return its path."""
    fd, path = tempfile.mkstemp(suffix='.bin', dir='/tmp')
    os.write(fd, data)
    os.close(fd)
    return path


def load_manifest():
    with open('/app/fixtures/manifest.json') as f:
        return json.load(f)


from yjs_compat import YDoc


# ---------------------------------------------------------------------------
# Decode binary fixtures generated by Yjs
# ---------------------------------------------------------------------------

class TestDecodeFixtures:
    def test_basic_hello(self):
        doc = YDoc(999)
        with open('/app/fixtures/basic_hello.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        assert str(doc.get_text('t')) == 'hello'

    def test_hello_world(self):
        doc = YDoc(999)
        with open('/app/fixtures/hello_world.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        assert str(doc.get_text('t')) == 'hello world'

    def test_with_deletes(self):
        doc = YDoc(999)
        with open('/app/fixtures/with_delete.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        assert str(doc.get_text('t')) == 'ho world'

    def test_insert_middle(self):
        doc = YDoc(999)
        with open('/app/fixtures/insert_middle.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        assert str(doc.get_text('t')) == 'abc'

    def test_multi_type(self):
        doc = YDoc(999)
        with open('/app/fixtures/multi_type.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        assert str(doc.get_text('title')) == 'Hello'
        assert str(doc.get_text('body')) == 'World'

    def test_complex_edit(self):
        doc = YDoc(999)
        with open('/app/fixtures/complex_edit.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        assert str(doc.get_text('t')) == 'abXYfgh'

    def test_state_vector_from_fixture(self):
        doc = YDoc(999)
        with open('/app/fixtures/basic_hello.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        sv = doc.get_state_vector()
        assert sv.get(100) == 5


# ---------------------------------------------------------------------------
# Encode binary updates, validate with real Yjs via Node.js oracle
# ---------------------------------------------------------------------------

class TestEncodeForYjs:
    def test_encode_simple(self):
        doc = YDoc(500)
        doc.get_text('t').insert(0, 'hello')
        data = doc.encode_state_as_update_v1()
        tmp = write_tmp_bin(data)
        try:
            yjs_text = oracle_apply('t', tmp)
            assert yjs_text == 'hello'
        finally:
            os.unlink(tmp)

    def test_encode_sequential_inserts(self):
        doc = YDoc(500)
        doc.get_text('t').insert(0, 'hello')
        doc.get_text('t').insert(5, ' world')
        data = doc.encode_state_as_update_v1()
        tmp = write_tmp_bin(data)
        try:
            yjs_text = oracle_apply('t', tmp)
            assert yjs_text == 'hello world'
        finally:
            os.unlink(tmp)

    def test_encode_with_delete(self):
        doc = YDoc(500)
        doc.get_text('t').insert(0, 'hello world')
        doc.get_text('t').delete(5, 6)
        data = doc.encode_state_as_update_v1()
        tmp = write_tmp_bin(data)
        try:
            yjs_text = oracle_apply('t', tmp)
            assert yjs_text == 'hello'
        finally:
            os.unlink(tmp)

    def test_encode_insert_in_middle(self):
        doc = YDoc(500)
        doc.get_text('t').insert(0, 'ac')
        doc.get_text('t').insert(1, 'b')
        data = doc.encode_state_as_update_v1()
        tmp = write_tmp_bin(data)
        try:
            yjs_text = oracle_apply('t', tmp)
            assert yjs_text == 'abc'
        finally:
            os.unlink(tmp)


# ---------------------------------------------------------------------------
# Cross-language convergence — concurrent edits match Yjs ordering
# ---------------------------------------------------------------------------

class TestCrossLanguageConvergence:
    def test_two_client_same_position(self):
        manifest = load_manifest()
        doc = YDoc(999)
        with open('/app/fixtures/client_a.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        with open('/app/fixtures/client_b.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        py_text = str(doc.get_text('t'))
        yjs_text = oracle_apply('t', '/app/fixtures/client_a.bin',
                                '/app/fixtures/client_b.bin')
        assert py_text == yjs_text
        assert py_text == manifest['concurrent_two']['expected_text']

    def test_three_client_same_position(self):
        manifest = load_manifest()
        doc = YDoc(999)
        for i in range(3):
            with open(f'/app/fixtures/three_{i}.bin', 'rb') as f:
                doc.apply_update_v1(f.read())
        py_text = str(doc.get_text('t'))
        yjs_text = oracle_apply('t', '/app/fixtures/three_0.bin',
                                '/app/fixtures/three_1.bin',
                                '/app/fixtures/three_2.bin')
        assert py_text == yjs_text
        assert py_text == manifest['concurrent_three']['expected_text']

    def test_commutativity_two_clients(self):
        """Applying updates in reverse order produces the same result."""
        doc1 = YDoc(999)
        with open('/app/fixtures/client_a.bin', 'rb') as f:
            data_a = f.read()
        with open('/app/fixtures/client_b.bin', 'rb') as f:
            data_b = f.read()

        doc1.apply_update_v1(data_a)
        doc1.apply_update_v1(data_b)

        doc2 = YDoc(998)
        doc2.apply_update_v1(data_b)
        doc2.apply_update_v1(data_a)

        assert str(doc1.get_text('t')) == str(doc2.get_text('t'))

    def test_five_client_convergence(self):
        manifest = load_manifest()
        doc = YDoc(999)
        with open('/app/fixtures/five_base.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        for i in range(5):
            with open(f'/app/fixtures/five_{i}.bin', 'rb') as f:
                doc.apply_update_v1(f.read())
        py_text = str(doc.get_text('t'))

        files = ['/app/fixtures/five_base.bin'] + \
                [f'/app/fixtures/five_{i}.bin' for i in range(5)]
        yjs_text = oracle_apply('t', *files)

        assert py_text == yjs_text
        assert py_text == manifest['five_concurrent']['expected_text']

    def test_concurrent_delete_and_insert(self):
        manifest = load_manifest()
        doc = YDoc(999)
        with open('/app/fixtures/del_ins_base.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        with open('/app/fixtures/del_ins_1.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        with open('/app/fixtures/del_ins_2.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        py_text = str(doc.get_text('t'))

        yjs_text = oracle_apply('t', '/app/fixtures/del_ins_base.bin',
                                '/app/fixtures/del_ins_1.bin',
                                '/app/fixtures/del_ins_2.bin')

        assert py_text == yjs_text
        assert py_text == manifest['concurrent_del_ins']['expected_text']


# ---------------------------------------------------------------------------
# Round-trip: JS → binary → Python → binary → JS
# ---------------------------------------------------------------------------

class TestRoundTrip:
    def test_roundtrip_simple(self):
        """Decode Yjs binary, re-encode, feed back to Yjs."""
        doc = YDoc(999)
        with open('/app/fixtures/hello_world.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        assert str(doc.get_text('t')) == 'hello world'

        re_encoded = doc.encode_state_as_update_v1()
        tmp = write_tmp_bin(re_encoded)
        try:
            yjs_text = oracle_apply('t', tmp)
            assert yjs_text == 'hello world'
        finally:
            os.unlink(tmp)

    def test_roundtrip_complex(self):
        """Complex editing survives round-trip."""
        doc = YDoc(999)
        with open('/app/fixtures/complex_edit.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        assert str(doc.get_text('t')) == 'abXYfgh'

        re_encoded = doc.encode_state_as_update_v1()
        tmp = write_tmp_bin(re_encoded)
        try:
            yjs_text = oracle_apply('t', tmp)
            assert yjs_text == 'abXYfgh'
        finally:
            os.unlink(tmp)

    def test_roundtrip_concurrent(self):
        """Concurrent edits survive round-trip after merge."""
        doc = YDoc(999)
        with open('/app/fixtures/client_a.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        with open('/app/fixtures/client_b.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        py_text = str(doc.get_text('t'))

        re_encoded = doc.encode_state_as_update_v1()
        tmp = write_tmp_bin(re_encoded)
        try:
            yjs_text = oracle_apply('t', tmp)
            assert yjs_text == py_text
        finally:
            os.unlink(tmp)


# ---------------------------------------------------------------------------
# Diff-based sync across the language boundary
# ---------------------------------------------------------------------------

class TestDiffSync:
    def test_diff_sync_python_to_yjs(self):
        """Python creates a diff update, Yjs applies it correctly."""
        doc = YDoc(600)
        doc.get_text('t').insert(0, 'hello')
        base_sv = doc.get_state_vector()

        doc.get_text('t').insert(5, ' world')
        diff = doc.encode_state_as_update_v1(target_sv=base_sv)

        full = doc.encode_state_as_update_v1()
        tmp_full = write_tmp_bin(full)
        tmp_diff = write_tmp_bin(diff)
        try:
            yjs_full = oracle_apply('t', tmp_full)
            assert yjs_full == 'hello world'
        finally:
            os.unlink(tmp_full)
            os.unlink(tmp_diff)

    def test_bidirectional_divergent_sync(self):
        """Base + two divergent diffs converge."""
        manifest = load_manifest()
        doc = YDoc(999)
        with open('/app/fixtures/shared_base.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        with open('/app/fixtures/diverge_a.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        with open('/app/fixtures/diverge_b.bin', 'rb') as f:
            doc.apply_update_v1(f.read())
        py_text = str(doc.get_text('t'))

        yjs_text = oracle_apply('t', '/app/fixtures/shared_base.bin',
                                '/app/fixtures/diverge_a.bin',
                                '/app/fixtures/diverge_b.bin')

        assert py_text == yjs_text
        assert py_text == manifest['divergent_sync']['expected_text']


# ---------------------------------------------------------------------------
# Snapshots
# ---------------------------------------------------------------------------

class TestSnapshots:
    def test_basic_snapshot(self):
        doc = YDoc(700)
        doc.get_text('t').insert(0, 'hello')
        snap = doc.snapshot()
        doc.get_text('t').insert(5, ' world')
        assert str(doc.get_text('t')) == 'hello world'
        assert doc.text_at_snapshot('t', snap) == 'hello'

    def test_snapshot_with_deletes(self):
        doc = YDoc(700)
        doc.get_text('t').insert(0, 'hello world')
        snap1 = doc.snapshot()
        doc.get_text('t').delete(5, 6)
        snap2 = doc.snapshot()
        doc.get_text('t').insert(5, '!')
        assert str(doc.get_text('t')) == 'hello!'
        assert doc.text_at_snapshot('t', snap1) == 'hello world'
        assert doc.text_at_snapshot('t', snap2) == 'hello'

    def test_snapshot_after_remote_sync(self):
        doc1 = YDoc(701)
        doc1.get_text('t').insert(0, 'ab')

        doc2 = YDoc(702)
        doc2.apply_update_v1(doc1.encode_state_as_update_v1())
        doc2.get_text('t').insert(2, 'cd')

        snap = doc2.snapshot()
        doc2.get_text('t').insert(4, 'ef')

        assert str(doc2.get_text('t')) == 'abcdef'
        assert doc2.text_at_snapshot('t', snap) == 'abcd'
