#!/usr/bin/env python3
"""Generate synthetic climate model output files with realistic data quality issues.

Simulates MATLAB-exported climate model data containing:
1. NaN values for missing data, but _FillValue set to default (9.96921e+36)
   This mismatch causes NCO averaging tools to produce incorrect results.
2. Non-standard dimension names (latitude/longitude instead of lat/lon)
3. A fully corrupt time record (August 2011) with all-NaN data
4. Temperature in Celsius with non-CF unit string
"""
import numpy as np
import os
from netCDF4 import Dataset

output_dir = "/app/data"
os.makedirs(output_dir, exist_ok=True)

# Grid: 36 lat x 72 lon (5-degree resolution)
nlat, nlon = 36, 72
lats = np.linspace(-87.5, 87.5, nlat)
lons = np.linspace(2.5, 357.5, nlon)
lat_rad = np.deg2rad(lats)

# Deterministic ocean mask (~30% of grid cells are ocean/masked)
np.random.seed(12345)
ocean_mask = np.random.random((nlat, nlon)) < 0.30

# Per-year temperature offsets for inter-annual variability
# Using asymmetric offsets so excluding corrupt year 2011 changes the average
year_offsets = {2010: 0.0, 2011: 1.0, 2012: 0.5}

# Approximate mid-month day-of-year values
mid_month_days = [15, 46, 74, 105, 135, 166, 196, 227, 258, 288, 319, 349]

for year in [2010, 2011, 2012]:
    filepath = os.path.join(output_dir, "climate_{}.nc".format(year))
    ds = Dataset(filepath, 'w', format='NETCDF4')
    ds.set_auto_maskandscale(False)

    # Dimensions with non-standard names
    ds.createDimension('time', None)
    ds.createDimension('latitude', nlat)
    ds.createDimension('longitude', nlon)

    # Time coordinate (common epoch across all files)
    tv = ds.createVariable('time', 'f8', ('time',))
    tv.units = "days since 2010-01-01 00:00:00"
    tv.calendar = "standard"
    tv.axis = "T"

    latv = ds.createVariable('latitude', 'f8', ('latitude',))
    latv.units = "degrees_north"
    latv[:] = lats

    lonv = ds.createVariable('longitude', 'f8', ('longitude',))
    lonv.units = "degrees_east"
    lonv[:] = lons

    # Data variables: default _FillValue = 9.96921e+36 for float32
    # But data will use NaN for missing — this mismatch is the core problem
    tas = ds.createVariable('tas', 'f4', ('time', 'latitude', 'longitude'))
    tas.units = "celsius"
    tas.long_name = "Near-Surface Air Temperature"

    uas = ds.createVariable('uas', 'f4', ('time', 'latitude', 'longitude'))
    uas.units = "m s-1"
    uas.long_name = "Eastward Near-Surface Wind"

    vas = ds.createVariable('vas', 'f4', ('time', 'latitude', 'longitude'))
    vas.units = "m s-1"
    vas.long_name = "Northward Near-Surface Wind"

    offset = year_offsets[year]
    year_day_offset = (year - 2010) * 365

    for m in range(12):
        cos_lat = np.cos(lat_rad)[:, np.newaxis] * np.ones((1, nlon))
        sin_2lat = np.sin(2 * lat_rad)[:, np.newaxis] * np.ones((1, nlon))

        # Temperature: warm equator, cold poles, seasonal cycle, inter-annual offset
        tas_data = (15.0 + 20.0 * cos_lat
                    + 5.0 * np.cos(2.0 * np.pi * m / 12.0)
                    + offset).astype(np.float32)

        # Wind components
        uas_data = (5.0 * cos_lat
                    + np.sin(2.0 * np.pi * m / 12.0)).astype(np.float32)
        vas_data = (2.0 * sin_2lat).astype(np.float32)

        # Ocean mask: set to NaN (mimics MATLAB missing-data convention)
        tas_data[ocean_mask] = np.float32('nan')
        uas_data[ocean_mask] = np.float32('nan')
        vas_data[ocean_mask] = np.float32('nan')

        # Corrupt record: year 2011, August (month index 7) — all data NaN
        if year == 2011 and m == 7:
            tas_data[:, :] = np.float32('nan')
            uas_data[:, :] = np.float32('nan')
            vas_data[:, :] = np.float32('nan')

        tv[m] = float(year_day_offset + mid_month_days[m])
        tas[m, :, :] = tas_data
        uas[m, :, :] = uas_data
        vas[m, :, :] = vas_data

    ds.Conventions = "CF-1.6"
    ds.source = "Synthetic Climate Model v1.0 (MATLAB export)"
    ds.institution = "Test University"
    ds.history = "Generated by MATLAB R2024a export routine"

    ds.close()
    print("Created {}".format(filepath))

print("Data generation complete: {} files in {}".format(len(year_offsets), output_dir))
