#!/usr/bin/env python3

"""
Automated PRNG family classifier.

Identifies whether a binary stream of uint32 values was generated by:
  - xorshift128: outputs the 4-word state directly; detectable via 4-output recurrence
  - lcg64: truncated 64-bit LCG with Knuth constants; detectable via brute-force state recovery
  - mt19937: Mersenne Twister variant; identified by elimination

Usage: python3 classifier.py <stream_file.bin>
Prints exactly one of: xorshift128, lcg64, mt19937
"""

import os
import struct
import subprocess
import sys
import tempfile

MASK32 = 0xFFFFFFFF


def read_stream(path):
    with open(path, "rb") as f:
        data = f.read()
    n = len(data) // 4
    return list(struct.unpack(f"<{n}I", data))


def check_xorshift128(vals):
    """Test if output follows the xorshift128 4-output recurrence.
    In xorshift128, the state IS the last 4 outputs, so output[n+4]
    is deterministically computed from output[n:n+4]."""
    if len(vals) < 10:
        return False
    for start in range(min(50, len(vals) - 5)):
        a = vals[start + 3]
        b = vals[start + 2]
        c = vals[start + 1]
        d = vals[start]
        t = d
        s = a
        t = (t ^ ((t << 11) & MASK32)) & MASK32
        t = (t ^ (t >> 8)) & MASK32
        s = (s ^ (s >> 19)) & MASK32
        predicted = (t ^ s) & MASK32
        if predicted != vals[start + 4]:
            return False
    return True


_LCG_CRACK_PATH = "/tmp/lcg_crack_classifier"

_LCG_CRACK_SRC = r"""
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
int main(int argc, char **argv) {
    uint64_t mult = 6364136223846793005ULL;
    uint64_t inc = 1442695040888963407ULL;
    uint32_t o0 = (uint32_t)strtoul(argv[1], NULL, 16);
    uint32_t o1 = (uint32_t)strtoul(argv[2], NULL, 16);
    for (uint64_t lo = 0; lo < (1ULL << 32); lo++) {
        uint64_t s1 = ((uint64_t)o0 << 32) | lo;
        uint64_t s2 = s1 * mult + inc;
        if ((uint32_t)(s2 >> 32) == o1) {
            printf("0x%016llx\n", (unsigned long long)s1);
            return 0;
        }
    }
    return 1;
}
"""


def _ensure_lcg_crack():
    if os.path.exists(_LCG_CRACK_PATH):
        return True
    fd, src_path = tempfile.mkstemp(suffix=".c")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(_LCG_CRACK_SRC)
        ret = os.system(f"gcc -O2 -o {_LCG_CRACK_PATH} {src_path}")
        return ret == 0
    finally:
        if os.path.exists(src_path):
            os.unlink(src_path)


def check_lcg64(vals):
    """Test if output could be from the known truncated 64-bit LCG.
    Brute-forces 2^32 possible lower bits of state using compiled C helper,
    then verifies with a third output."""
    if len(vals) < 3:
        return False
    if not _ensure_lcg_crack():
        return False

    LCG_MULT = 6364136223846793005
    LCG_INC = 1442695040888963407
    MASK64 = (1 << 64) - 1

    o0, o1, o2 = vals[0], vals[1], vals[2]
    try:
        result = subprocess.run(
            [_LCG_CRACK_PATH, f"{o0:08x}", f"{o1:08x}"],
            capture_output=True, text=True, timeout=120,
        )
        if result.returncode != 0:
            return False
        state_1 = int(result.stdout.strip(), 16)
        # Verify with third output
        state_2 = (state_1 * LCG_MULT + LCG_INC) & MASK64
        if ((state_2 >> 32) & MASK32) != o1:
            return False
        state_3 = (state_2 * LCG_MULT + LCG_INC) & MASK64
        return ((state_3 >> 32) & MASK32) == o2
    except Exception:
        return False


def main():
    if len(sys.argv) < 2:
        print("Usage: classifier.py <stream_file.bin>", file=sys.stderr)
        sys.exit(1)

    vals = read_stream(sys.argv[1])

    if check_xorshift128(vals):
        print("xorshift128")
    elif check_lcg64(vals):
        print("lcg64")
    else:
        print("mt19937")


if __name__ == "__main__":
    main()
