#!/usr/bin/env python3
"""Code generator for parser rules - generates compile-time constants."""
import argparse
import json
import sys
import os


def generate_rules(config_path, output_path):
    with open(config_path) as f:
        config = json.load(f)

    content = (
        "// Auto-generated by codegen.py - do not edit\n"
        "#pragma once\n"
        f"#define GENERATED_SCALE_FACTOR {config['scale_factor']}\n"
        f"#define GENERATED_VERSION \"{config['version']}\"\n"
        f"#define GENERATED_MAX_STAGES {config['max_stages']}\n"
    )

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(content)


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description='Generate parser rule headers')
    ap.add_argument('--config', required=True, help='Path to config JSON')
    ap.add_argument('--output', required=True, help='Output header path')
    args = ap.parse_args()
    generate_rules(args.config, args.output)
