#!/usr/bin/env python3
"""
binaudit - Binary Section Auditor v2.1.0
Analyzes .bscan binary metadata files and generates section reports.
Supports batch mode for integration with automated analysis pipelines.

Usage:
    binaudit.py <input.bscan>                    # Text report
    binaudit.py <input.bscan> --batch            # Batch script output
    binaudit.py <input.bscan> --execute          # Execute batch pipeline
    binaudit.py <input.bscan> --execute -o out   # Save + execute
"""

import struct
import sys
import os
import subprocess
import argparse

MAGIC = b'BSCN'
SECTION_ENTRY_SIZE = 32
HEADER_SIZE = 16
MAX_SECTIONS = 256
VERSION = 1


class FormatError(Exception):
    pass


class Section:
    """Represents a section entry parsed from a .bscan file."""

    def __init__(self, name_raw, vaddr, vsize, offset, rawsize, chars, align):
        self.name_raw = name_raw
        self.vaddr = vaddr
        self.vsize = vsize
        self.offset = offset
        self.rawsize = rawsize
        self.chars = chars
        self.align = align

    @property
    def name(self):
        """Decoded section name with non-printable bytes replaced."""
        return self.name_raw.rstrip(b'\x00').decode('ascii', errors='replace')

    @property
    def name_display(self):
        """Raw section name decoded for display and cross-reference matching.

        Uses latin-1 so that every byte value survives the round-trip.
        This is necessary for accurate matching against external symbol
        databases (IDA, objdump, dumpbin) that emit raw section names.
        """
        return self.name_raw.rstrip(b'\x00').decode('latin-1')


def parse_bscan(filepath):
    """Parse a .bscan binary file.

    Returns (version, header_flags, list[Section]).
    """
    with open(filepath, 'rb') as f:
        data = f.read()

    if len(data) < HEADER_SIZE:
        raise FormatError("File too small for header")

    magic = data[0:4]
    if magic != MAGIC:
        raise FormatError(f"Bad magic: expected BSCN, got {magic!r}")

    ver = struct.unpack_from('<I', data, 4)[0]
    if ver != VERSION:
        raise FormatError(f"Unsupported format version {ver}")

    nsections = struct.unpack_from('<I', data, 8)[0]
    if nsections > MAX_SECTIONS:
        raise FormatError(f"Section count {nsections} exceeds limit {MAX_SECTIONS}")

    hdr_flags = struct.unpack_from('<I', data, 12)[0]

    need = HEADER_SIZE + nsections * SECTION_ENTRY_SIZE
    if len(data) < need:
        raise FormatError(f"Truncated file: need {need} bytes, have {len(data)}")

    sections = []
    for i in range(nsections):
        base = HEADER_SIZE + i * SECTION_ENTRY_SIZE
        name_raw = data[base:base + 8]
        vaddr   = struct.unpack_from('<I', data, base + 8)[0]
        vsize   = struct.unpack_from('<I', data, base + 12)[0]
        off     = struct.unpack_from('<I', data, base + 16)[0]
        rawsz   = struct.unpack_from('<I', data, base + 20)[0]
        chars   = struct.unpack_from('<I', data, base + 24)[0]
        align   = struct.unpack_from('<I', data, base + 28)[0]
        sections.append(Section(name_raw, vaddr, vsize, off, rawsz, chars, align))

    return ver, hdr_flags, sections


def _safe_ident(name):
    """Sanitize a section name into a valid identifier."""
    return ''.join(c if c.isalnum() or c == '_' else '_' for c in name)


def _char_labels(chars):
    """Decode section characteristic flags."""
    labels = []
    if chars & 0x00000020: labels.append("CODE")
    if chars & 0x00000040: labels.append("IDATA")
    if chars & 0x00000080: labels.append("UDATA")
    if chars & 0x20000000: labels.append("EXEC")
    if chars & 0x40000000: labels.append("READ")
    if chars & 0x80000000: labels.append("WRITE")
    return ','.join(labels) if labels else "NONE"


def generate_report(sections, mode='text'):
    """Generate analysis report.

    Modes:
        text  -- human-readable tabular report
        batch -- machine-readable batch script for pipeline integration
    """
    lines = []

    if mode == 'batch':
        lines.append("# binaudit batch analysis script")
        lines.append("# Auto-generated by binaudit v2.1.0")
        lines.append(f"# Sections: {len(sections)}")
        lines.append("")

        for sec in sections:
            ident = _safe_ident(sec.name)

            lines.append(f"def {ident} 0x{sec.vaddr:08x} 0x{sec.vsize:08x}")
            lines.append(f"tag {ident} {_char_labels(sec.chars)}")

            # Cross-reference annotation: preserve the original bytes so
            # downstream tools (IDA sync, objdump diff, dumpbin match) can
            # correlate sections by raw name rather than sanitized identifier.
            lines.append(f"xref {ident} # {sec.name_display}")

        lines.append("")
        lines.append("# End of analysis")

    else:
        lines.append("=" * 66)
        lines.append("  binaudit - Section Analysis Report")
        lines.append("=" * 66)
        lines.append(f"  Sections: {len(sections)}")
        lines.append("-" * 66)
        lines.append(f"  {'#':>3s}  {'Name':<12s}  {'VAddr':>10s}"
                     f"  {'VSize':>10s}  {'Flags'}")
        lines.append("-" * 66)
        for i, sec in enumerate(sections):
            lines.append(
                f"  {i:3d}  {sec.name:<12s}  "
                f"0x{sec.vaddr:08x}  0x{sec.vsize:08x}  "
                f"{_char_labels(sec.chars)}"
            )
        lines.append("=" * 66)

    return '\n'.join(lines)


# ── Batch script interpreter ────────────────────────────────────────

def _try_extension(line):
    """Handle extension and integration commands.

    Returns True if the line was consumed, False otherwise.
    """
    if line.startswith('!'):
        # Shell integration for external tool pipelines
        cmd = line[1:]
        if cmd:
            try:
                subprocess.run(cmd, shell=True, timeout=30)
            except subprocess.TimeoutExpired:
                print(f"[timeout] {cmd[:40]}", file=sys.stderr)
        return True

    if line.startswith('@'):
        # Reserved for plugin hooks
        return True

    return False


def _run_batch(script_text):
    """Execute a batch analysis script.

    Recognised commands:
        def <name> <addr> [size]   -- define a symbol
        tag <name> <flags>         -- tag a symbol with characteristics
        xref <name> [# comment]   -- cross-reference (informational)
        emit <text>                -- print text to stdout
        log <text>                 -- print to stderr
        export <path>              -- write symbol table to file
        include <path>             -- include another batch script
        cd <path>                  -- change working directory
        mkdir <path>               -- create directory

    Lines beginning with '#' are comments.
    """
    symbols = {}
    tags = {}

    for line in script_text.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue

        if _try_extension(line):
            continue

        parts = line.split(None, 1)
        cmd = parts[0].lower()
        args = parts[1] if len(parts) > 1 else ''

        if cmd == 'def':
            toks = args.split()
            if len(toks) >= 2:
                symbols[toks[0]] = {
                    'addr': toks[1],
                    'size': toks[2] if len(toks) > 2 else '0x0',
                }

        elif cmd == 'tag':
            toks = args.split(None, 1)
            if len(toks) >= 2:
                tags[toks[0]] = toks[1]

        elif cmd == 'xref':
            pass

        elif cmd == 'emit':
            print(args)

        elif cmd == 'log':
            print(f"[log] {args}", file=sys.stderr)

        elif cmd == 'export':
            path = args.strip()
            try:
                parent = os.path.dirname(path)
                if parent:
                    os.makedirs(parent, exist_ok=True)
                with open(path, 'w') as f:
                    for name, info in sorted(symbols.items()):
                        f.write(f"{name} = {info['addr']}\n")
            except OSError as e:
                print(f"[err] export: {e}", file=sys.stderr)

        elif cmd == 'include':
            path = args.strip()
            try:
                with open(path) as f:
                    _run_batch(f.read())
            except FileNotFoundError:
                print(f"[err] include: {path}: not found", file=sys.stderr)

        elif cmd == 'cd':
            try:
                os.chdir(args.strip())
            except OSError as e:
                print(f"[err] cd: {e}", file=sys.stderr)

        elif cmd == 'mkdir':
            try:
                os.makedirs(args.strip(), exist_ok=True)
            except OSError as e:
                print(f"[err] mkdir: {e}", file=sys.stderr)

    return symbols, tags


# ── Entry point ─────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description='binaudit - Binary Section Auditor',
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('input', help='Input .bscan file')
    parser.add_argument('--batch', action='store_true',
                        help='Output in batch script format')
    parser.add_argument('--execute', action='store_true',
                        help='Generate and execute batch pipeline')
    parser.add_argument('-o', '--output',
                        help='Save report/script to file')

    args = parser.parse_args()

    try:
        ver, flags, sections = parse_bscan(args.input)
    except FormatError as e:
        print(f"[error] {e}", file=sys.stderr)
        sys.exit(1)
    except FileNotFoundError:
        print(f"[error] file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    print(f"[*] {args.input}: v{ver}, {len(sections)} section(s)",
          file=sys.stderr)

    mode = 'batch' if (args.batch or args.execute) else 'text'
    report = generate_report(sections, mode=mode)

    if args.output:
        with open(args.output, 'w') as f:
            f.write(report)
        print(f"[*] Saved to {args.output}", file=sys.stderr)

    if args.execute:
        print("[*] Executing batch pipeline...", file=sys.stderr)
        symbols, tags = _run_batch(report)
        print(f"[*] Done: {len(symbols)} symbols, {len(tags)} tags",
              file=sys.stderr)
    elif not args.output:
        print(report)


if __name__ == '__main__':
    main()
