
"""
Tests for MPI derived datatype layout analyzer.

Verifies:
1. Makefile compiles MPI C code correctly
2. MPI runtime produces ground truth
3. Python results match expected values per MPI 5.0 section 4.1
4. Python results match MPI runtime ground truth
5. Independent type constructions prevent hardcoding
"""

import json
import os
import subprocess
import sys

import pytest

# Expected correct results for each type in type_defs.json
EXPECTED = {
    "particle_pos": {
        "typemap": [
            ("MPI_DOUBLE", 0), ("MPI_DOUBLE", 8), ("MPI_DOUBLE", 16), ("MPI_INT", 24),
        ],
        "lb": 0, "ub": 32, "extent": 32,
        "true_lb": 0, "true_ub": 28, "true_extent": 28,
        "size": 28,
    },
    "strided_doubles": {
        "typemap": [
            ("MPI_DOUBLE", 0), ("MPI_DOUBLE", 8),
            ("MPI_DOUBLE", 40), ("MPI_DOUBLE", 48),
            ("MPI_DOUBLE", 80), ("MPI_DOUBLE", 88),
            ("MPI_DOUBLE", 120), ("MPI_DOUBLE", 128),
        ],
        "lb": 0, "ub": 136, "extent": 136,
        "true_lb": 0, "true_ub": 136, "true_extent": 136,
        "size": 64,
    },
    "padded_particle": {
        "typemap": [
            ("MPI_DOUBLE", 0), ("MPI_DOUBLE", 8), ("MPI_DOUBLE", 16), ("MPI_INT", 24),
        ],
        "lb": 0, "ub": 64, "extent": 64,
        "true_lb": 0, "true_ub": 28, "true_extent": 28,
        "size": 28,
    },
    "particle_array": {
        "typemap": [
            ("MPI_DOUBLE", 0), ("MPI_DOUBLE", 8), ("MPI_DOUBLE", 16), ("MPI_INT", 24),
            ("MPI_DOUBLE", 64), ("MPI_DOUBLE", 72), ("MPI_DOUBLE", 80), ("MPI_INT", 88),
            ("MPI_DOUBLE", 128), ("MPI_DOUBLE", 136), ("MPI_DOUBLE", 144), ("MPI_INT", 152),
        ],
        "lb": 0, "ub": 192, "extent": 192,
        "true_lb": 0, "true_ub": 156, "true_extent": 156,
        "size": 84,
    },
    "column_slice": {
        "typemap": [
            ("MPI_DOUBLE", 88), ("MPI_DOUBLE", 96),
            ("MPI_DOUBLE", 152), ("MPI_DOUBLE", 160),
            ("MPI_DOUBLE", 216), ("MPI_DOUBLE", 224),
        ],
        "lb": 0, "ub": 384, "extent": 384,
        "true_lb": 88, "true_ub": 232, "true_extent": 144,
        "size": 48,
    },
    "scattered_ints": {
        "typemap": [
            ("MPI_INT", 0), ("MPI_INT", 4),
            ("MPI_INT", 20), ("MPI_INT", 24),
            ("MPI_INT", 52), ("MPI_INT", 56),
            ("MPI_INT", 100), ("MPI_INT", 104),
        ],
        "lb": 0, "ub": 108, "extent": 108,
        "true_lb": 0, "true_ub": 108, "true_extent": 108,
        "size": 32,
    },
    "mixed_struct": {
        "typemap": [
            ("MPI_CHAR", 0), ("MPI_DOUBLE", 4), ("MPI_DOUBLE", 12), ("MPI_SHORT", 20),
        ],
        "lb": 0, "ub": 24, "extent": 24,
        "true_lb": 0, "true_ub": 22, "true_extent": 22,
        "size": 19,
    },
    "nested_vector": {
        "typemap": [
            ("MPI_DOUBLE", 0), ("MPI_DOUBLE", 8), ("MPI_DOUBLE", 16), ("MPI_INT", 24),
            ("MPI_DOUBLE", 64), ("MPI_DOUBLE", 72), ("MPI_DOUBLE", 80), ("MPI_INT", 88),
            ("MPI_DOUBLE", 128), ("MPI_DOUBLE", 136), ("MPI_DOUBLE", 144), ("MPI_INT", 152),
        ],
        "lb": 0, "ub": 160, "extent": 160,
        "true_lb": 0, "true_ub": 156, "true_extent": 156,
        "size": 84,
    },
}


@pytest.fixture(scope="session")
def mpi_binary():
    """Clean and recompile the MPI validation program to verify Makefile."""
    subprocess.run(["make", "-C", "/app", "clean"], capture_output=True)
    result = subprocess.run(["make", "-C", "/app"], capture_output=True, text=True)
    assert result.returncode == 0, (
        f"Makefile compilation failed — must use the MPI compiler wrapper (mpicc):\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert os.path.isfile("/app/mpi_validate"), "mpi_validate binary not produced by make"
    return "/app/mpi_validate"


@pytest.fixture(scope="session")
def ground_truth(mpi_binary):
    """Run MPI validation program to obtain ground truth from MPI runtime."""
    gt_path = "/app/mpi_ground_truth.json"
    if os.path.exists(gt_path):
        os.remove(gt_path)
    result = subprocess.run(
        ["mpirun", "--allow-run-as-root", "-np", "1", mpi_binary],
        capture_output=True, text=True, cwd="/app",
    )
    assert result.returncode == 0, (
        f"mpirun failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert os.path.isfile(gt_path), "Ground truth JSON not generated by mpi_validate"
    with open(gt_path) as f:
        return json.load(f)


@pytest.fixture(scope="session")
def results():
    """Run the Python analysis and load results."""
    result = subprocess.run(
        ["python3", "/app/run_analysis.py"],
        capture_output=True, text=True, cwd="/app",
    )
    assert result.returncode == 0, (
        f"Python analysis failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
    )
    with open("/app/results.json") as f:
        return json.load(f)


def test_makefile_compiles(mpi_binary):
    """Makefile must successfully compile the MPI validation program."""
    assert os.path.isfile(mpi_binary)


def test_mpi_runtime_produces_ground_truth(ground_truth):
    """MPI validation program must produce ground truth for all 8 types."""
    assert len(ground_truth) == 8, (
        f"Expected 8 types in ground truth, got {len(ground_truth)}"
    )


@pytest.mark.parametrize("type_name", list(EXPECTED.keys()))
def test_type_properties(results, type_name):
    """Verify all computed properties for each defined type."""
    expected = EXPECTED[type_name]
    assert type_name in results, f"Type '{type_name}' missing from results"
    actual = results[type_name]

    # Compare typemaps (sorted by displacement then type name)
    expected_tm = sorted(expected["typemap"], key=lambda x: (x[1], x[0]))
    actual_tm = sorted([tuple(e) for e in actual["typemap"]], key=lambda x: (x[1], x[0]))
    assert actual_tm == expected_tm, (
        f"Typemap mismatch for {type_name}:\n"
        f"  expected: {expected_tm}\n"
        f"  got:      {actual_tm}"
    )

    # Compare scalar properties
    for prop in ["lb", "ub", "extent", "true_lb", "true_ub", "true_extent", "size"]:
        assert actual[prop] == expected[prop], (
            f"{prop} mismatch for {type_name}: got {actual[prop]}, expected {expected[prop]}"
        )


@pytest.mark.parametrize("type_name", list(EXPECTED.keys()))
def test_python_matches_mpi_runtime(results, ground_truth, type_name):
    """Python results must agree with MPI runtime ground truth."""
    assert type_name in ground_truth, (
        f"Type '{type_name}' missing from MPI runtime ground truth"
    )
    gt = ground_truth[type_name]
    py = results[type_name]
    for prop in ["lb", "ub", "extent", "true_lb", "true_ub", "true_extent", "size"]:
        assert py[prop] == gt[prop], (
            f"{type_name}.{prop}: Python={py[prop]} vs MPI runtime={gt[prop]}"
        )


def test_independent_struct():
    """Test extent alignment with an independent struct (not from type_defs.json)."""
    sys.path.insert(0, "/app")
    from mpi_types import type_create_struct

    # struct: [1 MPI_DOUBLE at 0, 1 MPI_INT at 8]
    # raw_ub = 12, max_align = 8, extent should be ceil(12/8)*8 = 16
    dt = type_create_struct([1, 1], [0, 8], ["MPI_DOUBLE", "MPI_INT"], "test_struct")
    assert dt.extent == 16, f"extent should be 16 (ceil-aligned), got {dt.extent}"
    assert dt.size == 12
    assert dt.true_extent == 12


def test_independent_vector():
    """Test vector stride parameter with an independent vector."""
    sys.path.insert(0, "/app")
    from mpi_types import MPIType, type_vector

    int_type = MPIType([("MPI_INT", 0)], "MPI_INT")

    # vector(3, 1, 3, MPI_INT): 3 blocks of 1 int, stride 3 elements
    # block 0 at 0, block 1 at 12, block 2 at 24
    dt = type_vector(3, 1, 3, int_type, "test_vec")
    tm = dt.get_data_typemap()
    assert len(tm) == 3
    assert tm[0] == ("MPI_INT", 0)
    assert tm[1] == ("MPI_INT", 12), f"block 1 should be at 12 (stride*extent), got {tm[1][1]}"
    assert tm[2] == ("MPI_INT", 24)
    assert dt.extent == 28


def test_independent_resized_contiguous():
    """Test that resized type bounds propagate through contiguous constructor."""
    sys.path.insert(0, "/app")
    from mpi_types import MPIType, type_contiguous, type_create_resized

    int_type = MPIType([("MPI_INT", 0)], "MPI_INT")

    # Resize MPI_INT to extent 8
    resized = type_create_resized(int_type, 0, 8, "padded_int")
    assert resized.extent == 8
    assert resized.size == 4

    # contiguous(3, padded_int): should produce extent=24 via LB/UB propagation
    arr = type_contiguous(3, resized, "int_arr")
    assert arr.extent == 24, (
        f"Contiguous of resized type should have extent=24 (3*8 via LB/UB propagation), got {arr.extent}"
    )
    assert arr.size == 12


def test_independent_hindexed():
    """Test that hindexed_block treats displacements as byte offsets."""
    sys.path.insert(0, "/app")
    from mpi_types import MPIType, type_create_hindexed_block

    double_type = MPIType([("MPI_DOUBLE", 0)], "MPI_DOUBLE")

    # hindexed_block with byte displacements [0, 24], blocklength 1
    dt = type_create_hindexed_block(1, [0, 24], double_type, "test_hindex")
    tm = dt.get_data_typemap()
    assert len(tm) == 2
    assert tm[0] == ("MPI_DOUBLE", 0)
    assert tm[1] == ("MPI_DOUBLE", 24), (
        f"Displacement 24 is in bytes (not elements), entry should be at 24, got {tm[1][1]}"
    )
