#!/usr/bin/env python3
"""Reference verification — regenerates ground truth from deterministic seed."""

import pytest
import random
import re
import os


NUM_RELATIONS = 6
NUM_QUERIES = 25

SPECS = [
    (200, 4, 1, 50),
    (300, 3, 1, 50),
    (150, 4, 1, 40),
    (400, 3, 1, 50),
    (250, 4, 1, 50),
    (180, 3, 1, 50),
]

# Hardcoded queries — same as generated by generate_data.py with seed 42
QUERIES = [
    "0 1|0.0=1.0|0.2 1.2",
    "0 3|0.1=1.1|0.2 1.2",
    "1 3|0.0=1.0&1.2<30|0.2 1.2",
    "0 2|0.0=1.0|0.2 1.2",
    "0 4|0.0=1.0|0.2 1.2",
    "2 5|0.1=1.1|0.0 1.2",
    "3 5|0.0=1.0|0.2 1.2",
    "1 5|0.0=1.0|0.1 1.1",
    "0 1|0.0=1.0&0.2<25|0.3 1.2",
    "0 3|0.1=1.1&0.3<20|0.2 1.2",
    "0 1|0.0=1.0&0.2>30|0.3 1.1",
    "1 5|0.0=1.0&0.1<20|0.2 1.1",
    "0 0|0.0=1.0&1.2>30|0.3 1.3",
    "0 0|0.0=1.0&0.2>20|0.3 1.3",
    "0 0|0.0=1.0|0.2 1.3",
    "1 1|0.0=1.1&0.1>25|0.2 1.2",
    "3 3|0.0=1.0&0.1>25|0.1 1.1",
    "0 1|0.0=1.0&0.2>999|0.3 1.2",
    "0 3|0.1=1.1&0.3>999|0.2 1.2",
    "0 1 3|0.0=1.0&1.0=2.0|0.3 2.2",
    "0 1 2|0.0=1.0&1.0=2.0|0.3 2.3",
    "0 1 3|0.0=1.0&1.0=2.0&0.2<30|0.3 1.2 2.2",
    "0 3 4|0.0=1.0&1.0=2.0|0.3 2.3",
    "0 0 2|0.0=1.0&1.0=2.0&0.2>20|0.3 2.2",
    "0 3|0.0=1.0&0.2=25|0.1 1.2",
]


def generate_ground_truth():
    """Regenerate correct relation data from the same seed used at build time."""
    rng = random.Random(42)
    relations = []
    for nrows, ncols, lo, hi in SPECS:
        cols = [[rng.randint(lo, hi) for _ in range(nrows)] for _ in range(ncols)]
        relations.append((nrows, ncols, cols))
    return relations


def _apply_filter(val, op, ref):
    if op == '=':
        return val == ref
    elif op == '>':
        return val > ref
    elif op == '<':
        return val < ref
    return False


def _parse_query(qstr):
    parts = qstr.strip().split('|')
    rel_ids = list(map(int, parts[0].split()))
    joins, filters = [], []
    for pred in parts[1].split('&'):
        m = re.match(r'(\d+)\.(\d+)([=<>])(.*)', pred)
        if not m:
            continue
        pos, col = int(m.group(1)), int(m.group(2))
        op = m.group(3)
        rhs = m.group(4)
        if '.' in rhs:
            rpos, rcol = map(int, rhs.split('.'))
            joins.append((pos, col, rpos, rcol))
        else:
            filters.append((pos, col, op, int(rhs)))
    projs = []
    for p in parts[2].split():
        pos, col = map(int, p.split('.'))
        projs.append((pos, col))
    return rel_ids, joins, filters, projs


def execute_query(relations, qstr):
    """Execute a single query correctly and return result string."""
    rel_ids, joins, filters, projs = _parse_query(qstr)
    npos = len(rel_ids)

    # Independent filtered tuple sets per position (no caching)
    pos_tuples = {}
    for p in range(npos):
        rid = rel_ids[p]
        nrows, ncols, cols = relations[rid]
        rows = []
        for r in range(nrows):
            row = [cols[c][r] for c in range(ncols)]
            keep = True
            for fp, fc, fo, fv in filters:
                if fp == p and not _apply_filter(row[fc], fo, fv):
                    keep = False
                    break
            if keep:
                rows.append(row)
        pos_tuples[p] = rows

    # BFS join order from position 0
    adj = {p: set() for p in range(npos)}
    for lp, lc, rp, rc in joins:
        adj[lp].add(rp)
        adj[rp].add(lp)

    order = [0]
    seen = {0}
    q = [0]
    while q:
        cur = q.pop(0)
        for nb in sorted(adj[cur]):
            if nb not in seen:
                seen.add(nb)
                order.append(nb)
                q.append(nb)
    for p in range(npos):
        if p not in seen:
            order.append(p)

    # Incremental hash join
    first = order[0]
    result = [{first: row} for row in pos_tuples[first]]
    joined = {first}

    for step in range(1, len(order)):
        nxt = order[step]
        appl = []
        for lp, lc, rp, rc in joins:
            if lp == nxt and rp in joined:
                appl.append((rp, rc, lc))
            elif rp == nxt and lp in joined:
                appl.append((lp, lc, rc))

        new_result = []
        if appl:
            ep, ec, nc = appl[0]
            ht = {}
            for row in pos_tuples[nxt]:
                ht.setdefault(row[nc], []).append(row)
            for combo in result:
                for row in ht.get(combo[ep][ec], []):
                    ok = True
                    for ep2, ec2, nc2 in appl[1:]:
                        if combo[ep2][ec2] != row[nc2]:
                            ok = False
                            break
                    if ok:
                        d = dict(combo)
                        d[nxt] = row
                        new_result.append(d)
        else:
            for combo in result:
                for row in pos_tuples[nxt]:
                    d = dict(combo)
                    d[nxt] = row
                    new_result.append(d)

        result = new_result
        joined.add(nxt)

    if not result:
        return ' '.join(['NULL'] * len(projs))

    sums = [0] * len(projs)
    for combo in result:
        for j, (pp, pc) in enumerate(projs):
            sums[j] += combo[pp][pc]
    return ' '.join(str(s) for s in sums)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def relations():
    return generate_ground_truth()


@pytest.fixture(scope="module")
def queries():
    return list(QUERIES)


@pytest.fixture(scope="module")
def expected(relations, queries):
    return [execute_query(relations, q) for q in queries]


@pytest.fixture(scope="module")
def actual():
    path = '/app/output.txt'
    assert os.path.exists(path), "Output file /app/output.txt not found."
    with open(path) as f:
        return [line.strip() for line in f if line.strip()]


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_output_exists():
    assert os.path.exists('/app/output.txt'), "/app/output.txt does not exist"


def test_line_count(expected, actual):
    assert len(actual) == len(expected), \
        f"Expected {len(expected)} lines, got {len(actual)}"


@pytest.mark.parametrize("idx", range(NUM_QUERIES))
def test_query(idx, queries, expected, actual):
    assert idx < len(actual), f"Missing output for query {idx}"
    actual_norm = ' '.join(actual[idx].split())
    expected_norm = ' '.join(expected[idx].split())
    assert actual_norm == expected_norm, (
        f"Query {idx}: {queries[idx]}\n"
        f"Expected: {expected_norm}\n"
        f"Got:      {actual_norm}"
    )
