port 6379
bind 127.0.0.1
requirepass secretpass
masterauth secretpass
dir /data/redis-node-a
appendonly yes
appendfilename "appendonly.aof"
appenddirname "appendonlydir"
aof-load-truncated no
aof-use-rdb-preamble yes
save ""
daemonize no
loglevel notice
logfile /var/log/redis/node-a.log
