(* ================================================================== *)
(* Formal specifications: P-256 modular arithmetic operations          *)
(* Excerpted from s2n-bignum proof files                               *)
(* ================================================================== *)

(* Uses p_256, bignum_from_memory from spec_common.ml and              *)
(* spec_montmul_p256.ml                                                *)

(* ------------------------------------------------------------------ *)
(* Modular addition: bignum_add_p256                                   *)
(*                                                                     *)
(* ensures x86                                                         *)
(*   (\s. read RDI s = z /\ read RSI s = x /\ read RDX s = y /\      *)
(*        bignum_from_memory(x,4) s = a /\                             *)
(*        bignum_from_memory(y,4) s = b /\                             *)
(*        a < p_256 /\ b < p_256 /\                                    *)
(*        aliasing_ok(x,z) /\ aliasing_ok(y,z))                       *)
(*   (\s. bignum_from_memory(z,4) s = (a + b) MOD p_256)              *)
(*   (MAYCHANGE [memory :> bytes(z,32)] ,,                             *)
(*    MAYCHANGE_REGS_AND_FLAGS_PERMITTED_BY_ABI)                       *)
(*                                                                     *)
(* The output is (a + b) mod p_256, fully reduced to [0, p_256).      *)
(* Since a,b < p_256, we have a + b < 2*p_256, so at most one         *)
(* subtraction of p_256 is needed.                                     *)
(*                                                                     *)
(* Implementation note: compute s = a + b (may be 257 bits), then     *)
(* if s >= p_256, output s - p_256, else output s.                    *)
(* ------------------------------------------------------------------ *)

(* ------------------------------------------------------------------ *)
(* Modular subtraction: bignum_sub_p256                                *)
(*                                                                     *)
(* ensures x86                                                         *)
(*   (\s. read RDI s = z /\ read RSI s = x /\ read RDX s = y /\      *)
(*        bignum_from_memory(x,4) s = a /\                             *)
(*        bignum_from_memory(y,4) s = b /\                             *)
(*        a < p_256 /\ b < p_256 /\                                    *)
(*        aliasing_ok(x,z) /\ aliasing_ok(y,z))                       *)
(*   (\s. bignum_from_memory(z,4) s = (p_256 + a - b) MOD p_256)      *)
(*   (MAYCHANGE [memory :> bytes(z,32)] ,,                             *)
(*    MAYCHANGE_REGS_AND_FLAGS_PERMITTED_BY_ABI)                       *)
(*                                                                     *)
(* Note: the postcondition uses (p_256 + a - b) MOD p_256 which       *)
(* equals (a - b) MOD p_256 since p_256 ≡ 0 (mod p_256).             *)
(* This formulation avoids underflow in the natural number domain.     *)
(*                                                                     *)
(* Implementation note: compute d = a - b. If borrow occurred         *)
(* (a < b), add p_256 back: output d + p_256.                         *)
(* ------------------------------------------------------------------ *)

(* ------------------------------------------------------------------ *)
(* To-Montgomery conversion: bignum_tomont_p256                        *)
(*                                                                     *)
(* ensures x86                                                         *)
(*   (\s. read RDI s = z /\ read RSI s = x /\                         *)
(*        bignum_from_memory(x,4) s = a /\                             *)
(*        a < p_256 /\                                                  *)
(*        aliasing_ok(x,z))                                            *)
(*   (\s. bignum_from_memory(z,4) s = (2 EXP 256 * a) MOD p_256)      *)
(*   (MAYCHANGE [memory :> bytes(z,32)] ,,                             *)
(*    MAYCHANGE_REGS_AND_FLAGS_PERMITTED_BY_ABI)                       *)
(*                                                                     *)
(* Converts a standard integer to Montgomery representation:           *)
(*   tomont(a) = a * R mod p_256                                       *)
(*                                                                     *)
(* Can be implemented as montmul(a, R^2 mod p_256), since:            *)
(*   montmul(a, R^2) = a * R^2 * R^{-1} mod p = a * R mod p          *)
(*                                                                     *)
(* R^2 mod p_256 is the precomputed constant:                          *)
(*   0x00000004FFFFFFFD FFFFFFFFFFFFFFFE FFFFFFFBFFFFFFFF              *)
(*   0000000000000003                                                   *)
(* (in 64-bit limbs, most significant first)                           *)
(* ------------------------------------------------------------------ *)

(* ------------------------------------------------------------------ *)
(* From-Montgomery conversion: bignum_demont_p256                      *)
(*                                                                     *)
(* ensures x86                                                         *)
(*   (\s. read RDI s = z /\ read RSI s = x /\                         *)
(*        bignum_from_memory(x,4) s = a /\                             *)
(*        a < p_256 /\                                                  *)
(*        aliasing_ok(x,z))                                            *)
(*   (\s. bignum_from_memory(z,4) s =                                  *)
(*          (inverse_mod p_256 (2 EXP 256) * a) MOD p_256)             *)
(*   (MAYCHANGE [memory :> bytes(z,32)] ,,                             *)
(*    MAYCHANGE_REGS_AND_FLAGS_PERMITTED_BY_ABI)                       *)
(*                                                                     *)
(* Converts from Montgomery representation back to standard:           *)
(*   frommont(m) = m * R^{-1} mod p_256                                *)
(*                                                                     *)
(* Can be implemented as montmul(m, 1), since:                         *)
(*   montmul(m, 1) = m * 1 * R^{-1} mod p = m * R^{-1} mod p         *)
(* ------------------------------------------------------------------ *)

(* ------------------------------------------------------------------ *)
(* Modular inverse:                                                    *)
(*                                                                     *)
(* Given x in Montgomery form (representing a), compute z in           *)
(* Montgomery form representing a^{-1} mod p_256.                      *)
(*                                                                     *)
(* Formally: if x = a * R mod p_256, then                              *)
(*   z = a^{-1} * R mod p_256                                          *)
(*                                                                     *)
(* By Fermat's little theorem (p_256 is prime):                        *)
(*   a^{-1} ≡ a^{p_256 - 2} (mod p_256)                              *)
(*                                                                     *)
(* In Montgomery form, this becomes:                                    *)
(*   inv(x) = x^{p_256 - 2} computed using montsqr and montmul        *)
(*                                                                     *)
(* Proof sketch:                                                       *)
(*   Let x = aR mod p. Then montsqr(x) = (aR)^2 * R^{-1} = a^2*R.    *)
(*   By induction, x^k (via mont operations) = a^k * R mod p.         *)
(*   So x^{p-2} via mont operations = a^{p-2} * R = a^{-1} * R mod p. *)
(*                                                                     *)
(* p_256 - 2 in 64-bit limbs (little-endian):                         *)
(*   [0xFFFFFFFFFFFFFFFD; 0x00000000FFFFFFFF;                          *)
(*    0x0000000000000000; 0xFFFFFFFF00000001]                          *)
(* ------------------------------------------------------------------ *)
