"""
Tests for coastal wave transformation analysis system.
Verifies build system, C library, AWK preprocessor, Python pipeline,
and SQLite results against USACE CEM (EM 1110-2-1100) golden values.
"""

import subprocess
import json
import math
import os
import sqlite3
import ctypes
import tempfile
import pytest

G = 9.81


def run_pipeline(scenario_path):
    """Run the coastal pipeline CLI with a scenario file and return parsed JSON."""
    result = subprocess.run(
        ["python3", "/app/coastal_pipeline.py", scenario_path],
        capture_output=True, text=True, timeout=120
    )
    assert result.returncode == 0, (
        f"Pipeline returned exit code {result.returncode}.\n"
        f"stderr: {result.stderr}\nstdout: {result.stdout}"
    )
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as e:
        pytest.fail(f"Invalid JSON output: {e}\nstdout: {result.stdout}")


def assert_close(actual, expected, rtol=0.05, atol=0.05, label=""):
    """Assert value within relative tolerance (for |expected|>0.1) or absolute."""
    prefix = f"[{label}] " if label else ""
    if abs(expected) > 0.1:
        rel_err = abs(actual - expected) / abs(expected)
        assert rel_err < rtol, (
            f"{prefix}Expected {expected:.6f}, got {actual:.6f} "
            f"(rel error {rel_err:.4f}, rtol={rtol})"
        )
    else:
        abs_err = abs(actual - expected)
        assert abs_err < atol, (
            f"{prefix}Expected {expected:.6f}, got {actual:.6f} "
            f"(abs error {abs_err:.4f}, atol={atol})"
        )


# ===========================================================================
# BUILD SYSTEM — Makefile, C library, AWK script existence & usability
# ===========================================================================
class TestBuildSystem:
    def test_makefile_exists(self):
        assert os.path.isfile("/app/Makefile"), "Makefile not found at /app/Makefile"

    def test_libdispersion_exists(self):
        assert os.path.isfile("/app/lib/libdispersion.so"), (
            "libdispersion.so not found — 'make lib' may have failed"
        )

    def test_pipeline_exists(self):
        assert os.path.isfile("/app/coastal_pipeline.py"), (
            "coastal_pipeline.py not found"
        )

    def test_preprocess_awk_exists(self):
        assert os.path.isfile("/app/preprocess.awk"), (
            "preprocess.awk not found"
        )

    def test_pipeline_uses_c_library(self):
        """Pipeline must load and call the C shared library."""
        with open("/app/coastal_pipeline.py") as f:
            source = f.read()
        assert "libdispersion" in source, "Pipeline must reference libdispersion shared library"
        uses_c_interop = any(kw in source for kw in ["ctypes", "cffi", "cdll", "CDLL", "ffi"])
        assert uses_c_interop, "Pipeline must use a C interop mechanism to call the shared library"

    def test_make_clean_target(self):
        """Verify make clean target exists (dry run)."""
        result = subprocess.run(
            ["make", "-n", "clean"], capture_output=True, text=True, cwd="/app"
        )
        assert result.returncode == 0, f"make -n clean failed: {result.stderr}"

    def test_profiles_generated(self):
        """After make preprocess, profile JSON files should exist in /app/profiles/."""
        assert os.path.isdir("/app/profiles"), "profiles directory not found"
        profiles = [f for f in os.listdir("/app/profiles") if f.endswith(".json")]
        assert len(profiles) >= 1, "No profile JSON files generated by preprocessing"

    def test_profile_content_valid(self):
        """At least one profile file must contain valid JSON with expected structure."""
        import glob
        profiles = glob.glob("/app/profiles/*.json")
        assert profiles, "No profile files found"
        with open(profiles[0]) as f:
            data = json.loads(f.read())
        assert isinstance(data, list), "Profile should be a JSON array"
        assert len(data) > 0, "Profile should have entries"
        assert "station" in data[0], "Profile entries must have 'station' key"
        assert "depth_m" in data[0], "Profile entries must have 'depth_m' key"
        assert data[0]["depth_m"] > 0, "Depths should be positive"


# ===========================================================================
# C LIBRARY — dispersion solver correctness via ctypes
# ===========================================================================
class TestCLibrary:
    @pytest.fixture(scope="class")
    def lib(self):
        lib_path = "/app/lib/libdispersion.so"
        assert os.path.isfile(lib_path), f"C library not found at {lib_path}"
        lib = ctypes.CDLL(lib_path)
        lib.solve_dispersion.argtypes = [
            ctypes.c_double, ctypes.c_double,
            ctypes.POINTER(ctypes.c_double)
        ]
        lib.solve_dispersion.restype = ctypes.c_int
        return lib

    def _call(self, lib, T, d):
        out = (ctypes.c_double * 5)()
        ret = lib.solve_dispersion(T, d, out)
        assert ret == 0, f"solve_dispersion returned {ret} for T={T}, d={d}"
        return {"L": out[0], "C": out[1], "Cg": out[2], "k": out[3], "n": out[4]}

    def test_deep_water_wavelength(self, lib):
        """At d=200m (deep water), L ~ Lo = g*T^2/(2*pi) ~ 156m."""
        r = self._call(lib, 10.0, 200.0)
        assert_close(r["L"], 156.13, rtol=0.03, label="C lib L at d=200")

    def test_deep_water_celerity(self, lib):
        r = self._call(lib, 10.0, 200.0)
        assert_close(r["C"], 15.61, rtol=0.03, label="C lib C at d=200")

    def test_deep_water_n(self, lib):
        """In deep water, n should be 0.5."""
        r = self._call(lib, 10.0, 200.0)
        assert_close(r["n"], 0.5, atol=0.01, label="C lib n deep water")

    def test_intermediate_wavelength(self, lib):
        """At d=3m, L ~ 53.3m per CEM Example II-1-1."""
        r = self._call(lib, 10.0, 3.0)
        assert_close(r["L"], 53.29, rtol=0.03, label="C lib L at d=3")

    def test_intermediate_celerity(self, lib):
        r = self._call(lib, 10.0, 3.0)
        assert_close(r["C"], 5.33, rtol=0.03, label="C lib C at d=3")

    def test_dispersion_relation_satisfied(self, lib):
        """Verify omega^2 = g*k*tanh(k*d) for computed results."""
        T = 10.0
        omega = 2.0 * math.pi / T
        omega_sq = omega ** 2
        for d in [200.0, 3.0, 0.5, 50.0]:
            r = self._call(lib, T, d)
            k = r["k"]
            rhs = G * k * math.tanh(k * d)
            rel = abs(omega_sq - rhs) / omega_sq
            assert rel < 1e-6, (
                f"Dispersion not satisfied at d={d}: "
                f"omega^2={omega_sq:.6f}, g*k*tanh(kd)={rhs:.6f}, rel={rel:.6e}"
            )

    def test_cg_equals_n_times_c(self, lib):
        """Verify Cg = n * C for all results."""
        r = self._call(lib, 10.0, 3.0)
        assert_close(r["Cg"], r["n"] * r["C"], rtol=0.001, label="Cg=n*C")

    def test_shallow_water_n(self, lib):
        """In very shallow water, n should approach 1.0."""
        r = self._call(lib, 10.0, 0.1)
        assert r["n"] > 0.9, f"n should approach 1.0 in shallow water, got {r['n']}"


# ===========================================================================
# AWK PREPROCESSOR — bathymetric survey conversion
# ===========================================================================
class TestAWKPreprocess:
    def _run_awk(self, survey_content):
        with tempfile.NamedTemporaryFile(mode='w', suffix='.survey', delete=False) as f:
            f.write(survey_content)
            tmp_path = f.name
        try:
            result = subprocess.run(
                ["awk", "-f", "/app/preprocess.awk", tmp_path],
                capture_output=True, text=True, timeout=10
            )
            return result
        finally:
            os.unlink(tmp_path)

    def test_basic_conversion(self):
        """Convert two stations and verify depth calculation."""
        survey = ("# Test survey\n"
                  "STA-001 100.0 200.0 -32.808\n"
                  "STA-002 150.0 200.0 -65.617\n")
        result = self._run_awk(survey)
        assert result.returncode == 0, f"AWK failed: {result.stderr}"
        data = json.loads(result.stdout)
        assert len(data) == 2
        assert data[0]["station"] == "STA-001"
        assert_close(data[0]["depth_m"], 10.0, rtol=0.01, label="depth 10m")
        assert data[1]["station"] == "STA-002"
        assert_close(data[1]["depth_m"], 20.0, rtol=0.01, label="depth 20m")

    def test_comment_skipping(self):
        """Lines starting with # must be skipped."""
        survey = ("# Header comment\n"
                  "# Another comment\n"
                  "STA-001 100.0 200.0 -32.808\n"
                  "# Inline comment\n"
                  "STA-002 150.0 200.0 -65.617\n")
        result = self._run_awk(survey)
        assert result.returncode == 0
        data = json.loads(result.stdout)
        assert len(data) == 2, f"Expected 2 entries (comments skipped), got {len(data)}"

    def test_blank_line_skipping(self):
        """Blank lines must be skipped."""
        survey = ("STA-001 100.0 200.0 -32.808\n"
                  "\n"
                  "STA-002 150.0 200.0 -65.617\n")
        result = self._run_awk(survey)
        assert result.returncode == 0
        data = json.loads(result.stdout)
        assert len(data) == 2

    def test_unit_conversion(self):
        """Verify ft to m conversion: -1 ft NAVD88 -> depth = 0.3048 m."""
        survey = "TST-001 0.0 0.0 -1.0\n"
        result = self._run_awk(survey)
        assert result.returncode == 0
        data = json.loads(result.stdout)
        assert_close(data[0]["depth_m"], 0.3048, rtol=0.001, label="unit conversion")

    def test_valid_json_output(self):
        """Output must be valid JSON array."""
        survey = "STA-001 100.0 200.0 -32.808\n"
        result = self._run_awk(survey)
        data = json.loads(result.stdout)
        assert isinstance(data, list)

    def test_actual_survey_file(self):
        """Preprocess one of the actual survey files from /app/raw_surveys/."""
        result = subprocess.run(
            ["awk", "-f", "/app/preprocess.awk", "/app/raw_surveys/profile_P001.survey"],
            capture_output=True, text=True, timeout=10
        )
        assert result.returncode == 0, f"Failed on actual survey: {result.stderr}"
        data = json.loads(result.stdout)
        assert len(data) == 5, f"P001 should have 5 stations, got {len(data)}"
        # First station should be ~100m depth (-328.084 ft * 0.3048)
        assert_close(data[0]["depth_m"], 100.0, rtol=0.01, label="P001 first depth")

    def test_corrupted_survey_handling(self):
        """P003 has data quality issues: incomplete record, positive elevation."""
        result = subprocess.run(
            ["awk", "-f", "/app/preprocess.awk", "/app/raw_surveys/profile_P003.survey"],
            capture_output=True, text=True, timeout=10
        )
        assert result.returncode == 0, f"Failed on P003: {result.stderr}"
        data = json.loads(result.stdout)
        # All returned entries must have positive depth
        assert all(entry["depth_m"] > 0 for entry in data), (
            "All depths must be positive — filter invalid entries"
        )
        # P003 has: 2 good stations, 1 incomplete record (skip),
        # 1 positive-elevation station (skip), 2 more good stations = 4 valid
        assert len(data) == 4, (
            f"P003 should have 4 valid entries after filtering, got {len(data)}"
        )

    def test_positive_elevation_filtered(self):
        """Stations with positive elevation (above water) must be excluded."""
        survey = ("STA-001 0.0 0.0 -32.808\n"
                  "STA-002 0.0 0.0 5.0\n"
                  "STA-003 0.0 0.0 -16.404\n")
        result = self._run_awk(survey)
        assert result.returncode == 0
        data = json.loads(result.stdout)
        assert len(data) == 2, (
            f"Should have 2 entries (positive elevation filtered), got {len(data)}"
        )
        stations = [e["station"] for e in data]
        assert "STA-002" not in stations, "Positive-elevation station should be filtered"

    def test_incomplete_record_skipped(self):
        """Records with fewer than 4 fields must be skipped."""
        survey = ("STA-001 0.0 0.0 -32.808\n"
                  "BAD_REC 100.0\n"
                  "STA-002 0.0 0.0 -65.617\n")
        result = self._run_awk(survey)
        assert result.returncode == 0
        data = json.loads(result.stdout)
        assert len(data) == 2, (
            f"Should have 2 entries (incomplete record skipped), got {len(data)}"
        )


# ===========================================================================
# DISPERSION (CEM Example II-1-1: T=10s, d=200m and d=3m)
# ===========================================================================
class TestDispersion:
    @pytest.fixture(scope="class")
    def disp_data(self):
        return run_pipeline("/app/scenarios/dispersion.json")

    def test_deep_water_wavelength(self, disp_data):
        """At d=200m (deep water), L should equal Lo = g*T^2/(2*pi) ~ 156m."""
        r = disp_data["results"][0]
        assert abs(r["d"] - 200.0) < 1.0
        assert_close(r["L"], 156.13, rtol=0.03, label="L at d=200")

    def test_deep_water_celerity(self, disp_data):
        r = disp_data["results"][0]
        assert_close(r["C"], 15.61, rtol=0.03, label="C at d=200")

    def test_deep_water_group_ratio(self, disp_data):
        """In deep water, n should be 0.5."""
        r = disp_data["results"][0]
        assert_close(r["n"], 0.5, atol=0.02, label="n at d=200")

    def test_intermediate_wavelength(self, disp_data):
        """At d=3m, L ~ 53.3m per CEM Example II-1-1."""
        r = disp_data["results"][1]
        assert abs(r["d"] - 3.0) < 0.1
        assert_close(r["L"], 53.29, rtol=0.03, label="L at d=3")

    def test_intermediate_celerity(self, disp_data):
        r = disp_data["results"][1]
        assert_close(r["C"], 5.33, rtol=0.03, label="C at d=3")

    def test_dispersion_relation_satisfied(self, disp_data):
        """Verify omega^2 = g*k*tanh(k*d) for all computed results."""
        T = 10.0
        omega = 2.0 * math.pi / T
        omega_sq = omega ** 2
        for r in disp_data["results"]:
            k = r["k"]
            d = r["d"]
            rhs = G * k * math.tanh(k * d)
            rel = abs(omega_sq - rhs) / omega_sq
            assert rel < 1e-3, (
                f"Dispersion not satisfied at d={d}: "
                f"omega^2={omega_sq:.6f}, g*k*tanh(kd)={rhs:.6f}, rel={rel:.6e}"
            )

    def test_group_velocity_consistency(self, disp_data):
        """Verify Cg = n * C for all results."""
        for r in disp_data["results"]:
            expected_cg = r["n"] * r["C"]
            assert_close(r["Cg"], expected_cg, rtol=0.01,
                         label=f"Cg consistency at d={r['d']}")


# ===========================================================================
# TRANSECT - NORMAL INCIDENCE (CEM Example II-3-1: theta0=0)
# ===========================================================================
class TestTransectNormal:
    @pytest.fixture(scope="class")
    def trans_data(self):
        return run_pipeline("/app/scenarios/transect_normal.json")

    def test_wave_height_d100(self, trans_data):
        """At d=100m, theta0=0: H ~ 0.94 per CEM table."""
        r = next(x for x in trans_data["results"] if abs(x["d"] - 100) < 1)
        assert_close(r["H"], 0.94, rtol=0.05, label="H at d=100, theta0=0")

    def test_wave_height_d10(self, trans_data):
        """At d=10m, theta0=0: H ~ 1.14 per CEM table."""
        r = next(x for x in trans_data["results"] if abs(x["d"] - 10) < 1)
        assert_close(r["H"], 1.14, rtol=0.05, label="H at d=10, theta0=0")

    def test_wave_height_d4(self, trans_data):
        """At d=4m, theta0=0: H ~ 1.39 per CEM table."""
        r = next(x for x in trans_data["results"] if abs(x["d"] - 4) < 1)
        assert_close(r["H"], 1.39, rtol=0.05, label="H at d=4, theta0=0")

    def test_angle_stays_zero(self, trans_data):
        """For theta0=0, angle should remain 0 at all depths."""
        for r in trans_data["results"]:
            assert abs(r["theta"]) < 0.5, (
                f"Angle should be ~0 for normal incidence, got {r['theta']} at d={r['d']}"
            )

    def test_kr_unity_for_normal(self, trans_data):
        """For normal incidence, Kr should be 1.0 at all depths."""
        for r in trans_data["results"]:
            assert_close(r["Kr"], 1.0, atol=0.02,
                         label=f"Kr at d={r['d']}, theta0=0")


# ===========================================================================
# TRANSECT - OBLIQUE 45 DEGREES (CEM Example II-3-1: theta0=45)
# ===========================================================================
class TestTransectOblique:
    @pytest.fixture(scope="class")
    def trans_data(self):
        return run_pipeline("/app/scenarios/transect_oblique.json")

    def test_wave_height_d10(self, trans_data):
        """At d=10m, theta0=45: H ~ 0.98 per CEM table."""
        r = next(x for x in trans_data["results"] if abs(x["d"] - 10) < 1)
        assert_close(r["H"], 0.98, rtol=0.05, label="H at d=10, theta0=45")

    def test_wave_angle_d10(self, trans_data):
        """At d=10m, theta0=45: theta ~ 16.8 deg per CEM."""
        r = next(x for x in trans_data["results"] if abs(x["d"] - 10) < 1)
        assert_close(r["theta"], 16.8, atol=1.0, label="theta at d=10")

    def test_wave_height_d4(self, trans_data):
        """At d=4m, theta0=45: H ~ 1.18 per CEM table."""
        r = next(x for x in trans_data["results"] if abs(x["d"] - 4) < 1)
        assert_close(r["H"], 1.18, rtol=0.05, label="H at d=4, theta0=45")

    def test_wave_angle_d4(self, trans_data):
        """At d=4m, theta0=45: theta ~ 10.8 deg per CEM."""
        r = next(x for x in trans_data["results"] if abs(x["d"] - 4) < 1)
        assert_close(r["theta"], 10.8, atol=1.0, label="theta at d=4")

    def test_angle_decreases_shoreward(self, trans_data):
        """Wave angle must decrease as depth decreases (refraction)."""
        results = sorted(trans_data["results"], key=lambda x: -x["d"])
        for i in range(len(results) - 1):
            assert results[i]["theta"] >= results[i + 1]["theta"] - 0.1, (
                f"Angle not decreasing: {results[i]['theta']} at d={results[i]['d']} "
                f"vs {results[i+1]['theta']} at d={results[i+1]['d']}"
            )


# ===========================================================================
# WAVE BREAKING (CEM Example II-4-1: slope=1:100, H0=2m, T=10s, Kr=1.05)
# ===========================================================================
class TestBreaking:
    @pytest.fixture(scope="class")
    def brk_data(self):
        return run_pipeline("/app/scenarios/breaking.json")

    def test_breaker_height(self, brk_data):
        """Hb ~ 2.78m (precise) or ~2.7m (CEM rounded)."""
        assert_close(brk_data["Hb"], 2.78, rtol=0.05, label="Hb")

    def test_breaker_depth(self, brk_data):
        """db ~ 3.34m (precise) or ~3.2m (CEM rounded)."""
        assert_close(brk_data["db"], 3.34, rtol=0.06, label="db")

    def test_gamma_b_range(self, brk_data):
        """Breaker depth index should be physically reasonable (0.5 to 1.5)."""
        gb = brk_data["gamma_b"]
        assert 0.5 < gb < 1.5, f"gamma_b={gb} outside reasonable range"

    def test_hb_db_consistency(self, brk_data):
        """Hb / db should equal gamma_b."""
        ratio = brk_data["Hb"] / brk_data["db"]
        assert_close(ratio, brk_data["gamma_b"], rtol=0.01, label="Hb/db vs gamma_b")


# ===========================================================================
# WAVE SETUP (CEM Example II-4-2: Hb=2.7m, db=3.2m, gamma_b=0.84, m=0.01)
# ===========================================================================
class TestSetup:
    @pytest.fixture(scope="class")
    def setup_data(self):
        return run_pipeline("/app/scenarios/setup.json")

    def test_setdown_at_breaker(self, setup_data):
        """eta_b ~ -0.141m per CEM (-0.14 rounded)."""
        assert_close(setup_data["eta_b"], -0.141, atol=0.02, label="eta_b")

    def test_setdown_is_negative(self, setup_data):
        assert setup_data["eta_b"] < 0, "Setdown at breaker must be negative"

    def test_setup_at_shoreline(self, setup_data):
        """eta_s ~ 0.558m per CEM (0.56 rounded)."""
        assert_close(setup_data["eta_s"], 0.558, rtol=0.05, label="eta_s")

    def test_max_setup(self, setup_data):
        """eta_max ~ 0.705m per CEM (0.71 rounded)."""
        assert_close(setup_data["eta_max"], 0.705, rtol=0.05, label="eta_max")

    def test_max_greater_than_shoreline(self, setup_data):
        assert setup_data["eta_max"] > setup_data["eta_s"], (
            "Maximum setup must exceed setup at SWL shoreline"
        )

    def test_shoreline_displacement(self, setup_data):
        """Shoreline displacement ~ 70.5m per CEM (71 rounded)."""
        assert_close(setup_data["shoreline_displacement_m"], 70.5, rtol=0.10,
                     label="shoreline displacement")


# ===========================================================================
# WAVE RUNUP (CEM Example II-4-3: slope=1:80, H0=4m, T=9s)
# ===========================================================================
class TestRunup:
    @pytest.fixture(scope="class")
    def runup_data(self):
        return run_pipeline("/app/scenarios/runup.json")

    def test_max_runup(self, runup_data):
        """Rmax ~ 1.20m per CEM Example II-4-3."""
        assert_close(runup_data["Rmax"], 1.20, rtol=0.05, label="Rmax")

    def test_r2pct(self, runup_data):
        """R2% ~ 1.13m."""
        assert_close(runup_data["R2pct"], 1.13, rtol=0.05, label="R2pct")

    def test_significant_runup(self, runup_data):
        """R_1/3 ~ 0.86m per CEM."""
        assert_close(runup_data["R_1_3"], 0.86, rtol=0.05, label="R_1_3")

    def test_runup_ordering(self, runup_data):
        """Rmax > R2% > R_1_10 > R_1_3 > R_mean."""
        assert runup_data["Rmax"] > runup_data["R2pct"] > runup_data["R_1_10"], (
            "Runup statistics not in expected order"
        )
        assert runup_data["R_1_10"] > runup_data["R_1_3"] > runup_data["R_mean"], (
            "Runup statistics not in expected order"
        )

    def test_all_positive(self, runup_data):
        for key in ["Rmax", "R2pct", "R_1_10", "R_1_3", "R_mean"]:
            assert runup_data[key] > 0, f"{key} must be positive"


# ===========================================================================
# OVERTOPPING (CEM Example VI-7-6: Hs_toe=1.69m, Tp=8s, cot=2.5, Rc=1.5m)
# ===========================================================================
class TestOvertopping:
    @pytest.fixture(scope="class")
    def ovt_data(self):
        return run_pipeline("/app/scenarios/overtopping.json")

    def test_owen_discharge(self, ovt_data):
        """Owen q ~ 0.325 m^3/s/m per CEM Example VI-7-6."""
        assert_close(ovt_data["owen"]["q"], 0.325, rtol=0.10, label="Owen q")

    def test_vdm_discharge(self, ovt_data):
        """van der Meer q ~ 0.137 m^3/s/m per CEM Example VI-7-6."""
        assert_close(ovt_data["vdm"]["q"], 0.137, rtol=0.10, label="vdM q")

    def test_owen_greater_than_vdm(self, ovt_data):
        """For this scenario, Owen should predict higher overtopping than vdM."""
        assert ovt_data["owen"]["q"] > ovt_data["vdm"]["q"], (
            "Owen should predict higher discharge than van der Meer for this scenario"
        )

    def test_both_positive(self, ovt_data):
        assert ovt_data["owen"]["q"] > 0
        assert ovt_data["vdm"]["q"] > 0


# ===========================================================================
# FULL PIPELINE (H0=1.5m, T=8s, slope=0.05, structure at dtoe=3.0m)
# ===========================================================================
class TestFullPipeline:
    @pytest.fixture(scope="class")
    def full_data(self):
        return run_pipeline("/app/scenarios/full_pipeline.json")

    def test_has_all_sections(self, full_data):
        """Full output must contain all required sections."""
        for key in ["breaking", "setup", "runup", "overtopping", "total_water_level"]:
            assert key in full_data, f"Missing section: {key}"

    def test_breaking_height(self, full_data):
        """Hb ~ 1.95m for H0=1.5, T=8, slope=0.05."""
        assert_close(full_data["breaking"]["Hb"], 1.95, rtol=0.05,
                     label="full:Hb")

    def test_breaking_depth(self, full_data):
        """db ~ 1.85m for these conditions."""
        assert_close(full_data["breaking"]["db"], 1.85, rtol=0.10,
                     label="full:db")

    def test_setup_positive(self, full_data):
        """Setup at shoreline should be positive."""
        assert full_data["setup"]["eta_s"] > 0
        assert full_data["setup"]["eta_max"] > 0

    def test_setup_max_value(self, full_data):
        """eta_max ~ 0.64 for slope=0.05."""
        assert_close(full_data["setup"]["eta_max"], 0.64, rtol=0.10,
                     label="full:eta_max")

    def test_runup_r2pct(self, full_data):
        """R2% ~ 1.48m for H0=1.5, T=8, slope=0.05."""
        assert_close(full_data["runup"]["R2pct"], 1.48, rtol=0.05,
                     label="full:R2pct")

    def test_overtopping_present(self, full_data):
        """Overtopping discharges should be computed."""
        assert full_data["overtopping"]["owen"]["q"] > 0.01
        assert full_data["overtopping"]["vdm"]["q"] > 0.01

    def test_twl_is_sum(self, full_data):
        """total_water_level should equal eta_max + R2pct."""
        expected = full_data["setup"]["eta_max"] + full_data["runup"]["R2pct"]
        assert_close(full_data["total_water_level"], expected, rtol=0.01,
                     label="TWL consistency")

    def test_twl_value(self, full_data):
        """TWL ~ 2.12m for these conditions."""
        assert_close(full_data["total_water_level"], 2.12, rtol=0.10,
                     label="full:TWL")

    def test_twl_reasonable_range(self, full_data):
        """TWL should be between 1m and 5m for these conditions."""
        twl = full_data["total_water_level"]
        assert 1.0 < twl < 5.0, f"TWL={twl} outside reasonable range"


# ===========================================================================
# SQLITE RESULTS — schema and data verification
# ===========================================================================
class TestSQLiteResults:
    def test_database_exists(self):
        assert os.path.isfile("/app/results.db"), "SQLite database not found at /app/results.db"

    def test_table_exists(self):
        conn = sqlite3.connect("/app/results.db")
        cursor = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='scenario_results'"
        )
        row = cursor.fetchone()
        conn.close()
        assert row is not None, "Table 'scenario_results' not found in database"

    def test_schema_columns(self):
        """Verify scenario_results table has required columns."""
        conn = sqlite3.connect("/app/results.db")
        cursor = conn.execute("PRAGMA table_info(scenario_results)")
        columns = {row[1] for row in cursor.fetchall()}
        conn.close()
        required = {"id", "scenario_name", "mode", "input_json", "output_json", "timestamp"}
        missing = required - columns
        assert not missing, f"Missing columns in scenario_results: {missing}"

    def test_results_present(self):
        """After make all, results should be in the database."""
        conn = sqlite3.connect("/app/results.db")
        cursor = conn.execute("SELECT COUNT(*) FROM scenario_results")
        count = cursor.fetchone()[0]
        conn.close()
        assert count > 0, "No results in database after pipeline run"

    def test_result_json_parseable(self):
        """Stored output_json must be valid JSON."""
        conn = sqlite3.connect("/app/results.db")
        cursor = conn.execute("SELECT output_json FROM scenario_results LIMIT 1")
        row = cursor.fetchone()
        conn.close()
        assert row is not None, "No results found"
        data = json.loads(row[0])
        assert isinstance(data, dict), "output_json should parse to a dict"

    def test_dispersion_in_db(self):
        """Run dispersion scenario and verify result is stored in DB."""
        run_pipeline("/app/scenarios/dispersion.json")
        conn = sqlite3.connect("/app/results.db")
        cursor = conn.execute(
            "SELECT output_json FROM scenario_results WHERE mode = 'dispersion'"
        )
        row = cursor.fetchone()
        conn.close()
        assert row is not None, "Dispersion result not found in database"
        data = json.loads(row[0])
        assert "results" in data

    def test_scenario_name_unique(self):
        """scenario_name should be UNIQUE — no duplicates."""
        conn = sqlite3.connect("/app/results.db")
        cursor = conn.execute(
            "SELECT scenario_name, COUNT(*) FROM scenario_results GROUP BY scenario_name HAVING COUNT(*) > 1"
        )
        duplicates = cursor.fetchall()
        conn.close()
        assert len(duplicates) == 0, f"Duplicate scenario names found: {duplicates}"

    def test_multiple_modes_in_db(self):
        """Database should contain results from multiple different modes."""
        conn = sqlite3.connect("/app/results.db")
        cursor = conn.execute("SELECT DISTINCT mode FROM scenario_results")
        modes = {row[0] for row in cursor.fetchall()}
        conn.close()
        assert len(modes) >= 3, f"Expected results from multiple modes, got: {modes}"
