#!/usr/bin/env python3
"""
FHIR R5 Transaction Processor Conformance Evaluator

Analyzes pre-generated output from three processor implementations against
the FHIR R5 specification and produces a structured conformance report.

"""

import json
import os
import glob


def load_bundle(path):
    with open(path) as f:
        return json.load(f)


def load_state(state_dir):
    resources = {}
    for filepath in glob.glob(os.path.join(state_dir, "*.json")):
        with open(filepath) as f:
            r = json.load(f)
            key = f"{r['resourceType']}/{r['id']}"
            resources[key] = r
    return resources


def find_all_urn_uuids(obj, path=""):
    """Find all remaining urn:uuid: strings anywhere in a JSON object."""
    results = []
    if isinstance(obj, str) and obj.startswith("urn:uuid:"):
        results.append((path, obj))
    elif isinstance(obj, dict):
        for k, v in obj.items():
            results.extend(find_all_urn_uuids(v, f"{path}.{k}"))
    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            results.extend(find_all_urn_uuids(item, f"{path}[{i}]"))
    return results


def find_conditional_refs(obj, path=""):
    """Find all conditional references (Type?search=value) in a JSON object."""
    results = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            if (k == "reference" and isinstance(v, str)
                    and "?" in v and not v.startswith("urn:")
                    and not v.startswith("http")):
                results.append((path, v))
            else:
                results.extend(find_conditional_refs(v, f"{path}.{k}"))
    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            results.extend(find_conditional_refs(item, f"{path}[{i}]"))
    return results


def evaluate_processor(output_dir, input_bundle_path, initial_state_dir):
    """Evaluate a processor's output for FHIR R5 conformance violations."""
    violations = []

    bundle_path = os.path.join(output_dir, "response_bundle.json")
    state_dir = os.path.join(output_dir, "server_state")

    if not os.path.exists(bundle_path):
        violations.append({
            "category": "other",
            "description": "No response bundle was generated by the processor.",
            "severity": "error"
        })
        return violations

    bundle = load_bundle(bundle_path)
    state = load_state(state_dir)
    input_bundle = load_bundle(input_bundle_path)
    initial_state = load_state(initial_state_dir)

    entries = bundle.get("entry", [])
    input_entries = input_bundle.get("entry", [])

    # ------------------------------------------------------------------
    # Check DELETE status codes (FHIR R5 3.2.0.7: 204 No Content)
    # ------------------------------------------------------------------
    for i, inp_entry in enumerate(input_entries):
        method = inp_entry.get("request", {}).get("method", "").upper()
        if method == "DELETE" and i < len(entries):
            status = entries[i].get("response", {}).get("status", "")
            if "204" not in status:
                violations.append({
                    "category": "status_codes",
                    "description": (
                        f"DELETE operation returned '{status}' instead of '204 No Content'. "
                        "Per FHIR R5 section 3.2.0.7, a server SHALL return 204 No Content "
                        "when no response body is included for a successful delete."
                    ),
                    "severity": "error"
                })

    # ------------------------------------------------------------------
    # Check for unresolved urn:uuid references in output state
    # ------------------------------------------------------------------
    all_unresolved = []
    for key, resource in state.items():
        urns = find_all_urn_uuids(resource)
        all_unresolved.extend([(key, path, urn) for path, urn in urns])

    if all_unresolved:
        extension_unresolved = [
            u for u in all_unresolved if ".extension" in u[1]
        ]
        supporting_info_unresolved = [
            u for u in all_unresolved if ".supportingInfo" in u[1]
        ]
        array_field_unresolved = [
            u for u in all_unresolved
            if any(f in u[1] for f in (".hasMember", ".derivedFrom", ".basedOn", ".partOf"))
        ]
        other_unresolved = [
            u for u in all_unresolved
            if u not in extension_unresolved
            and u not in supporting_info_unresolved
            and u not in array_field_unresolved
        ]

        if extension_unresolved:
            locations = "; ".join(f"{r}:{p}" for r, p, _ in extension_unresolved[:3])
            violations.append({
                "category": "reference_resolution",
                "description": (
                    f"urn:uuid: references inside extension elements were not resolved "
                    f"(at {locations}). The processor uses shallow field-enumeration for "
                    "reference resolution, only checking a hardcoded list of fields "
                    "(subject, encounter, etc.) and missing references in extensions and "
                    "nested structures. Per FHIR R5 section 3.2.0.11.2, implementers "
                    "SHOULD use recursive traversal of the entire resource structure to "
                    "resolve all urn:uuid: references."
                ),
                "severity": "error"
            })

        if array_field_unresolved:
            locations = "; ".join(f"{r}:{p}" for r, p, _ in array_field_unresolved[:3])
            if extension_unresolved:
                violations.append({
                    "category": "reference_resolution",
                    "description": (
                        f"urn:uuid: references in array-based reference fields were not "
                        f"resolved (at {locations}). Shallow field enumeration does not "
                        "traverse hasMember, derivedFrom, and similar array structures."
                    ),
                    "severity": "error"
                })
            else:
                violations.append({
                    "category": "reference_resolution",
                    "description": (
                        f"urn:uuid: references in array-based reference fields were not "
                        f"resolved (at {locations}). The processor builds the urn:uuid "
                        "mapping incrementally during POST processing, so forward "
                        "references to entries that appear later in the bundle remain "
                        "unresolved. All urn:uuid: identities should be assigned before "
                        "reference resolution begins."
                    ),
                    "severity": "error"
                })

        if supporting_info_unresolved:
            locations = "; ".join(f"{r}:{p}" for r, p, _ in supporting_info_unresolved[:3])
            # Determine if this is due to conditional create mapping failure
            # Check if the unresolved urn corresponds to a conditional create entry
            conditional_uuids = set()
            for inp_entry in input_entries:
                if inp_entry.get("request", {}).get("ifNoneExist"):
                    full_url = inp_entry.get("fullUrl", "")
                    if full_url:
                        conditional_uuids.add(full_url)

            if any(urn in conditional_uuids for _, _, urn in supporting_info_unresolved):
                violations.append({
                    "category": "reference_resolution",
                    "description": (
                        f"urn:uuid: references dependent on a conditional create's "
                        f"identity were not resolved (at {locations}). When a conditional "
                        "create (ifNoneExist) matches an existing resource, the entry's "
                        "fullUrl must still be mapped to the existing resource's identity "
                        "per FHIR R5 section 3.2.0.11.4.2, so that other entries "
                        "referencing it can resolve correctly."
                    ),
                    "severity": "error"
                })
            elif not extension_unresolved and not array_field_unresolved:
                violations.append({
                    "category": "reference_resolution",
                    "description": (
                        f"urn:uuid: references in supportingInfo fields were not resolved "
                        f"(at {locations})."
                    ),
                    "severity": "error"
                })

    # ------------------------------------------------------------------
    # Check for unresolved conditional references
    # ------------------------------------------------------------------
    all_cond_refs = []
    for key, resource in state.items():
        cond_refs = find_conditional_refs(resource)
        all_cond_refs.extend([(key, path, ref) for path, ref in cond_refs])

    if all_cond_refs:
        locations = "; ".join(f"{r}:{p}={ref}" for r, p, ref in all_cond_refs[:3])
        violations.append({
            "category": "conditional_reference",
            "description": (
                f"Conditional references (Type?search=value) in resource content were "
                f"not resolved (at {locations}). Per FHIR R5 section 3.2.0.11.4.1, "
                "the server SHALL resolve conditional references by performing the "
                "implied search against server state and replacing with a direct "
                "reference to the matched resource."
            ),
            "severity": "error"
        })

    # ------------------------------------------------------------------
    # Check conditional create handling (ifNoneExist)
    # ------------------------------------------------------------------
    for i, inp_entry in enumerate(input_entries):
        if_none_exist = inp_entry.get("request", {}).get("ifNoneExist", "")
        method = inp_entry.get("request", {}).get("method", "").upper()
        if method == "POST" and if_none_exist:
            resource_type = inp_entry.get("resource", {}).get("resourceType", "")
            # Check if there's a matching resource in initial state
            params = {}
            for part in if_none_exist.split("&"):
                if "=" in part:
                    k, v = part.split("=", 1)
                    params[k] = v

            initial_matches = []
            for key, resource in initial_state.items():
                if not key.startswith(f"{resource_type}/"):
                    continue
                match = True
                for pk, pv in params.items():
                    if pk == "patient":
                        if resource.get("patient", {}).get("reference", "") != pv:
                            match = False
                            break
                    elif pk == "code":
                        if "|" in pv:
                            sys, code = pv.split("|", 1)
                            codings = resource.get("code", {}).get("coding", [])
                            found = any(
                                c.get("system") == sys and c.get("code") == code
                                for c in codings
                            )
                            if not found:
                                match = False
                                break
                if match:
                    initial_matches.append(resource)

            if len(initial_matches) == 1:
                # There IS a matching resource - the conditional create should skip
                existing = initial_matches[0]
                existing_key = f"{existing['resourceType']}/{existing['id']}"

                # Check if the processor created a duplicate
                output_count = sum(
                    1 for k in state
                    if k.startswith(f"{resource_type}/")
                    and _resource_matches_type_criteria(state[k], resource_type, params)
                )
                if output_count > 1:
                    violations.append({
                        "category": "conditional_create",
                        "description": (
                            f"Conditional create (ifNoneExist) for {resource_type} with "
                            f"criteria '{if_none_exist}' matched existing resource "
                            f"{existing_key}, but the processor created a duplicate "
                            f"resource instead of returning the existing one. Per FHIR R5 "
                            "section 3.2.0.8.1, if a single match is found, the server "
                            "should return 200 OK with the existing resource."
                        ),
                        "severity": "error"
                    })

                # Check response status code
                if i < len(entries):
                    status = entries[i].get("response", {}).get("status", "")
                    if "200" not in status and "201" in status:
                        violations.append({
                            "category": "conditional_create",
                            "description": (
                                f"Conditional create for {resource_type} that matched "
                                f"existing resource {existing_key} returned '{status}' "
                                "instead of '200 OK'. When ifNoneExist matches an existing "
                                "resource, the status should be 200, not 201."
                            ),
                            "severity": "error"
                        })

    # ------------------------------------------------------------------
    # Check PUT versioning
    # ------------------------------------------------------------------
    for i, inp_entry in enumerate(input_entries):
        method = inp_entry.get("request", {}).get("method", "").upper()
        if method == "PUT":
            url = inp_entry.get("request", {}).get("url", "")
            if url in initial_state and url in state:
                old_version = int(
                    initial_state[url].get("meta", {}).get("versionId", "0")
                )
                new_version = int(
                    state[url].get("meta", {}).get("versionId", "0")
                )
                if new_version <= old_version:
                    violations.append({
                        "category": "versioning",
                        "description": (
                            f"PUT update to {url}: versionId was not incremented "
                            f"(old: {old_version}, new: {new_version}). Per FHIR R5 "
                            "section 3.2.0.4, meta.versionId SHALL be incremented from "
                            "the current version when a resource is updated."
                        ),
                        "severity": "error"
                    })

                last_updated = state[url].get("meta", {}).get("lastUpdated")
                if not last_updated:
                    violations.append({
                        "category": "versioning",
                        "description": (
                            f"PUT update to {url}: meta.lastUpdated was not set. Per "
                            "FHIR R5 section 3.2.0.4, the server SHALL update "
                            "meta.lastUpdated to reflect the time of the operation."
                        ),
                        "severity": "error"
                    })

    return violations


def _resource_matches_type_criteria(resource, resource_type, params):
    """Check if a resource matches type and search criteria."""
    if resource.get("resourceType") != resource_type:
        return False
    for pk, pv in params.items():
        if pk == "patient":
            if resource.get("patient", {}).get("reference", "") != pv:
                return False
        elif pk == "code":
            if "|" in pv:
                sys, code = pv.split("|", 1)
                codings = resource.get("code", {}).get("coding", [])
                found = any(
                    c.get("system") == sys and c.get("code") == code
                    for c in codings
                )
                if not found:
                    return False
    return True


def main():
    input_bundle = "/app/data/transaction_bundle.json"
    initial_state = "/app/data/server_state"

    violations_a = evaluate_processor("/app/output_a", input_bundle, initial_state)
    violations_b = evaluate_processor("/app/output_b", input_bundle, initial_state)
    violations_c = evaluate_processor("/app/output_c", input_bundle, initial_state)

    def score(violations):
        error_count = len([v for v in violations if v["severity"] == "error"])
        warning_count = len([v for v in violations if v["severity"] == "warning"])
        return max(0, 100 - error_count * 15 - warning_count * 5)

    score_a = score(violations_a)
    score_b = score(violations_b)
    score_c = score(violations_c)

    scores = {"processor_a": score_a, "processor_b": score_b, "processor_c": score_c}
    superior = max(scores, key=scores.get)

    report = {
        "processor_a": {
            "violations": violations_a,
            "conformance_score": score_a
        },
        "processor_b": {
            "violations": violations_b,
            "conformance_score": score_b
        },
        "processor_c": {
            "violations": violations_c,
            "conformance_score": score_c
        },
        "comparative_analysis": {
            "superior_implementation": superior,
            "architectural_strengths": {
                "processor_a": [
                    "Simple, flat procedural code structure that is easy to read and audit",
                    "Straightforward sequential processing model with minimal abstraction"
                ],
                "processor_b": [
                    "Correct phased operation ordering (DELETE then POST then PUT) per FHIR R5 section 3.2.0.11",
                    "Recursive reference resolution that correctly traverses extensions and nested structures",
                    "Correct HTTP 204 No Content status code for DELETE operations",
                    "Clean class-based architecture with separated handler methods"
                ],
                "processor_c": [
                    "Pre-assigned identity mapping that resolves circular urn:uuid references between entries",
                    "Correct phased operation ordering with proper DELETE/POST/PUT sequencing",
                    "Recursive reference resolution covering all nested structures",
                    "Correct HTTP status codes for all standard operations",
                    "Correct versionId increment and lastUpdated on PUT operations",
                    "Partial conditional create (ifNoneExist) support with server state search"
                ]
            },
            "recommendation": (
                "Processor C provides the strongest foundation with pre-assigned identity "
                "mapping (resolving circular references that B fails on), correct operation "
                "ordering, proper versioning, and partial conditional create support. However, "
                "it has a critical conformance gap: when a conditional create matches an existing "
                "resource, it fails to map the entry's urn:uuid to the existing resource's identity, "
                "causing downstream reference breakage in entries that depend on the conditional "
                "create. It also does not resolve conditional references (Type?search=value). "
                "Processor B has correct operation ordering and recursive resolution but lacks "
                "pre-assigned IDs (breaking forward/circular references), omits meta.lastUpdated "
                "on PUT, and ignores conditional operations entirely. Processor A has the most "
                "fundamental issues including shallow reference resolution, no operation ordering, "
                "incorrect DELETE status codes, and version management failures."
            )
        }
    }

    with open("/app/conformance_report.json", "w") as f:
        json.dump(report, f, indent=2)

    print("Conformance report written to /app/conformance_report.json")
    print(f"  Processor A: {len(violations_a)} violations, score {score_a}")
    print(f"  Processor B: {len(violations_b)} violations, score {score_b}")
    print(f"  Processor C: {len(violations_c)} violations, score {score_c}")
    print(f"  Superior: {superior}")


if __name__ == "__main__":
    main()
