/*
 * gmpb.c — Generalized Moving Peaks Benchmark
 *
 * C implementation of a dynamic fitness landscape with shifting peaks.
 * Reference: Yazdani et al., "Competition on Dynamic Optimization Problems
 * Generated by Generalized Moving Peaks Benchmark (GMPB)," arXiv:2106.06174.
 *
 * Build:  gcc -O2 -fPIC -Wall -shared -o libgmpb.so src/gmpb.c -lm
 */

#include "gmpb.h"
#include <stdlib.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

#define MAX_DIM 64

/* ── SplitMix64 PRNG ─────────────────────────────────────────────────── */

typedef struct { uint64_t state; } splitmix64_t;

static uint64_t sm64_next(splitmix64_t *rng) {
    uint64_t z = (rng->state += 0x9e3779b97f4a7c15ULL);
    z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ULL;
    z = (z ^ (z >> 27)) * 0x94d049bb133111ebULL;
    return z ^ (z >> 31);
}

static double sm64_uniform(splitmix64_t *rng) {
    return (sm64_next(rng) >> 11) * (1.0 / 9007199254740992.0);
}

static double sm64_uniform_range(splitmix64_t *rng, double lo, double hi) {
    return lo + sm64_uniform(rng) * (hi - lo);
}

static double sm64_normal(splitmix64_t *rng) {
    double u1, u2;
    do { u1 = sm64_uniform(rng); } while (u1 < 1e-15);
    u2 = sm64_uniform(rng);
    return sqrt(-2.0 * log(u1)) * cos(2.0 * M_PI * u2);
}

/* ── Context definition ───────────────────────────────────────────────── */

struct GMPBContext {
    int num_peaks;
    int dimension;
    int change_frequency;
    double shift_severity;
    int num_environments;
    double *heights;
    double *centers;
    double *widths;
    double *velocities;
    double height_range[2];
    double width_range[2];
    double height_severity;
    double width_severity;
    double bounds[2];
    double correlation;
    splitmix64_t rng;
};

/* ── Lifecycle ─────────────────────────────────────────────────────────── */

void gmpb_destroy(GMPBContext *ctx) {
    if (!ctx) return;
    free(ctx->heights);
    free(ctx->centers);
    free(ctx->widths);
    free(ctx->velocities);
    free(ctx);
}

GMPBContext *gmpb_create(int num_peaks, int dimension, int change_frequency,
                         double shift_severity, int num_environments,
                         uint64_t seed) {
    if (dimension > MAX_DIM || dimension < 1 || num_peaks < 1) return NULL;

    GMPBContext *ctx = (GMPBContext *)calloc(1, sizeof(GMPBContext));
    if (!ctx) return NULL;

    ctx->num_peaks       = num_peaks;
    ctx->dimension       = dimension;
    ctx->change_frequency = change_frequency;
    ctx->shift_severity  = shift_severity;
    ctx->num_environments = num_environments;

    ctx->height_range[0] = 30.0;  ctx->height_range[1] = 70.0;
    ctx->width_range[0]  = 0.001; ctx->width_range[1]  = 0.01;
    ctx->height_severity = 7.0;
    ctx->width_severity  = 0.001;
    ctx->bounds[0] = 0.0;  ctx->bounds[1] = 100.0;
    ctx->correlation = 0.5;

    ctx->rng.state = seed;

    int np = num_peaks, d = dimension;
    ctx->heights    = (double *)malloc(np * sizeof(double));
    ctx->centers    = (double *)malloc(np * d * sizeof(double));
    ctx->widths     = (double *)malloc(np * sizeof(double));
    ctx->velocities = (double *)calloc(np * d, sizeof(double));

    if (!ctx->heights || !ctx->centers || !ctx->widths || !ctx->velocities) {
        gmpb_destroy(ctx);
        return NULL;
    }

    for (int i = 0; i < np; i++) {
        ctx->heights[i] = sm64_uniform_range(&ctx->rng, 30.0, 70.0);
        ctx->widths[i]  = sm64_uniform_range(&ctx->rng, 0.001, 0.01);
        for (int j = 0; j < d; j++)
            ctx->centers[i * d + j] = sm64_uniform_range(&ctx->rng, 0.0, 100.0);
    }

    return ctx;
}

/* ── Evaluation ────────────────────────────────────────────────────────── */

double gmpb_evaluate(GMPBContext *ctx, const double *x) {
    double best = -1e300;
    int d = ctx->dimension;

    for (int i = 0; i < ctx->num_peaks; i++) {
        double r_sq = 0.0;
        for (int j = 0; j < d; j++) {
            double diff = x[j] - ctx->centers[i * d + j];
            r_sq += diff * diff;
        }
        double val = ctx->heights[i] / (1.0 + ctx->widths[i] * r_sq);
        if (val > best) best = val;
    }
    return best;
}

double gmpb_get_optimum(GMPBContext *ctx, double *pos) {
    int best_idx = 0;
    for (int i = 1; i < ctx->num_peaks; i++) {
        if (ctx->heights[i] > ctx->heights[best_idx])
            best_idx = i;
    }
    if (pos)
        memcpy(pos, &ctx->centers[best_idx * ctx->dimension],
               ctx->dimension * sizeof(double));
    return ctx->heights[best_idx];
}

/* ── Dynamics ──────────────────────────────────────────────────────────── */

void gmpb_trigger_change(GMPBContext *ctx) {
    int d = ctx->dimension;
    double lb = ctx->bounds[0], ub = ctx->bounds[1];
    double lam = ctx->correlation;

    for (int i = 0; i < ctx->num_peaks; i++) {
        double r[MAX_DIM], combined[MAX_DIM];

        for (int j = 0; j < d; j++)
            r[j] = sm64_normal(&ctx->rng);

        double norm = 0.0;
        for (int j = 0; j < d; j++) {
            combined[j] = lam * r[j] + (1.0 - lam) * ctx->velocities[i * d + j];
            norm += combined[j] * combined[j];
        }
        norm = sqrt(norm);

        if (norm > 1e-10) {
            for (int j = 0; j < d; j++)
                ctx->velocities[i * d + j] = ctx->shift_severity * combined[j] / norm;
        } else {
            double rn = 0.0;
            for (int j = 0; j < d; j++) rn += r[j] * r[j];
            rn = sqrt(rn) + 1e-10;
            for (int j = 0; j < d; j++)
                ctx->velocities[i * d + j] = ctx->shift_severity * r[j] / rn;
        }

        for (int j = 0; j < d; j++) {
            double c = ctx->centers[i * d + j] + ctx->velocities[i * d + j];
            int guard = 100;
            while ((c < lb || c > ub) && guard-- > 0) {
                if (c < lb) c = 2.0 * lb - c;
                if (c > ub) c = 2.0 * ub - c;
            }
            if (c < lb) c = lb;
            if (c > ub) c = ub;
            ctx->centers[i * d + j] = c;
        }

        double h = ctx->heights[i] + ctx->height_severity * sm64_normal(&ctx->rng);
        if (h < ctx->height_range[0]) h = ctx->height_range[0];
        if (h > ctx->height_range[1]) h = ctx->height_range[1];
        ctx->heights[i] = h;

        double w = ctx->widths[i] + ctx->width_severity * sm64_normal(&ctx->rng);
        if (w < ctx->width_range[0]) w = ctx->width_range[0];
        if (w > ctx->width_range[1]) w = ctx->width_range[1];
        ctx->widths[i] = w;
    }
}

/* ── Accessors ─────────────────────────────────────────────────────────── */

int gmpb_total_evaluations(GMPBContext *ctx) {
    return ctx->change_frequency * ctx->num_environments;
}
int gmpb_change_frequency(GMPBContext *ctx) { return ctx->change_frequency; }
int gmpb_dimension(GMPBContext *ctx)        { return ctx->dimension; }
int gmpb_num_environments(GMPBContext *ctx) { return ctx->num_environments; }
int gmpb_num_peaks(GMPBContext *ctx)        { return ctx->num_peaks; }
