"""LABS symmetry operations and canonical form."""


def negate(s):
    """Return negation of sequence: s -> -s."""
    return [-x for x in s]


def reverse_seq(s):
    """Return reversal of sequence."""
    return list(reversed(s))


def alternating_inversion(s):
    """Return alternating inversion: s'[i] = (-1)^i * s[i]."""
    return [s[i] * ((-1) ** i) for i in range(len(s))]


def canonical_form(s):
    """Return lexicographically smallest equivalent sequence under all symmetries.

    The symmetry group is generated by negation, reversal, and alternating
    inversion, producing up to 8 equivalent sequences.
    """
    neg = negate(s)
    rev = reverse_seq(s)
    neg_rev = negate(rev)
    alt = alternating_inversion(s)
    neg_alt = negate(alt)
    rev_alt = reverse_seq(alt)
    neg_rev_alt = negate(rev_alt)

    candidates = [s, neg, rev, neg_rev, alt, neg_alt, rev_alt, neg_rev_alt]
    return min(tuple(c) for c in candidates)
