CC = gcc
CFLAGS = -Wall -Werror -O2 -std=gnu11 -fno-strict-aliasing -I.
LDFLAGS =

TARGET = xv6-fsck

.PHONY: all clean

all: $(TARGET)

# Add your build rule(s) for $(TARGET) here.
# Your C source file(s) should compile into the $(TARGET) ELF binary.
# The fs_spec.h header is available for #include via the -I. flag above.

clean:
	rm -f $(TARGET) *.o
