#!/usr/bin/env python3
"""Generate configuration header for the netmon library.

This script produces a C header with version information and build
metadata, suitable for inclusion in both C and C++ translation units.
"""
import argparse
import os
import sys
import hashlib


def generate_config(output_path, version):
    """Generate the configuration header file."""
    parts = version.split('.')
    if len(parts) != 3:
        print(f"Error: version must be MAJOR.MINOR.PATCH, got '{version}'",
              file=sys.stderr)
        sys.exit(1)

    major, minor, patch = parts
    version_hash = hashlib.sha256(version.encode()).hexdigest()[:8]

    content = f"""/* Auto-generated by codegen.py - DO NOT EDIT */
#ifndef NETMON_GENERATED_CONFIG_H
#define NETMON_GENERATED_CONFIG_H

#define NETMON_VERSION_MAJOR {major}
#define NETMON_VERSION_MINOR {minor}
#define NETMON_VERSION_PATCH {patch}
#define NETMON_VERSION_STRING "{major}.{minor:02d}.{patch}"
#define NETMON_VERSION_HEX 0x{major:02x}{minor:02x}{patch:02x}
#define NETMON_BUILD_HASH "{version_hash}"

#endif /* NETMON_GENERATED_CONFIG_H */
"""

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(content)

    print(f"Generated {output_path}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Generate netmon configuration header')
    parser.add_argument('--output', required=True,
                        help='Output header file path')
    parser.add_argument('--version', required=True,
                        help='Version string (MAJOR.MINOR.PATCH)')
    args = parser.parse_args()
    generate_config(args.output, args.version)
