#!/usr/bin/env python3

"""
NCL Reachability Solver with Invariant Certificates, SMT-LIB2 Proofs,
and Graphviz DOT/SVG Visualization.

Solves NCL edge-reversal reachability via BFS over valid configurations.
For unreachable instances, extracts fixed-edge inductive invariants and
generates standalone SMT-LIB2 proof scripts verifiable by the Z3 theorem
prover. Generates Graphviz DOT files and renders them to SVG.
"""

import json
import os
import subprocess
from collections import deque


def load_instance(filepath):
    with open(filepath) as f:
        return json.load(f)


def compute_inflow(vertices, edges, orientation):
    inflow = {v: 0 for v in vertices}
    for eid, edata in edges.items():
        target = orientation[eid]
        inflow[target] += edata["weight"]
    return inflow


def is_valid(vertices, edges, orientation):
    inflow = compute_inflow(vertices, edges, orientation)
    return all(
        inflow[v] >= vdata["min_inflow"]
        for v, vdata in vertices.items()
    )


def other_endpoint(edges, eid, current_target):
    ep = edges[eid]["endpoints"]
    return ep[1] if current_target == ep[0] else ep[0]


def orientation_to_key(orientation, edge_ids):
    return tuple(orientation[eid] for eid in edge_ids)


def key_to_orientation(key, edge_ids):
    return {eid: key[i] for i, eid in enumerate(edge_ids)}


def solve_instance(instance):
    """BFS over valid NCL configurations."""
    vertices = instance["vertices"]
    edges = instance["edges"]
    initial = instance["initial_orientation"]
    target_edge = instance["target_edge"]
    target_dir = instance["target_direction"]
    edge_ids = sorted(edges.keys())

    start_key = orientation_to_key(initial, edge_ids)

    if initial[target_edge] == target_dir:
        return {"reachable": True, "path": []}, {start_key}

    queue = deque([(start_key, [])])
    visited = {start_key}

    while queue:
        state_key, path = queue.popleft()
        orientation = key_to_orientation(state_key, edge_ids)

        for eid in edge_ids:
            new_orientation = dict(orientation)
            new_target = other_endpoint(edges, eid, orientation[eid])
            new_orientation[eid] = new_target

            if is_valid(vertices, edges, new_orientation):
                new_key = orientation_to_key(new_orientation, edge_ids)
                new_path = path + [eid]

                if new_orientation[target_edge] == target_dir:
                    return {"reachable": True, "path": new_path}, visited

                if new_key not in visited:
                    visited.add(new_key)
                    queue.append((new_key, new_path))

    return {"reachable": False, "path": None}, visited


def find_invariant(instance, visited, edge_ids):
    """Extract edges fixed across ALL reachable configurations."""
    initial = instance["initial_orientation"]
    fixed = {}

    for idx, eid in enumerate(edge_ids):
        directions = {cfg[idx] for cfg in visited}
        if len(directions) == 1:
            fixed[eid] = initial[eid]

    target = instance["target_edge"]
    target_dir = instance["target_direction"]
    if target in fixed and fixed[target] != target_dir:
        return {"fixed_edges": fixed}
    return None


def generate_smt2(instance, invariant, name):
    """Generate SMT-LIB2 proof script for invariant verification.

    Encodes the NCL constraint graph in QF_LIA logic. Edge orientations
    are modeled as integer variables (0 = toward endpoints[0], 1 = toward
    endpoints[1]). Vertex inflow constraints are expressed as linear
    arithmetic inequalities. The script proves inductiveness (no fixed
    edge can be legally reversed) and target exclusion via (check-sat)
    calls that must all return unsat.
    """
    edges = instance["edges"]
    vertices = instance["vertices"]
    fixed = invariant["fixed_edges"]
    edge_ids = sorted(edges.keys())

    lines = []
    lines.append(f"; NCL Inductive Invariant Proof: {name}")
    lines.append("; Generated by NCL solver")
    lines.append("(set-logic QF_LIA)")
    lines.append("")

    # Declare edge orientation variables
    lines.append("; Edge orientation variables")
    lines.append("; Convention: 0 = toward endpoints[0], 1 = toward endpoints[1]")
    for eid in edge_ids:
        ep = edges[eid]["endpoints"]
        lines.append(f"(declare-const {eid} Int) ; {ep[0]}-{ep[1]} w={edges[eid]['weight']}")
    lines.append("")

    # Range constraints
    lines.append("; Range constraints (binary orientation)")
    for eid in edge_ids:
        lines.append(f"(assert (and (>= {eid} 0) (<= {eid} 1)))")
    lines.append("")

    def inflow_expr(vid, edge_var_map=None):
        """Build SMT-LIB2 inflow expression for vertex vid."""
        if edge_var_map is None:
            edge_var_map = {}
        terms = []
        for eid, edata in edges.items():
            ep = edata["endpoints"]
            w = edata["weight"]
            var = edge_var_map.get(eid, eid)
            if vid == ep[0]:
                terms.append(f"(* (- 1 {var}) {w})")
            elif vid == ep[1]:
                terms.append(f"(* {var} {w})")
        if not terms:
            return "0"
        if len(terms) == 1:
            return terms[0]
        return "(+ " + " ".join(terms) + ")"

    # Valid configuration constraints (pre-state)
    lines.append("; Valid configuration: vertex inflow >= min_inflow")
    for vid in sorted(vertices.keys()):
        vdata = vertices[vid]
        expr = inflow_expr(vid)
        lines.append(f"(assert (>= {expr} {vdata['min_inflow']})) ; {vid}")
    lines.append("")

    # Fixed edge constraints
    lines.append("; Fixed edge constraints (invariant)")
    for eid in sorted(fixed.keys()):
        direction = fixed[eid]
        ep = edges[eid]["endpoints"]
        val = 0 if direction == ep[0] else 1
        lines.append(f"(assert (= {eid} {val})) ; {eid} -> {direction}")
    lines.append("")

    # Inductiveness checks
    for eid_check in sorted(fixed.keys()):
        direction = fixed[eid_check]
        ep = edges[eid_check]["endpoints"]
        other_dir = ep[1] if direction == ep[0] else ep[0]
        lines.append(
            f"; --- Inductiveness: {eid_check} cannot reverse "
            f"({direction} -> {other_dir}) ---"
        )
        lines.append("(push 1)")

        post_var = f"{eid_check}_post"
        lines.append(f"(declare-const {post_var} Int)")
        lines.append(f"(assert (= {post_var} (- 1 {eid_check})))")

        var_map = {eid_check: post_var}
        for vid in sorted(vertices.keys()):
            vdata = vertices[vid]
            expr = inflow_expr(vid, var_map)
            lines.append(
                f"(assert (>= {expr} {vdata['min_inflow']})) ; post {vid}"
            )

        lines.append("(check-sat) ; expect unsat")
        lines.append("(pop 1)")
        lines.append("")

    # Target exclusion
    target_edge = instance["target_edge"]
    target_dir = instance["target_direction"]
    ep = edges[target_edge]["endpoints"]
    target_val = 0 if target_dir == ep[0] else 1
    lines.append(
        f"; --- Target exclusion: {target_edge} cannot reach "
        f"direction {target_dir} ---"
    )
    lines.append("(push 1)")
    lines.append(f"(assert (= {target_edge} {target_val}))")
    lines.append("(check-sat) ; expect unsat")
    lines.append("(pop 1)")

    return "\n".join(lines) + "\n"


def generate_dot(instance, name):
    """Generate Graphviz DOT visualization of the constraint graph."""
    vertices = instance["vertices"]
    edges = instance["edges"]
    initial = instance["initial_orientation"]

    lines = [f"digraph {name} {{"]
    lines.append("    rankdir=LR;")
    lines.append(
        "    node [shape=circle, style=filled, fillcolor=lightyellow];"
    )

    for vid, vdata in sorted(vertices.items()):
        label = f"{vid}\\nmin={vdata['min_inflow']}"
        lines.append(f'    {vid} [label="{label}"];')

    for eid, edata in sorted(edges.items()):
        u, v = edata["endpoints"]
        w = edata["weight"]
        color = "red" if w == 1 else "blue"
        target = initial[eid]
        source = v if target == u else u
        label = f"{eid} (w={w})"
        lines.append(
            f'    {source} -> {target} '
            f'[label="{label}", color={color}, penwidth=2];'
        )

    lines.append("}")
    return "\n".join(lines)


def render_svg(dot_path, svg_path):
    """Render DOT file to SVG using graphviz dot command."""
    result = subprocess.run(
        ["dot", "-Tsvg", dot_path, "-o", svg_path],
        capture_output=True, text=True, timeout=30
    )
    if result.returncode != 0:
        print(f"  WARNING: SVG render failed for {dot_path}: {result.stderr}")
    return result.returncode == 0


def main():
    instances_dir = "/app/instances"
    results = {}

    os.makedirs("/app/invariants", exist_ok=True)
    os.makedirs("/app/proofs", exist_ok=True)
    os.makedirs("/app/graphs", exist_ok=True)

    for filename in sorted(os.listdir(instances_dir)):
        if not filename.endswith(".json"):
            continue

        name = filename[:-5]
        filepath = os.path.join(instances_dir, filename)
        instance = load_instance(filepath)
        edge_ids = sorted(instance["edges"].keys())

        result, visited = solve_instance(instance)
        results[name] = result

        if not result["reachable"]:
            invariant = find_invariant(instance, visited, edge_ids)
            if invariant:
                # Write JSON invariant certificate
                inv_path = f"/app/invariants/{name}.json"
                with open(inv_path, "w") as f:
                    json.dump(invariant, f, indent=2)

                # Generate SMT-LIB2 proof script
                smt2 = generate_smt2(instance, invariant, name)
                smt2_path = f"/app/proofs/{name}.smt2"
                with open(smt2_path, "w") as f:
                    f.write(smt2)

                # Verify with z3 if available
                try:
                    z3_result = subprocess.run(
                        ["z3", smt2_path],
                        capture_output=True, text=True, timeout=60
                    )
                    z3_lines = z3_result.stdout.strip().split("\n")
                    all_unsat = all(l.strip() == "unsat" for l in z3_lines if l.strip())
                    status = "VERIFIED" if all_unsat else "FAILED"
                except (FileNotFoundError, subprocess.TimeoutExpired):
                    status = "z3 unavailable"

                fixed_list = list(invariant["fixed_edges"].keys())
                print(f"  {name}: UNREACHABLE (fixed: {fixed_list}, proof: {status})")
            else:
                print(f"  {name}: UNREACHABLE (no invariant found)")
        else:
            path_len = len(result["path"]) if result["path"] else 0
            print(f"  {name}: REACHABLE ({path_len} steps)")

        # Generate DOT and SVG
        dot = generate_dot(instance, name)
        dot_path = f"/app/graphs/{name}.dot"
        with open(dot_path, "w") as f:
            f.write(dot)

        svg_path = f"/app/graphs/{name}.svg"
        render_svg(dot_path, svg_path)

    with open("/app/results.json", "w") as f:
        json.dump(results, f, indent=2)

    print(f"\nResults written to /app/results.json")
    print(f"Invariants written to /app/invariants/")
    print(f"Proofs written to /app/proofs/")
    print(f"Graphs written to /app/graphs/")


if __name__ == "__main__":
    main()
