"""
Tests for the Cargo workspace feature audit pipeline.

"""

import json
import os


# --- Reference data for verification ---

MAIN_FEATURES = {
    "default": ["acpi", "dhcpv4", "fsgsbase", "pci", "smp", "tcp", "virtio-fs", "virtio-net"],
    "acpi": [],
    "fsgsbase": [],
    "smp": ["acpi"],
    "pci": ["virtio-spec?/pci"],
    "net": [],
    "tcp": ["net", "dep:net-stack", "net-stack?/socket-tcp"],
    "udp": ["net", "dep:net-stack", "net-stack?/socket-udp"],
    "dhcpv4": ["net", "dep:net-stack", "net-stack?/proto-dhcpv4", "net-stack?/socket-dhcpv4"],
    "dns": ["net", "dep:net-stack", "net-stack?/socket-dns"],
    "virtio-net": ["net", "dep:virtio-spec"],
    "rtl8139": ["net", "pci"],
    "gem-net": ["net", "dep:hw-regs"],
    "virtio-console": ["dep:virtio-spec"],
    "virtio-fs": ["dep:virtio-spec", "dep:fuse-proto", "fuse-proto?/linux"],
    "virtio-vsock": ["dep:virtio-spec"],
    "shell": ["debug-shell"],
    "net-trace": ["net-stack?/verbose"],
    "idle-poll": [],
    "alloc-stats": [],
    "strace": [],
    "console": ["virtio-console"],
    "fs": ["virtio-fs"],
    # Implicit feature (auto-generated by Cargo)
    "debug-shell": ["dep:debug-shell"],
}

DEP_INFO = {
    "net-stack": {"uses_default_features": False},
    "virtio-spec": {"uses_default_features": False},
    "fuse-proto": {"uses_default_features": True},
    "hw-regs": {"uses_default_features": False},
    "debug-shell": {"uses_default_features": True},
}

DEP_FEATURES = {
    "net-stack": {
        "default": ["alloc", "medium-ethernet"],
        "alloc": [],
        "medium-ethernet": [],
        "socket-tcp": ["alloc"],
        "socket-udp": ["alloc"],
        "socket-dns": ["alloc"],
        "proto-dhcpv4": [],
        "socket-dhcpv4": ["alloc", "proto-dhcpv4"],
        "verbose": ["log"],
        "log": [],
    },
    "virtio-spec": {
        "default": ["alloc"],
        "alloc": [],
        "pci": [],
        "mmio": [],
        "nightly": [],
    },
    "fuse-proto": {
        "default": ["num-enum"],
        "linux": [],
        "num-enum": [],
    },
    "hw-regs": {
        "default": ["register-ops"],
        "register-ops": [],
    },
    "debug-shell": {
        "default": ["history"],
        "history": [],
        "completion": ["history"],
    },
}


def _resolve_dep_feats(dep_name, feat, active):
    """Resolve transitive features within a dependency crate."""
    if dep_name not in DEP_FEATURES:
        return
    pkg_feats = DEP_FEATURES[dep_name]
    if feat not in pkg_feats:
        return
    worklist = list(pkg_feats[feat])
    while worklist:
        sub = worklist.pop()
        if sub in active.get(dep_name, set()):
            continue
        active.setdefault(dep_name, set()).add(sub)
        if sub in pkg_feats:
            worklist.extend(pkg_feats[sub])


def reference_resolve(input_features):
    """Independent reference resolver for verifying minimal_set answers."""
    enabled_features = set()
    enabled_deps = set()
    dep_feats = {}

    worklist = list(input_features)

    while worklist:
        item = worklist.pop()
        if item in enabled_features:
            continue
        enabled_features.add(item)

        if item not in MAIN_FEATURES:
            continue

        for spec in MAIN_FEATURES[item]:
            if spec.startswith("dep:"):
                dep_name = spec[4:]
                if dep_name not in enabled_deps:
                    enabled_deps.add(dep_name)
                    if dep_name in DEP_INFO and DEP_INFO[dep_name]["uses_default_features"]:
                        if dep_name in DEP_FEATURES and "default" in DEP_FEATURES[dep_name]:
                            dep_feats.setdefault(dep_name, set()).add("default")
                            _resolve_dep_feats(dep_name, "default", dep_feats)
            elif "?/" in spec:
                dep_name, feat = spec.split("?/", 1)
                if dep_name in enabled_deps:
                    if feat not in dep_feats.get(dep_name, set()):
                        dep_feats.setdefault(dep_name, set()).add(feat)
                        _resolve_dep_feats(dep_name, feat, dep_feats)
            elif "/" in spec:
                dep_name, feat = spec.split("/", 1)
                if dep_name not in enabled_deps:
                    enabled_deps.add(dep_name)
                    if dep_name in DEP_INFO and DEP_INFO[dep_name]["uses_default_features"]:
                        if dep_name in DEP_FEATURES and "default" in DEP_FEATURES[dep_name]:
                            dep_feats.setdefault(dep_name, set()).add("default")
                            _resolve_dep_feats(dep_name, "default", dep_feats)
                if feat not in dep_feats.get(dep_name, set()):
                    dep_feats.setdefault(dep_name, set()).add(feat)
                    _resolve_dep_feats(dep_name, feat, dep_feats)
            else:
                if spec not in enabled_features:
                    worklist.append(spec)

    # Fixed-point for weak deps
    changed = True
    while changed:
        changed = False
        for feat in list(enabled_features):
            if feat not in MAIN_FEATURES:
                continue
            for spec in MAIN_FEATURES[feat]:
                if "?/" in spec:
                    dep_name, feat_name = spec.split("?/", 1)
                    if dep_name in enabled_deps:
                        if feat_name not in dep_feats.get(dep_name, set()):
                            dep_feats.setdefault(dep_name, set()).add(feat_name)
                            _resolve_dep_feats(dep_name, feat_name, dep_feats)
                            changed = True

    result = set()
    result.update(enabled_features)
    result.update(enabled_deps)
    for dn, fs in dep_feats.items():
        for f in fs:
            result.add(f"{dn}/{f}")

    return sorted(result)


# --- Expected answers ---

EXPECTED_RESOLVE = {
    1: ["net", "net-stack", "net-stack/alloc", "net-stack/socket-tcp", "tcp"],
    2: ["pci"],
    3: ["net", "pci", "virtio-net", "virtio-spec", "virtio-spec/pci"],
    4: [
        "acpi", "default", "dhcpv4", "fsgsbase",
        "fuse-proto", "fuse-proto/default", "fuse-proto/linux", "fuse-proto/num-enum",
        "net", "net-stack", "net-stack/alloc", "net-stack/proto-dhcpv4",
        "net-stack/socket-dhcpv4", "net-stack/socket-tcp",
        "pci", "smp", "tcp", "virtio-fs", "virtio-net",
        "virtio-spec", "virtio-spec/pci",
    ],
    5: ["net-trace"],
    6: [
        "net", "net-stack", "net-stack/alloc", "net-stack/log",
        "net-stack/socket-tcp", "net-stack/verbose", "net-trace", "tcp",
    ],
    7: ["net", "pci", "rtl8139"],
    8: ["console", "virtio-console", "virtio-spec"],
    9: [
        "fs", "fuse-proto", "fuse-proto/default", "fuse-proto/linux",
        "fuse-proto/num-enum", "pci", "virtio-fs", "virtio-spec", "virtio-spec/pci",
    ],
    10: [
        "dns", "gem-net", "hw-regs", "net", "net-stack", "net-stack/alloc",
        "net-stack/socket-dns", "pci", "virtio-console", "virtio-spec", "virtio-spec/pci",
    ],
    11: ["debug-shell", "debug-shell/default", "debug-shell/history", "shell"],
    12: ["debug-shell", "debug-shell/default", "debug-shell/history"],
}

EXPECTED_IMPLICIT = {
    13: ["debug-shell"],
}

EXPECTED_REVERSE_DEPS = {
    14: ["default", "dhcpv4", "dns", "gem-net", "rtl8139", "tcp", "udp", "virtio-net"],
    15: ["console", "default", "fs", "virtio-console", "virtio-fs", "virtio-net", "virtio-vsock"],
    16: ["default", "dhcpv4", "dns", "tcp", "udp"],
    17: ["debug-shell", "shell"],
}

EXPECTED_FEATURE_DIFF = {
    18: {
        "only_a": ["net-stack/socket-tcp", "tcp"],
        "only_b": ["net-stack/socket-udp", "udp"],
    },
    19: {
        "only_a": ["debug-shell", "debug-shell/default", "debug-shell/history", "shell"],
        "only_b": ["virtio-console", "virtio-spec"],
    },
}

EXPECTED_MINIMAL_SIZES = {
    20: 1,
    21: 2,
    22: 4,
}

MINIMAL_SET_REQUIRED = {
    20: ["net", "virtio-spec/pci", "net-stack/socket-tcp"],
    21: ["net-stack/socket-udp", "fuse-proto/linux", "virtio-spec/pci"],
    22: ["net-stack/socket-udp", "net-stack/socket-dns", "hw-regs", "debug-shell/history"],
}


class TestResults:
    @classmethod
    def setup_class(cls):
        with open("/app/results.json") as f:
            results_list = json.load(f)
        cls.results = {r["id"]: r["result"] for r in results_list}

    def test_results_file_exists(self):
        assert os.path.exists("/app/results.json"), "results.json not found"

    def test_all_queries_answered(self):
        for qid in range(1, 23):
            assert qid in self.results, f"Missing result for query {qid}"

    # --- Resolve queries (exact match) ---

    def test_resolve_q1_tcp(self):
        assert self.results[1] == EXPECTED_RESOLVE[1], (
            f"Q1 wrong.\nExpected: {EXPECTED_RESOLVE[1]}\nGot: {self.results[1]}"
        )

    def test_resolve_q2_pci(self):
        assert self.results[2] == EXPECTED_RESOLVE[2], (
            f"Q2 wrong.\nExpected: {EXPECTED_RESOLVE[2]}\nGot: {self.results[2]}"
        )

    def test_resolve_q3_pci_virtio_net(self):
        assert self.results[3] == EXPECTED_RESOLVE[3], (
            f"Q3 wrong.\nExpected: {EXPECTED_RESOLVE[3]}\nGot: {self.results[3]}"
        )

    def test_resolve_q4_default(self):
        assert self.results[4] == EXPECTED_RESOLVE[4], (
            f"Q4 wrong.\nExpected: {EXPECTED_RESOLVE[4]}\nGot: {self.results[4]}"
        )

    def test_resolve_q5_net_trace(self):
        assert self.results[5] == EXPECTED_RESOLVE[5], (
            f"Q5 wrong.\nExpected: {EXPECTED_RESOLVE[5]}\nGot: {self.results[5]}"
        )

    def test_resolve_q6_net_trace_tcp(self):
        assert self.results[6] == EXPECTED_RESOLVE[6], (
            f"Q6 wrong.\nExpected: {EXPECTED_RESOLVE[6]}\nGot: {self.results[6]}"
        )

    def test_resolve_q7_rtl8139(self):
        assert self.results[7] == EXPECTED_RESOLVE[7], (
            f"Q7 wrong.\nExpected: {EXPECTED_RESOLVE[7]}\nGot: {self.results[7]}"
        )

    def test_resolve_q8_console(self):
        assert self.results[8] == EXPECTED_RESOLVE[8], (
            f"Q8 wrong.\nExpected: {EXPECTED_RESOLVE[8]}\nGot: {self.results[8]}"
        )

    def test_resolve_q9_fs_pci(self):
        assert self.results[9] == EXPECTED_RESOLVE[9], (
            f"Q9 wrong.\nExpected: {EXPECTED_RESOLVE[9]}\nGot: {self.results[9]}"
        )

    def test_resolve_q10_complex(self):
        assert self.results[10] == EXPECTED_RESOLVE[10], (
            f"Q10 wrong.\nExpected: {EXPECTED_RESOLVE[10]}\nGot: {self.results[10]}"
        )

    def test_resolve_q11_shell(self):
        assert self.results[11] == EXPECTED_RESOLVE[11], (
            f"Q11 wrong.\nExpected: {EXPECTED_RESOLVE[11]}\nGot: {self.results[11]}"
        )

    def test_resolve_q12_implicit_debug_shell(self):
        assert self.results[12] == EXPECTED_RESOLVE[12], (
            f"Q12 wrong.\nExpected: {EXPECTED_RESOLVE[12]}\nGot: {self.results[12]}"
        )

    # --- Implicit features query ---

    def test_implicit_features_q13(self):
        assert self.results[13] == EXPECTED_IMPLICIT[13], (
            f"Q13 wrong.\nExpected: {EXPECTED_IMPLICIT[13]}\nGot: {self.results[13]}"
        )

    # --- Reverse dependency queries (exact match) ---

    def test_reverse_deps_q14_net(self):
        assert self.results[14] == EXPECTED_REVERSE_DEPS[14], (
            f"Q14 wrong.\nExpected: {EXPECTED_REVERSE_DEPS[14]}\nGot: {self.results[14]}"
        )

    def test_reverse_deps_q15_virtio_spec(self):
        assert self.results[15] == EXPECTED_REVERSE_DEPS[15], (
            f"Q15 wrong.\nExpected: {EXPECTED_REVERSE_DEPS[15]}\nGot: {self.results[15]}"
        )

    def test_reverse_deps_q16_net_stack_alloc(self):
        assert self.results[16] == EXPECTED_REVERSE_DEPS[16], (
            f"Q16 wrong.\nExpected: {EXPECTED_REVERSE_DEPS[16]}\nGot: {self.results[16]}"
        )

    def test_reverse_deps_q17_debug_shell_history(self):
        assert self.results[17] == EXPECTED_REVERSE_DEPS[17], (
            f"Q17 wrong.\nExpected: {EXPECTED_REVERSE_DEPS[17]}\nGot: {self.results[17]}"
        )

    # --- Feature diff queries (exact match) ---

    def test_feature_diff_q18(self):
        assert self.results[18] == EXPECTED_FEATURE_DIFF[18], (
            f"Q18 wrong.\nExpected: {EXPECTED_FEATURE_DIFF[18]}\nGot: {self.results[18]}"
        )

    def test_feature_diff_q19(self):
        assert self.results[19] == EXPECTED_FEATURE_DIFF[19], (
            f"Q19 wrong.\nExpected: {EXPECTED_FEATURE_DIFF[19]}\nGot: {self.results[19]}"
        )

    # --- Minimal set queries (size + correctness) ---

    def _verify_minimal_set(self, qid):
        result = self.results[qid]
        expected_size = EXPECTED_MINIMAL_SIZES[qid]
        required = MINIMAL_SET_REQUIRED[qid]

        assert len(result) == expected_size, (
            f"Q{qid}: expected size {expected_size}, got {len(result)}: {result}"
        )

        for f in result:
            assert f in MAIN_FEATURES, (
                f"Q{qid}: '{f}' is not a valid hyperkernel feature"
            )

        resolved = set(reference_resolve(result))
        for req in required:
            assert req in resolved, (
                f"Q{qid}: required '{req}' not in resolved set of {result}. "
                f"Resolved: {sorted(resolved)}"
            )

    def test_minimal_set_q20(self):
        self._verify_minimal_set(20)

    def test_minimal_set_q21(self):
        self._verify_minimal_set(21)

    def test_minimal_set_q22(self):
        self._verify_minimal_set(22)
