#!/usr/bin/env python3
"""
Hack Assembly Peephole Optimizer.

Implement the optimize_asm function to optimize Hack assembly code
generated by the VM translator. The optimizer must:
1. Preserve functional equivalence (programs produce identical RAM states)
2. Reduce code size (instruction count) by meeting specified targets
3. Preserve all labels (jump targets must remain valid)

The function takes a list of assembly lines and returns an optimized list.
"""


def optimize_asm(lines):
    """Optimize a list of Hack assembly lines.

    Args:
        lines: List of strings, each a Hack assembly line.
               May contain A-instructions (@value), C-instructions (dest=comp;jump),
               labels ((LABEL)), comments (//...), and blank lines.

    Returns:
        List of optimized assembly lines that are functionally equivalent
        to the input but with fewer instructions.
    """
    return list(lines)  # No optimization - implement this
