# DataFlow version compatibility file

set(PACKAGE_VERSION "1.0.0")

if(PACKAGE_FIND_VERSION_RANGE)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
elseif("${PACKAGE_VERSION}" VERSION_LESS "${PACKAGE_FIND_VERSION}")
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if("${PACKAGE_VERSION}" VERSION_EQUAL "${PACKAGE_FIND_VERSION}")
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
