
"""
ROCA vulnerability detector, factorer, and private key deriver.

The ROCA vulnerability (CVE-2017-15361) arises from Infineon's flawed
prime generation: primes p are generated such that p mod q_i lies in
the multiplicative subgroup generated by 65537 modulo q_i, for every
prime q_i dividing M = primorial(71).

Detection: For each odd prime q dividing M, check whether n mod q is
a power of 65537 mod q.

Factoring (for keys with small moduli): Iterate over all elements
r = 65537^a mod M (a = 0..order-1) and test whether r divides n.
When both primes p,q < M, each prime is exactly one of these residues.

Private key derivation: d = e^(-1) mod lcm(p-1, q-1).
"""

import json
import os
import math
import random


def small_primes_up_to(n):
    sieve = [True] * (n + 1)
    sieve[0] = sieve[1] = False
    for i in range(2, int(n**0.5) + 1):
        if sieve[i]:
            for j in range(i * i, n + 1, i):
                sieve[j] = False
    return [i for i in range(2, n + 1) if sieve[i]]


def primorial(bound):
    result = 1
    for p in small_primes_up_to(bound):
        result *= p
    return result


def miller_rabin(n, k=40):
    """Deterministic-quality Miller-Rabin primality test."""
    if n < 2:
        return False
    if n == 2 or n == 3:
        return True
    if n % 2 == 0:
        return False
    # Write n-1 as 2^r * d
    r, d = 0, n - 1
    while d % 2 == 0:
        r += 1
        d //= 2
    # For numbers < 3.3e24, these witnesses are deterministic
    witnesses = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]
    for a in witnesses:
        if a >= n:
            continue
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue
        for _ in range(r - 1):
            x = pow(x, 2, n)
            if x == n - 1:
                break
        else:
            return False
    return True


M = primorial(71)
G = 65537
SMALL_PRIMES = small_primes_up_to(71)

# Bit-size cutoff: only factor ROCA keys with modulus <= this many bits
FACTOR_BIT_LIMIT = 200


def compute_powers_mod(g, p):
    """Compute the set of all powers of g modulo p."""
    powers = set()
    val = 1
    for _ in range(p):
        powers.add(val)
        val = (val * g) % p
        if val == 1:
            break
    return powers


def is_roca_vulnerable(n):
    """Check if n has the ROCA fingerprint.

    For each odd prime q dividing M = primorial(71), verify that
    n mod q lies in the multiplicative subgroup generated by G=65537
    modulo q. If ALL such checks pass, the key is ROCA-vulnerable.
    """
    for p in SMALL_PRIMES:
        if p == 2:
            continue
        powers = compute_powers_mod(G, p)
        if n % p not in powers:
            return False
    return True


def compute_order_mod_prime(g, p):
    """Compute the multiplicative order of g modulo a small prime p."""
    val = g % p
    if val == 0:
        return 0
    order = 1
    current = val
    while current != 1:
        current = (current * val) % p
        order += 1
    return order


def compute_order_mod_primorial():
    """Compute the multiplicative order of G modulo M = primorial(71).

    Uses CRT: order(G, M) = lcm(order(G, p) for each prime p dividing M).
    """
    result = 1
    for p in SMALL_PRIMES:
        o = compute_order_mod_prime(G, p)
        result = math.lcm(result, o)
    return result


ORDER_G_MOD_M = compute_order_mod_primorial()


def factor_roca_key(n):
    """
    Factor a ROCA-vulnerable RSA modulus n where both primes < M.

    Strategy: iterate over all elements r = G^a mod M.
    If r divides n and the quotient is > 1, we found the factors.
    """
    order = ORDER_G_MOD_M
    print(f"  Order of G mod M = {order}")

    val = 1
    for a in range(order):
        if a > 0:
            val = (val * G) % M

        if val < 2:
            continue

        if n % val == 0:
            q = n // val
            if q > 1 and miller_rabin(val) and miller_rabin(q):
                return val, q

    return None, None


def derive_private_key(p, q, e=65537):
    """Compute d = e^(-1) mod lcm(p-1, q-1)."""
    lam = math.lcm(p - 1, q - 1)
    d = pow(e, -1, lam)
    return d


def main():
    os.makedirs("/app/results", exist_ok=True)

    # Load all keys
    keys = {}
    for fname in sorted(os.listdir("/app/keys")):
        if not fname.endswith(".json"):
            continue
        with open(f"/app/keys/{fname}") as f:
            data = json.load(f)
        key_id = data["id"]
        n = int(data["n_hex"], 16)
        e = data["e"]
        keys[key_id] = {"n": n, "e": e}

    # Step 1: ROCA detection
    print("=== ROCA Detection ===")
    detection = {}
    for key_id, kdata in sorted(keys.items()):
        vuln = is_roca_vulnerable(kdata["n"])
        detection[key_id] = vuln
        nbits = kdata["n"].bit_length()
        print(f"  {key_id} ({nbits}-bit): {'VULNERABLE' if vuln else 'normal'}")

    with open("/app/results/roca_detection.json", "w") as f:
        json.dump(detection, f, indent=2)

    # Step 2: Factor ROCA keys with small moduli
    print(f"\n=== Factoring ROCA Keys (modulus <= {FACTOR_BIT_LIMIT} bits) ===")
    factored = {}
    for key_id, kdata in sorted(keys.items()):
        if not detection[key_id]:
            continue
        nbits = kdata["n"].bit_length()
        if nbits > FACTOR_BIT_LIMIT:
            print(f"  {key_id}: skipping ({nbits}-bit, exceeds {FACTOR_BIT_LIMIT}-bit limit)")
            continue
        print(f"  {key_id}: factoring {nbits}-bit modulus...")
        p, q = factor_roca_key(kdata["n"])
        if p and q:
            if p > q:
                p, q = q, p
            factored[key_id] = {"p": str(p), "q": str(q)}
            print(f"    SUCCESS: p={p.bit_length()}-bit, q={q.bit_length()}-bit")
        else:
            print(f"    FAILED to factor {key_id}")

    with open("/app/results/factored_keys.json", "w") as f:
        json.dump(factored, f, indent=2)

    # Step 3: Derive private keys
    print("\n=== Deriving Private Keys ===")
    private_keys = {}
    for key_id, factors in factored.items():
        p = int(factors["p"])
        q = int(factors["q"])
        n = keys[key_id]["n"]
        e = keys[key_id]["e"]
        d = derive_private_key(p, q, e)
        private_keys[key_id] = {"d": str(d), "n": str(n)}
        # Verify
        msg = 42
        ct = pow(msg, e, n)
        pt = pow(ct, d, n)
        status = "VERIFIED" if pt == msg else "FAILED"
        print(f"  {key_id}: d computed, RSA cycle {status}")

    with open("/app/results/private_keys.json", "w") as f:
        json.dump(private_keys, f, indent=2)

    print("\nDone. Results written to /app/results/")


if __name__ == "__main__":
    main()
