frr version 10.3
frr defaults traditional
hostname R2
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.1.1.2/32
exit
!
interface eth0
 ip address 10.0.12.2/30
exit
!
interface eth1
 ip address 10.0.23.1/30
exit
!
interface eth2
 ip address 10.100.2.1/24
exit
!
interface eth3
 ip address 10.200.2.1/24
exit
!
vrf CUST
exit-vrf
!
vrf INTERNAL
exit-vrf
!
router bgp 65001
 bgp router-id 10.1.1.2
 neighbor 10.0.12.1 remote-as 65001
 neighbor 10.0.12.1 update-source lo
 neighbor 10.0.23.2 remote-as 65001
 neighbor 10.0.23.2 update-source lo
 !
 address-family ipv4 unicast
  neighbor 10.0.12.1 activate
  neighbor 10.0.23.2 activate
 exit-address-family
exit
!
router bgp 65001 vrf CUST
 !
 address-family ipv4 unicast
  redistribute connected
  rd vpn export 65001:100
  rt vpn both 65001:100
  export vpn
  import vpn
 exit-address-family
exit
!
router bgp 65001 vrf INTERNAL
 bgp router-id 10.200.2.1
 !
 address-family ipv4 unicast
  redistribute connected
  rd vpn export 65001:250
  rt vpn export 65001:250
  rt vpn import 65001:100
  export vpn
 exit-address-family
exit
!
ip forwarding
!
line vty
!
