forge 'https://forge.puppet.com'

# Core infrastructure
mod 'puppetlabs/stdlib', '9.6.0'
mod 'puppetlabs/concat', '~> 8.1'
mod 'puppetlabs/apt'

# Monitoring stack
mod 'voxpupuli/prometheus'

# System services
mod 'voxpupuli/victorialogs'
mod 'voxpupuli/augeasproviders'

# Internal custom modules
mod 'acme/profiles',
  :git => 'https://github.com/acme-corp/puppet-profiles.git',
  :tag => 'v2.1.0'
