#!/usr/bin/env python3
"""
Energy field reconstruction solver for Lux AI Season 3.

Solves the inverse problem: given partial observations of a 24x24 energy field
generated by unknown energy source nodes, reconstruct the complete field and
determine the number of independent nodes.

Approach:
1. Parse partial observations and augment with rotational symmetry.
2. For each candidate node count (1-3) and function type combination:
   a. Use differential_evolution for global optimization of node positions
      and function parameters.
   b. Evaluate fit quality via integer reconstruction error.
3. Select the simplest model with near-zero integer error (early stopping +
   BIC-based selection).
4. Reconstruct the complete 24x24 field from best-fit parameters.
"""


import json
import math
import sys
from itertools import product

import numpy as np
from scipy.optimize import differential_evolution

MAP_SIZE = 24


# ── Forward computation (vectorized) ────────────────────────────────────────


def compute_pair_contribution(coords, nx, ny, fn_type, a, b, c):
    """Compute energy contribution from an independent node AND its mirror.

    Args:
        coords: (N, 2) array of tile coordinates
        nx, ny: independent node position
        fn_type: 0 (sinusoidal) or 1 (rational decay)
        a, b, c: function parameters

    Returns:
        (N,) array of energy contributions from this node pair
    """
    d1 = np.sqrt((coords[:, 0] - nx) ** 2 + (coords[:, 1] - ny) ** 2)
    d2 = np.sqrt((coords[:, 0] - (23 - nx)) ** 2 + (coords[:, 1] - (23 - ny)) ** 2)

    if fn_type == 0:
        return np.sin(d1 * a + b) * c + np.sin(d2 * a + b) * c
    else:
        return (a / (d1 + 1) + b) * c + (a / (d2 + 1) + b) * c


def _compute_total(params_flat, coords, n_nodes, fn_types):
    """Compute raw total energy at given coordinates."""
    total = np.zeros(len(coords))
    for i in range(n_nodes):
        off = i * 5
        total += compute_pair_contribution(
            coords,
            params_flat[off], params_flat[off + 1],
            fn_types[i],
            params_flat[off + 2], params_flat[off + 3], params_flat[off + 4],
        )
    return total


# ── Objective functions ─────────────────────────────────────────────────────


def smooth_objective(params_flat, obs_coords, obs_values, n_nodes, fn_types):
    """Smooth objective for optimization (clip but no truncation)."""
    computed = np.clip(_compute_total(params_flat, obs_coords, n_nodes, fn_types), -20, 20)
    return float(np.sum((computed - obs_values) ** 2))


def integer_error(params_flat, obs_coords, obs_values, n_nodes, fn_types):
    """Integer error (clip + truncate, matching game engine behavior)."""
    computed = np.trunc(np.clip(
        _compute_total(params_flat, obs_coords, n_nodes, fn_types), -20, 20
    ))
    return float(np.sum((computed - obs_values) ** 2))


# ── Optimization ────────────────────────────────────────────────────────────


def fit_model(obs_coords, obs_values, n_nodes, fn_types, seed=42):
    """Fit node parameters using differential evolution.

    Returns (smooth_loss, integer_loss, best_params).
    """
    bounds = []
    for _ in range(n_nodes):
        bounds.extend([
            (0.0, 23.0),    # x position
            (0.0, 23.0),    # y position
            (-6.0, 6.0),    # a (wider to cover both fn types)
            (-2.0, 2.0),    # b
            (0.5, 7.0),     # c (positive)
        ])

    result = differential_evolution(
        smooth_objective,
        bounds=bounds,
        args=(obs_coords, obs_values, n_nodes, fn_types),
        seed=seed,
        maxiter=300,
        tol=1e-3,
        popsize=15,
        mutation=(0.5, 1.5),
        recombination=0.8,
        polish=True,
    )

    i_loss = integer_error(result.x, obs_coords, obs_values, n_nodes, fn_types)
    return result.fun, i_loss, result.x


def reconstruct_full_field(params_flat, n_nodes, fn_types):
    """Reconstruct the complete 24x24 field from fitted parameters."""
    all_coords = np.array(
        [[x, y] for x in range(MAP_SIZE) for y in range(MAP_SIZE)],
        dtype=np.float64,
    )
    total = _compute_total(params_flat, all_coords, n_nodes, fn_types)
    total = np.clip(total, -20, 20)
    field = np.trunc(total).astype(int).reshape(MAP_SIZE, MAP_SIZE)

    # Enforce exact symmetry: for each symmetric pair, use the same value
    for x in range(MAP_SIZE):
        for y in range(MAP_SIZE):
            rx, ry = MAP_SIZE - 1 - x, MAP_SIZE - 1 - y
            if x < rx or (x == rx and y < ry):
                v1, v2 = int(field[x, y]), int(field[rx, ry])
                avg = (v1 + v2) / 2.0
                chosen = int(math.trunc(avg))
                field[x, y] = chosen
                field[rx, ry] = chosen

    return field


# ── Main solver ─────────────────────────────────────────────────────────────


# Threshold: average integer squared error per tile below which we accept the model
_ACCEPT_THRESHOLD = 0.05


def solve(input_path, output_path):
    """Main solver: read observations, infer parameters, write results."""
    with open(input_path) as f:
        data = json.load(f)

    observed = data["observed_tiles"]

    # Parse observations
    obs_x, obs_y, obs_v = [], [], []
    for key, val in observed.items():
        x, y = map(int, key.split(","))
        obs_x.append(x)
        obs_y.append(y)
        obs_v.append(val)

    # Augment with symmetric observations: f(x,y) = f(23-x, 23-y)
    seen = set(observed.keys())
    for key, val in list(observed.items()):
        x, y = map(int, key.split(","))
        sym_key = f"{23-x},{23-y}"
        if sym_key not in seen:
            obs_x.append(23 - x)
            obs_y.append(23 - y)
            obs_v.append(val)
            seen.add(sym_key)

    obs_coords = np.column_stack([obs_x, obs_y]).astype(np.float64)
    obs_values = np.array(obs_v, dtype=np.float64)
    n_obs = len(obs_values)

    # Search over candidate models with early stopping
    best_by_n = {}  # n_nodes -> (fn_types, params, s_loss, i_loss)
    found_perfect = False

    for n_nodes in [1, 2, 3]:
        if found_perfect:
            break

        best_for_n = None

        for fn_combo in product([0, 1], repeat=n_nodes):
            fn_types = list(fn_combo)
            s_loss, i_loss, params = fit_model(
                obs_coords, obs_values, n_nodes, fn_types, seed=42
            )

            if best_for_n is None or s_loss < best_for_n[2]:
                best_for_n = (fn_types, params, s_loss, i_loss)

            # Early exit if near-perfect fit
            avg_int_err = i_loss / n_obs
            if avg_int_err < _ACCEPT_THRESHOLD:
                best_for_n = (fn_types, params, s_loss, i_loss)
                break

        if best_for_n is not None:
            fn_types, params, s_loss, i_loss = best_for_n
            best_by_n[n_nodes] = (fn_types, params, s_loss, i_loss)

            # If this model fits perfectly, no need to try more nodes
            if i_loss / n_obs < _ACCEPT_THRESHOLD:
                found_perfect = True

    # Model selection: BIC on integer error, preferring simpler models
    best_bic = float("inf")
    best_choice = None

    for n_nodes, (fn_types, params, s_loss, i_loss) in best_by_n.items():
        k = n_nodes * 5
        rss = max(i_loss, 0.001)
        bic = n_obs * np.log(rss / n_obs) + k * np.log(n_obs)

        if bic < best_bic:
            best_bic = bic
            best_choice = (n_nodes, fn_types, params)

    n_nodes, fn_types, params = best_choice

    # Reconstruct full field
    field = reconstruct_full_field(params, n_nodes, fn_types)

    output = {
        "energy_field": field.tolist(),
        "n_nodes": n_nodes,
    }
    with open(output_path, "w") as f:
        json.dump(output, f)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input.json> <output.json>", file=sys.stderr)
        sys.exit(1)
    solve(sys.argv[1], sys.argv[2])
