
"""
Pytest verification for MicroHaxl concurrent data-fetching framework.
Checks compilation success and test results from the Haskell test driver.
"""

import subprocess
import os
import pytest
import re


def compile_and_run():
    """Compile and run the Haskell test driver, return (compile_ok, output)."""
    assert os.path.exists("/app/MicroHaxl.hs"), "MicroHaxl.hs not found"

    test_driver_path = "/app/TestDriver.hs"

    if not os.path.exists(test_driver_path):
        pytest.fail("TestDriver.hs not generated by test.sh")

    compile_result = subprocess.run(
        ["ghc", "-O0", "-o", "/app/test_runner",
         "/app/TestDriver.hs", "/app/MicroHaxl.hs",
         "-no-keep-hi-files", "-no-keep-o-files"],
        capture_output=True, text=True, timeout=120
    )

    if compile_result.returncode != 0:
        return False, compile_result.stderr

    run_result = subprocess.run(
        ["/app/test_runner"],
        capture_output=True, text=True, timeout=60
    )

    return True, run_result.stdout + run_result.stderr


@pytest.fixture(scope="session")
def test_output():
    """Run compilation and tests once, cache the result."""
    compiled, output = compile_and_run()
    return {"compiled": compiled, "output": output}


class TestCompilation:
    def test_compiles(self, test_output):
        assert test_output["compiled"], (
            f"MicroHaxl.hs failed to compile:\n{test_output['output']}"
        )


class TestSingleFetch:
    def test_single_fetch(self, test_output):
        assert test_output["compiled"], "Compilation failed"
        assert "PASS: single_fetch" in test_output["output"], (
            f"single_fetch test failed:\n{test_output['output']}"
        )


class TestApplicativeBatching:
    def test_applicative_batching(self, test_output):
        assert test_output["compiled"], "Compilation failed"
        assert "PASS: applicative_batching" in test_output["output"], (
            f"applicative_batching test failed:\n{test_output['output']}"
        )


class TestMonadicSequencing:
    def test_monadic_sequencing(self, test_output):
        assert test_output["compiled"], "Compilation failed"
        assert "PASS: monadic_sequencing" in test_output["output"], (
            f"monadic_sequencing test failed:\n{test_output['output']}"
        )


class TestDeduplication:
    def test_deduplication(self, test_output):
        assert test_output["compiled"], "Compilation failed"
        assert "PASS: deduplication" in test_output["output"], (
            f"deduplication test failed:\n{test_output['output']}"
        )


class TestTraverseBatching:
    def test_traverse_batching(self, test_output):
        assert test_output["compiled"], "Compilation failed"
        assert "PASS: traverse_batching" in test_output["output"], (
            f"traverse_batching test failed:\n{test_output['output']}"
        )


class TestStatsAccuracy:
    def test_stats_accuracy(self, test_output):
        assert test_output["compiled"], "Compilation failed"
        assert "PASS: stats_accuracy" in test_output["output"], (
            f"stats_accuracy test failed:\n{test_output['output']}"
        )


class TestCrossTypeCache:
    def test_cross_type_cache(self, test_output):
        assert test_output["compiled"], "Compilation failed"
        assert "PASS: cross_type_cache" in test_output["output"], (
            f"cross_type_cache test failed:\n{test_output['output']}"
        )


class TestExceptionPropagation:
    def test_exception_propagation(self, test_output):
        assert test_output["compiled"], "Compilation failed"
        assert "PASS: exception_propagation" in test_output["output"], (
            f"exception_propagation test failed:\n{test_output['output']}"
        )


class TestConcurrentDispatch:
    def test_concurrent_dispatch(self, test_output):
        assert test_output["compiled"], "Compilation failed"
        assert "PASS: concurrent_dispatch" in test_output["output"], (
            f"concurrent_dispatch test failed:\n{test_output['output']}"
        )


class TestMultiRound:
    def test_multi_round(self, test_output):
        assert test_output["compiled"], "Compilation failed"
        assert "PASS: multi_round" in test_output["output"], (
            f"multi_round test failed:\n{test_output['output']}"
        )


class TestPreFetch:
    def test_prefetch(self, test_output):
        assert test_output["compiled"], "Compilation failed"
        assert "PASS: prefetch" in test_output["output"], (
            f"prefetch test failed:\n{test_output['output']}"
        )


class TestAllPass:
    def test_all_tests_pass(self, test_output):
        assert test_output["compiled"], "Compilation failed"
        output = test_output["output"]
        match = re.search(r'(\d+)/(\d+) tests passed', output)
        assert match, f"Could not find test summary in output:\n{output}"
        passed = int(match.group(1))
        total = int(match.group(2))
        assert passed == total, (
            f"Not all tests passed: {passed}/{total}\n{output}"
        )
