#!/usr/bin/env python3
"""Generate a correctly-rounded exp2m1f implementation.

Uses mpmath to compute precise lookup-table entries and polynomial
coefficients, then writes /app/exp2m1f.c.
"""

import mpmath

mpmath.mp.prec = 200

N = 32  # table size (power of 2 for fast modular arithmetic)
LOG2N = 5  # log2(N)

# ---------------------------------------------------------------------------
# Compute table entries: T[j] = 2^(j/N) and Tm1[j] = 2^(j/N) - 1
# ---------------------------------------------------------------------------

T_vals = []
Tm1_vals = []
for j in range(N):
    v = mpmath.power(2, mpmath.mpf(j) / N)
    T_vals.append(float(v))
    Tm1_vals.append(float(v - 1))

# ---------------------------------------------------------------------------
# Polynomial coefficients for 2^r - 1 ~ r * (c0 + r*(c1 + r*(c2 + ...)))
# where c_k = ln(2)^(k+1) / (k+1)!   and |r| <= 1/(2N)
# ---------------------------------------------------------------------------

ln2 = mpmath.log(2)
coeffs = []
for k in range(6):
    c = ln2 ** (k + 1) / mpmath.factorial(k + 1)
    coeffs.append(float(c))

# ---------------------------------------------------------------------------
# Emit C code
# ---------------------------------------------------------------------------


def hex_double(d):
    """Format a double as a C hex-float literal."""
    return float.hex(d)


lines = []
w = lines.append

w("/* Correctly-rounded exp2m1f (2^x - 1) for IEEE 754 binary32.")
w(" *")
w(" * Algorithm:")
w(" *   Range reduction: x = k/32 + r  where k = round(32*x), |r| <= 1/64")
w(" *   Split k = 32*q + j  (0 <= j < 32)")
w(" *   Lookup T[j] = 2^(j/32), Tm1[j] = 2^(j/32) - 1")
w(" *   Polynomial: P(r) ~ 2^r - 1   (6-term Taylor in r)")
w(" *   Reconstruct: 2^x - 1 = T[j]*2^q*(1+P) - 1")
w(" *   For q == 0: use Tm1[j] + T[j]*P to avoid cancellation")
w(" *")
w(" * Generated by gen_exp2m1f.py -- do not edit by hand.")
w(" */")
w("")
w('#include "exp2m1f.h"')
w("#include <stdint.h>")
w("")
w("typedef union { float  f; uint32_t u; } b32u32_u;")
w("typedef union { double d; uint64_t u; } b64u64_u;")
w("")

# Table T
w(f"static const double T[{N}] = {{")
for j in range(N):
    w(f"    {hex_double(T_vals[j])},  /* 2^({j}/{N}) */")
w("};")
w("")

# Table Tm1
w(f"static const double Tm1[{N}] = {{")
for j in range(N):
    w(f"    {hex_double(Tm1_vals[j])},  /* 2^({j}/{N}) - 1 */")
w("};")
w("")

# Polynomial coefficients
for i, c in enumerate(coeffs):
    w(f"static const double c{i} = {hex_double(c)};  /* ln(2)^{i+1}/{i+1}! */")
w("")

# Main function
w("float cr_exp2m1f(float x) {")
w("    b32u32_u xi = {.f = x};")
w("    uint32_t ax = xi.u & 0x7FFFFFFFu;")
w("")
w("    /* NaN */")
w("    if (ax > 0x7F800000u) return x + x;")
w("    /* +Inf */")
w("    if (xi.u == 0x7F800000u) return x;")
w("    /* -Inf -> -1 */")
w("    if (xi.u == 0xFF800000u) return -1.0f;")
w("    /* +/-0 -> x (preserves sign) */")
w("    if (ax == 0u) return x;")
w("")
w("    /* Overflow: x >= 128 -> +Inf */")
w("    if (x >= 128.0f) {")
w("        volatile float huge = 0x1.fffffep+127f;")
w("        return huge + huge;  /* +Inf, raises overflow */")
w("    }")
w("")
w("    /* For x <= -150, 2^x underflows in double, result is -1 */")
w("    if (x <= -150.0f) return -1.0f;")
w("")
w("    double xd = (double)x;")
w("")
w("    /* ---- Range reduction: k = round(32 * x) ---- */")
w("    double kd_approx = xd * 32.0;")
w("    /* Round-to-nearest-even via the magic-number trick */")
w("    const double MAGIC = 0x1.8p+52;  /* 2^52 * 1.5 */")
w("    b64u64_u tmp;")
w("    tmp.d = kd_approx + MAGIC;")
w("    int64_t k = (int64_t)tmp.u - (int64_t)0x4338000000000000LL;")
w("    double r = xd - (double)k * 0x1p-5;  /* k / 32 */")
w("")
w("    /* Split k = 32*q + j   (0 <= j < 32) */")
w("    int q, j;")
w("    if (k >= 0) {")
w(f"        q = (int)(k >> {LOG2N});")
w(f"        j = (int)(k & {N - 1});")
w("    } else {")
w(f"        q = (int)((k - {N - 1}) / {N});")
w(f"        j = (int)(k - (int64_t)q * {N});")
w("    }")
w("")
w("    /* ---- Polynomial: P ~ 2^r - 1 ---- */")
poly = "r * (c0 + r * (c1 + r * (c2 + r * (c3 + r * (c4 + r * c5)))))"
w(f"    double P = {poly};")
w("")
w("    /* ---- Reconstruct: 2^x - 1 = T[j] * 2^q * (1 + P) - 1 ---- */")
w("    double result;")
w("")
w("    if (q == 0) {")
w("        /* Use Tm1 table to avoid cancellation T[j] - 1 */")
w("        result = Tm1[j] + T[j] * P;")
w("    } else {")
w("        /* Construct 2^q as a double */")
w("        int eq = q + 1023;")
w("        if (eq <= 0) {")
w("            /* 2^q is subnormal-range in double or smaller */")
w("            if (q < -1074) return -1.0f;")
w("            /* Use two-step scaling to avoid double subnormal arithmetic */")
w("            b64u64_u s1;")
w("            s1.u = (uint64_t)1 << 52;  /* 2^(-1022) */")
w("            double scale1 = T[j] * s1.d;")
w("            int q2 = q + 1022;")
w("            if (q2 + 1023 > 0) {")
w("                b64u64_u s2;")
w("                s2.u = (uint64_t)(q2 + 1023) << 52;")
w("                double s = scale1 * s2.d;")
w("                result = s * (1.0 + P) - 1.0;")
w("            } else {")
w("                /* Even smaller, result is -1 */")
w("                return -1.0f;")
w("            }")
w("        } else {")
w("            b64u64_u two_q;")
w("            two_q.u = (uint64_t)eq << 52;")
w("            double s = T[j] * two_q.d;")
w("            if (q > 0) {")
w("                /* s >= 2, subtraction of 1 is benign */")
w("                result = (s - 1.0) + s * P;")
w("            } else {")
w("                /* q < 0, s < 1 */")
w("                result = s * (1.0 + P) - 1.0;")
w("            }")
w("        }")
w("    }")
w("")
w("    return (float)result;")
w("}")
w("")

with open("/app/exp2m1f.c", "w") as f:
    f.write("\n".join(lines))

print("Generated /app/exp2m1f.c successfully.")
