
import subprocess
import os
import pytest

BUILD_DIR = "/app/build"


@pytest.fixture(scope="session")
def build_project():
    """Build the project with CMake."""
    os.makedirs(BUILD_DIR, exist_ok=True)

    result = subprocess.run(
        ["cmake", "-B", BUILD_DIR, "-DCMAKE_BUILD_TYPE=Release"],
        cwd="/app",
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert result.returncode == 0, (
        f"CMake configure failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
    )

    result = subprocess.run(
        ["cmake", "--build", BUILD_DIR, "-j"],
        cwd="/app",
        capture_output=True,
        text=True,
        timeout=120,
    )
    assert result.returncode == 0, (
        f"Build failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
    )
    return True


@pytest.fixture(scope="session")
def test_runner_output(build_project):
    """Run the test_runner binary and capture output."""
    result = subprocess.run(
        [os.path.join(BUILD_DIR, "test_runner")],
        capture_output=True,
        text=True,
        timeout=240,
    )
    return result


def test_project_builds(build_project):
    """The project must compile without errors."""
    assert build_project


def test_correctness_all(test_runner_output):
    """All correctness tests must pass (aligned, unaligned, small, large)."""
    out = test_runner_output.stdout
    assert "ALL_TESTS_PASSED" in out, (
        f"Correctness tests failed:\n{out}\nstderr: {test_runner_output.stderr}"
    )


def test_correctness_aligned(test_runner_output):
    """Aligned matrix sizes (multiples of micro-kernel tile) must be correct."""
    for line in test_runner_output.stdout.split("\n"):
        if "[aligned" in line:
            assert "PASS" in line, f"Aligned test failed: {line}"


def test_correctness_edge_cases(test_runner_output):
    """Non-aligned matrix sizes must be handled via masking/padding."""
    for line in test_runner_output.stdout.split("\n"):
        if "[unaligned" in line:
            assert "PASS" in line, f"Unaligned test failed: {line}"


def test_correctness_small(test_runner_output):
    """Degenerate/small matrix sizes must work correctly."""
    for line in test_runner_output.stdout.split("\n"):
        if "[small" in line:
            assert "PASS" in line, f"Small matrix test failed: {line}"


def test_correctness_large(test_runner_output):
    """Large matrix (1000x1000) must be correct."""
    for line in test_runner_output.stdout.split("\n"):
        if "[large" in line:
            assert "PASS" in line, f"Large matrix test failed: {line}"


def test_uses_fma_instructions():
    """The compiled assembly must contain vfmadd instructions (AVX2/FMA)."""
    result = subprocess.run(
        [
            "gcc", "-O3", "-mavx2", "-mfma", "-S",
            "-o", "/tmp/optimized.s",
            "/app/src/optimized.c",
            "-I/app/include",
        ],
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert result.returncode == 0, (
        f"Assembly generation failed:\n{result.stderr}"
    )

    with open("/tmp/optimized.s") as f:
        asm = f.read().lower()

    assert "vfmadd" in asm, (
        "No vfmadd (FMA) instructions found in generated assembly. "
        "The implementation must use _mm256_fmadd_ps intrinsics."
    )


def test_uses_broadcast_instructions():
    """The compiled assembly must contain vbroadcastss instructions."""
    # Re-use the assembly file generated by the FMA test if it exists,
    # otherwise generate it.
    asm_path = "/tmp/optimized.s"
    if not os.path.exists(asm_path):
        subprocess.run(
            [
                "gcc", "-O3", "-mavx2", "-mfma", "-S",
                "-o", asm_path,
                "/app/src/optimized.c",
                "-I/app/include",
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )

    with open(asm_path) as f:
        asm = f.read().lower()

    assert "vbroadcastss" in asm, (
        "No vbroadcastss instructions found in generated assembly. "
        "The micro-kernel must broadcast scalar B elements for outer-product updates."
    )


def test_not_naive_wrapper():
    """The implementation must not simply delegate to matmul_naive."""
    with open("/app/src/optimized.c") as f:
        code = f.read()

    assert "matmul_naive" not in code, (
        "Implementation must not call matmul_naive — it must be an independent "
        "AVX2/FMA implementation."
    )
    assert "_mm256" in code, (
        "Implementation must use AVX2 intrinsics (_mm256_* functions)."
    )
    assert "immintrin" in code or "x86intrin" in code, (
        "Implementation must include SIMD header (<immintrin.h> or <x86intrin.h>)."
    )
