#!/usr/bin/env python3
"""
Analyze pipeline architecture and generate a flow control wrapper.

"""

import re
import os
import subprocess
import math


def parse_module_params(filepath):
    """Extract module-level parameter defaults."""
    with open(filepath) as f:
        content = f.read()
    params = {}
    for m in re.finditer(r'parameter\s+(\w+)\s*=\s*(\d+)', content):
        params[m.group(1)] = int(m.group(2))
    return params


def parse_localparams(filepath):
    """Extract localparam definitions."""
    with open(filepath) as f:
        content = f.read()
    params = {}
    for m in re.finditer(r'localparam\s+(\w+)\s*=\s*([^;]+);', content):
        name = m.group(1)
        expr = re.sub(r'//.*', '', m.group(2)).strip()
        params[name] = expr
    return params


def resolve_params(localparams, initial_values=None):
    """Resolve localparam expressions to integer values."""
    known = dict(initial_values) if initial_values else {}
    for _ in range(10):
        for name, expr in localparams.items():
            if name in known:
                continue
            eval_expr = expr
            for k, v in known.items():
                eval_expr = re.sub(r'\b' + k + r'\b', str(v), eval_expr)
            try:
                val = int(eval(eval_expr))
                known[name] = val
            except Exception:
                pass
    return known


def get_overrides(pipeline_src, module_name):
    """Find parameter overrides at the instantiation site in compute_pipeline."""
    overrides = {}
    pat = rf'{module_name}\s*#\s*\(([^)]+)\)\s+\w+'
    m = re.search(pat, pipeline_src)
    if m:
        for pm in re.finditer(r'\.(\w+)\s*\((\d+)\)', m.group(1)):
            overrides[pm.group(1)] = int(pm.group(2))
    return overrides


def module_depth(filepath, depth_keys, overrides=None):
    """Compute effective pipeline depth of a blackbox module."""
    defaults = parse_module_params(filepath)
    if overrides:
        defaults.update(overrides)
    lp = parse_localparams(filepath)
    resolved = resolve_params(lp, defaults)
    for k in depth_keys:
        if k in resolved:
            return resolved[k]
    raise ValueError(f"Depth not found in {filepath}: {resolved}")


# --- Read pipeline source ---
with open('/app/rtl/compute_pipeline.sv') as f:
    pipe_src = f.read()

# --- Determine sub-block depths with instantiation overrides ---
mult_ov = get_overrides(pipe_src, 'pipe_mult')
isqrt_ov = get_overrides(pipe_src, 'pipe_isqrt')

d_mult = module_depth('/app/rtl/blackbox/pipe_mult.sv',
                       ['NUM_SEGMENTS', 'PIPE_STAGES'], mult_ov)
d_add = module_depth('/app/rtl/blackbox/pipe_add.sv',
                      ['STAGE_COUNT', 'PIPE_DEPTH'])
d_isqrt = module_depth('/app/rtl/blackbox/pipe_isqrt.sv',
                         ['PIPE_DEPTH', 'STAGE_COUNT'], isqrt_ov)

print(f"pipe_mult  depth = {d_mult}  (overrides: {mult_ov})")
print(f"pipe_add   depth = {d_add}")
print(f"pipe_isqrt depth = {d_isqrt}  (overrides: {isqrt_ov})")

# --- Detect registered interconnect stage in compute_pipeline ---
# A registered stage appears as an always block that registers
# module outputs before feeding them to the next module
interconnect = 1 if ('a_sq_r' in pipe_src or 'sq_vld_r' in pipe_src) else 0
print(f"Registered interconnect stages: {interconnect}")

# --- Total pipeline latency ---
# Pipeline: mult -> [reg] -> add -> isqrt -> add(final)
total_lat = d_mult + interconnect + d_add + d_isqrt + d_add
print(f"Total pipeline latency: {d_mult}+{interconnect}+{d_add}+{d_isqrt}+{d_add} = {total_lat}")

# --- FIFO sizing (power of 2 >= pipeline latency) ---
fifo_depth = 1
while fifo_depth < total_lat:
    fifo_depth *= 2
ptr_w = int(math.log2(fifo_depth))
credit_w = ptr_w + 1

print(f"FIFO depth = {fifo_depth}, ptr width = {ptr_w}")

# --- Generate wrapper RTL ---
wrapper = f"""\
// Flow control wrapper - generated by solve.py
//

module flow_control_wrapper (
    input  wire        clk,
    input  wire        rst,

    input  wire        arg_vld,
    output wire        arg_rdy,
    input  wire [31:0] a,
    input  wire [31:0] b,
    input  wire [31:0] c,

    output wire        res_vld,
    input  wire        res_rdy,
    output wire [31:0] result
);

    // Pipeline latency = {d_mult}(mult) + {interconnect}(reg) + {d_add}(add) + {d_isqrt}(isqrt) + {d_add}(add) = {total_lat}
    localparam FIFO_DEPTH = {fifo_depth};
    localparam PTR_W      = {ptr_w};

    //----------------------------------------------------------
    // Pipeline instance
    //----------------------------------------------------------

    wire pipe_in_vld;
    wire pipe_out_vld;
    wire [31:0] pipe_result;

    assign pipe_in_vld = arg_vld & arg_rdy;

    compute_pipeline u_pipe (
        .clk    (clk),
        .rst    (rst),
        .in_vld (pipe_in_vld),
        .a      (a),
        .b      (b),
        .c      (c),
        .out_vld(pipe_out_vld),
        .result (pipe_result)
    );

    //----------------------------------------------------------
    // Credit counter
    //----------------------------------------------------------

    reg [{credit_w - 1}:0] credits;

    assign arg_rdy = (credits > 0);

    wire fifo_pop = res_vld & res_rdy;

    always @(posedge clk) begin
        if (rst) begin
            credits <= FIFO_DEPTH;
        end else begin
            case ({{pipe_in_vld, fifo_pop}})
                2'b10:   credits <= credits - 1;
                2'b01:   credits <= credits + 1;
                default: credits <= credits;
            endcase
        end
    end

    //----------------------------------------------------------
    // FIFO (power-of-2 depth, extended-pointer empty detection)
    //----------------------------------------------------------

    reg [31:0] fifo_mem [0:FIFO_DEPTH-1];
    reg [PTR_W:0] wr_ptr;
    reg [PTR_W:0] rd_ptr;

    wire fifo_empty = (wr_ptr == rd_ptr);
    wire fifo_push  = pipe_out_vld;

    assign res_vld = ~fifo_empty;
    assign result  = fifo_mem[rd_ptr[PTR_W-1:0]];

    always @(posedge clk) begin
        if (rst) begin
            wr_ptr <= 0;
            rd_ptr <= 0;
        end else begin
            if (fifo_push) begin
                fifo_mem[wr_ptr[PTR_W-1:0]] <= pipe_result;
                wr_ptr <= wr_ptr + 1;
            end
            if (fifo_pop) begin
                rd_ptr <= rd_ptr + 1;
            end
        end
    end

endmodule
"""

with open('/app/rtl/flow_control_wrapper.sv', 'w') as f:
    f.write(wrapper)
print("Written /app/rtl/flow_control_wrapper.sv")

# --- Verify ---
os.chdir('/app')
r = subprocess.run(['bash', 'simulate.sh'], capture_output=True, text=True, timeout=120)
print(r.stdout)
if r.stderr:
    print(r.stderr)

if 'FAIL' in r.stdout or 'FAIL' in r.stderr:
    print("VERIFICATION FAILED")
    exit(1)
elif 'PASS' in r.stdout:
    print("VERIFICATION PASSED")
else:
    print("No PASS/FAIL detected")
    exit(1)
