#!/usr/bin/env python3
"""
Generate C source with Unicode Sentence_Break property lookup tables.

Reads SentenceBreakProperty.txt from /app/data/
and outputs sentence_tables.c with binary-search lookup functions.

"""

import os
import re

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data')

# Category name -> integer ID mapping.
# sentence_segment.py must use the same mapping.
CATEGORIES = {
    'Other': 0,
    'CR': 1,
    'LF': 2,
    'Extend': 3,
    'Sep': 4,
    'Format': 5,
    'Sp': 6,
    'Lower': 7,
    'Upper': 8,
    'OLetter': 9,
    'Numeric': 10,
    'ATerm': 11,
    'SContinue': 12,
    'STerm': 13,
    'Close': 14,
}


def parse_ranges(filepath, filter_prop=None):
    """Parse a Unicode data file, returning sorted (lo, hi, property) list."""
    pattern = re.compile(
        r'^\s*([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*([\w_]+)'
    )
    ranges = []
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            comment_pos = line.find('#')
            if comment_pos >= 0:
                line = line[:comment_pos].strip()
            if not line:
                continue
            m = pattern.match(line)
            if not m:
                continue
            lo = int(m.group(1), 16)
            hi = int(m.group(2), 16) if m.group(2) else lo
            prop = m.group(3)
            if 0xD800 <= lo <= 0xDFFF:
                continue
            if filter_prop is not None and prop != filter_prop:
                continue
            ranges.append((lo, hi, prop))
    ranges.sort(key=lambda x: x[0])
    return ranges


def merge_adjacent(ranges):
    """Merge adjacent ranges sharing the same category."""
    if not ranges:
        return []
    merged = [list(ranges[0])]
    for lo, hi, cat in ranges[1:]:
        prev = merged[-1]
        if cat == prev[2] and lo == prev[1] + 1:
            prev[1] = hi
        else:
            merged.append([lo, hi, cat])
    return [tuple(r) for r in merged]


def generate_c(sb_ranges, output_path):
    """Generate C source file with lookup tables and binary search functions."""
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('/* Auto-generated by gen_sentence_tables.py \xe2\x80\x94 DO NOT EDIT */\n')
        f.write('#include <stdint.h>\n\n')

        # Category ID defines
        for name, val in sorted(CATEGORIES.items(), key=lambda x: x[1]):
            f.write(f'#define SB_{name.upper()} {val}\n')
        f.write('\n')

        # Struct type
        f.write('typedef struct { uint32_t lo; uint32_t hi; int cat; } SBRange;\n\n')

        # Sentence break property table
        f.write(f'static const SBRange sb_table[] = {{\n')
        for lo, hi, cat in sb_ranges:
            cat_id = CATEGORIES.get(cat, 0)
            f.write(f'    {{0x{lo:04X}, 0x{hi:04X}, {cat_id}}},\n')
        f.write('};\n')
        f.write(f'static const int sb_table_len = {len(sb_ranges)};\n\n')

        # Binary search: sentence_break_property
        f.write('int sentence_break_property(uint32_t cp) {\n')
        f.write('    int lo = 0, hi = sb_table_len - 1;\n')
        f.write('    while (lo <= hi) {\n')
        f.write('        int mid = lo + (hi - lo) / 2;\n')
        f.write('        if (cp < sb_table[mid].lo) hi = mid - 1;\n')
        f.write('        else if (cp > sb_table[mid].hi) lo = mid + 1;\n')
        f.write('        else return sb_table[mid].cat;\n')
        f.write('    }\n')
        f.write('    return SB_OTHER;\n')
        f.write('}\n')


def main():
    # Parse Sentence_Break properties
    sbp_path = os.path.join(DATA_DIR, 'SentenceBreakProperty.txt')
    sb_ranges = parse_ranges(sbp_path)
    sb_ranges = merge_adjacent(sb_ranges)

    # Generate C source
    output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'sentence_tables.c')
    generate_c(sb_ranges, output_path)
    print(f'Generated {output_path}: {len(sb_ranges)} SB ranges')


if __name__ == '__main__':
    main()
