"""Tests for exponential integrator cross-validation pipeline.

"""

import os
import subprocess
import pytest
import numpy as np
import sys

sys.path.insert(0, "/app")


# ---------------------------------------------------------------------------
# Session-scoped fixture: run the full Makefile pipeline once
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def pipeline_result():
    """Run make clean && make all once before all tests."""
    subprocess.run(["make", "clean"], cwd="/app", capture_output=True)
    result = subprocess.run(
        ["make", "all"], cwd="/app",
        capture_output=True, timeout=180
    )
    return result


@pytest.fixture(scope="session")
def reference_data(pipeline_result):
    """Load Octave-generated reference CSV files after pipeline runs."""
    data = {}
    ref_dir = "/app/reference"
    phi_path = os.path.join(ref_dir, "phi_coeffs.csv")
    coeff_path = os.path.join(ref_dir, "etd4rk_coeffs.csv")
    ks_path = os.path.join(ref_dir, "ks_ref.csv")

    if os.path.isfile(phi_path):
        data["phi"] = np.loadtxt(phi_path, delimiter=",")
    if os.path.isfile(coeff_path):
        data["coeffs"] = np.loadtxt(coeff_path, delimiter=",")
    if os.path.isfile(ks_path):
        data["ks_ref"] = np.loadtxt(ks_path, delimiter=",")
    return data


# ---------------------------------------------------------------------------
# Pipeline tests
# ---------------------------------------------------------------------------

class TestMakefilePipeline:
    """Verify the Makefile-driven Octave-Python pipeline works end-to-end."""

    def test_make_all_succeeds(self, pipeline_result):
        """make all must exit 0."""
        assert pipeline_result.returncode == 0, (
            f"make all failed (exit {pipeline_result.returncode}):\n"
            f"stdout: {pipeline_result.stdout.decode()[:2000]}\n"
            f"stderr: {pipeline_result.stderr.decode()[:2000]}"
        )

    def test_phi_coeffs_csv_exists(self, pipeline_result):
        assert os.path.isfile("/app/reference/phi_coeffs.csv"), (
            "reference/phi_coeffs.csv not generated by pipeline"
        )

    def test_etd4rk_coeffs_csv_exists(self, pipeline_result):
        assert os.path.isfile("/app/reference/etd4rk_coeffs.csv"), (
            "reference/etd4rk_coeffs.csv not generated by pipeline"
        )

    def test_ks_ref_csv_exists(self, pipeline_result):
        assert os.path.isfile("/app/reference/ks_ref.csv"), (
            "reference/ks_ref.csv not generated by pipeline"
        )

    def test_phi_coeffs_shape(self, reference_data):
        assert "phi" in reference_data, "phi_coeffs.csv not loaded"
        assert reference_data["phi"].shape == (16, 5), (
            f"Expected (16, 5), got {reference_data['phi'].shape}"
        )

    def test_etd4rk_coeffs_shape(self, reference_data):
        assert "coeffs" in reference_data, "etd4rk_coeffs.csv not loaded"
        assert reference_data["coeffs"].shape == (6, 4), (
            f"Expected (6, 4), got {reference_data['coeffs'].shape}"
        )

    def test_ks_ref_shape(self, reference_data):
        assert "ks_ref" in reference_data, "ks_ref.csv not loaded"
        assert reference_data["ks_ref"].shape == (64,), (
            f"Expected (64,), got {reference_data['ks_ref'].shape}"
        )


# ---------------------------------------------------------------------------
# Phi-function accuracy tests (pure Python, no reference needed)
# ---------------------------------------------------------------------------

class TestPhiFunctions:
    """Test accuracy of Python phi-function implementation."""

    def test_phi0_scalar(self):
        from solver import phi
        for z in [-1.0, 0.0, 1.0, -10.0, 5.0]:
            result = phi(z, 0)
            expected = np.exp(z)
            assert abs(result - expected) < 1e-12, (
                f"phi_0({z})={result}, expected {expected}"
            )

    def test_phi1_moderate_z(self):
        from solver import phi
        for z in [-1.0, -5.0, -10.0, 1.0, 3.0]:
            result = phi(z, 1)
            expected = (np.exp(z) - 1) / z
            rel_err = abs(result - expected) / max(abs(expected), 1e-15)
            assert rel_err < 1e-8, (
                f"phi_1({z})={result}, expected {expected}, rel_err={rel_err}"
            )

    def test_phi2_moderate_z(self):
        from solver import phi
        for z in [-1.0, -5.0, 2.0, -20.0]:
            result = phi(z, 2)
            expected = (np.exp(z) - 1 - z) / z ** 2
            rel_err = abs(result - expected) / max(abs(expected), 1e-15)
            assert rel_err < 1e-8, (
                f"phi_2({z})={result}, expected {expected}, rel_err={rel_err}"
            )

    def test_phi3_moderate_z(self):
        from solver import phi
        for z in [-1.0, -5.0, 2.0, -20.0]:
            result = phi(z, 3)
            expected = (np.exp(z) - 1 - z - z ** 2 / 2) / z ** 3
            rel_err = abs(result - expected) / max(abs(expected), 1e-15)
            assert rel_err < 1e-8, (
                f"phi_3({z})={result}, expected {expected}, rel_err={rel_err}"
            )

    def test_phi1_near_zero(self):
        from solver import phi
        for z in [0.0, 1e-15, 1e-10, 1e-6, 1e-3]:
            result = phi(z, 1)
            expected = 1.0 + z / 2 + z ** 2 / 6 + z ** 3 / 24
            assert abs(result - expected) < 1e-6, (
                f"phi_1({z})={result}, expected ~{expected}"
            )

    def test_phi2_near_zero(self):
        from solver import phi
        for z in [0.0, 1e-15, 1e-10, 1e-6]:
            result = phi(z, 2)
            expected = 0.5 + z / 6 + z ** 2 / 24
            assert abs(result - expected) < 1e-6, (
                f"phi_2({z})={result}, expected ~{expected}"
            )

    def test_phi3_near_zero(self):
        from solver import phi
        for z in [0.0, 1e-15, 1e-10, 1e-6]:
            result = phi(z, 3)
            expected = 1.0 / 6 + z / 24 + z ** 2 / 120
            assert abs(result - expected) < 1e-6, (
                f"phi_3({z})={result}, expected ~{expected}"
            )

    def test_phi_complex_argument(self):
        from solver import phi
        z = 1.0 + 2.0j
        ez = np.exp(z)

        result1 = phi(z, 1)
        expected1 = (ez - 1) / z
        assert abs(result1 - expected1) < 1e-10

        result2 = phi(z, 2)
        expected2 = (ez - 1 - z) / z ** 2
        assert abs(result2 - expected2) < 1e-10

        result3 = phi(z, 3)
        expected3 = (ez - 1 - z - z ** 2 / 2) / z ** 3
        assert abs(result3 - expected3) < 1e-10

    def test_phi_array_input(self):
        from solver import phi
        z = np.array([-1.0, -5.0, -10.0, -0.1])
        for k in range(4):
            result = phi(z, k)
            assert hasattr(result, "__len__"), (
                f"phi({z}, {k}) should return array-like"
            )
            assert len(result) == len(z)

    def test_phi_mixed_magnitude_array(self):
        from solver import phi
        z = np.array([1e-12, -10.0, 0.0, -100.0])
        result = phi(z, 1)
        assert abs(result[0] - 1.0) < 1e-4
        expected_neg10 = (np.exp(-10.0) - 1) / (-10.0)
        assert abs(result[1] - expected_neg10) < 1e-8
        assert abs(result[2] - 1.0) < 1e-6
        expected_neg100 = (np.exp(-100.0) - 1) / (-100.0)
        assert abs(result[3] - expected_neg100) < 1e-8


# ---------------------------------------------------------------------------
# Cross-validation: Python vs Octave reference
# ---------------------------------------------------------------------------

class TestCrossValidation:
    """Verify Python implementation matches Octave reference data."""

    def test_phi_matches_octave(self, reference_data):
        """Python phi values must match Octave reference within 1e-8."""
        from solver import phi

        assert "phi" in reference_data, "No Octave phi reference data"
        phi_data = reference_data["phi"]
        z_vals = phi_data[:, 0]
        max_err = 0.0

        for k in range(4):
            for i, z in enumerate(z_vals):
                py_val = float(np.real(phi(z, k)))
                oct_val = phi_data[i, k + 1]
                denom = max(abs(oct_val), 1e-15)
                err = abs(py_val - oct_val) / denom
                max_err = max(max_err, err)

        assert max_err < 1e-8, (
            f"Max phi relative error vs Octave: {max_err:.2e}"
        )

    def test_etd4rk_coefficients_match_octave(self, reference_data):
        """Python update coefficients must match Octave within 1e-8."""
        from solver import phi

        assert "coeffs" in reference_data, "No Octave coefficient data"
        coeff_data = reference_data["coeffs"]
        max_err = 0.0

        for i in range(coeff_data.shape[0]):
            hL = coeff_data[i, 0]
            p1 = float(np.real(phi(hL, 1)))
            p2 = float(np.real(phi(hL, 2)))
            p3 = float(np.real(phi(hL, 3)))

            py_a1 = p1 - 3 * p2 + 4 * p3
            py_a2 = 2 * (p2 - 2 * p3)
            py_a3 = -p2 + 4 * p3

            for py_val, col in [(py_a1, 1), (py_a2, 2), (py_a3, 3)]:
                oct_val = coeff_data[i, col]
                denom = max(abs(oct_val), 1e-15)
                err = abs(py_val - oct_val) / denom
                max_err = max(max_err, err)

        assert max_err < 1e-8, (
            f"Max coefficient relative error vs Octave: {max_err:.2e}"
        )

    def test_ks_solution_matches_octave(self, reference_data):
        """Python KS solution must match Octave reference within 0.01."""
        from solver import solve_ks

        assert "ks_ref" in reference_data, "No Octave KS reference data"
        ks_ref = reference_data["ks_ref"]

        u_python = solve_ks(L=32 * np.pi, N=64, T=1.0, dt=0.0625)
        max_err = np.max(np.abs(u_python - ks_ref))

        assert max_err < 0.01, (
            f"Max KS error vs Octave: {max_err:.2e} (threshold 0.01)"
        )


# ---------------------------------------------------------------------------
# Convergence tests (pure Python)
# ---------------------------------------------------------------------------

class TestConvergence:
    """Test that the integrator achieves 4th-order convergence in time."""

    @classmethod
    def setup_class(cls):
        from scipy.integrate import solve_ivp
        sys.path.insert(0, "/app")
        from problem import setup, nonlinear

        params = setup(L=32 * np.pi, N=64)
        cls.k_wave = params["k"]
        cls.Lk = params["Lk"]
        cls.u0_hat = params["u0_hat"]
        cls.N_modes = 64

        def rhs(t, y):
            N = cls.N_modes
            u_hat = y[:N] + 1j * y[N:]
            dudt = cls.Lk * u_hat + nonlinear(u_hat, cls.k_wave)
            return np.concatenate([dudt.real, dudt.imag])

        y0 = np.concatenate([cls.u0_hat.real, cls.u0_hat.imag])
        sol = solve_ivp(
            rhs, [0, 1.0], y0, method="Radau",
            rtol=1e-12, atol=1e-14, max_step=0.01,
        )
        assert sol.success, f"Reference computation failed: {sol.message}"

        u_ref_hat = sol.y[:cls.N_modes, -1] + 1j * sol.y[cls.N_modes:, -1]
        cls.u_ref = np.fft.ifft(u_ref_hat).real

    def test_fourth_order_convergence(self):
        from solver import solve_ks

        dts = [0.25, 0.125, 0.0625]
        errors = []
        for dt in dts:
            u = solve_ks(L=32 * np.pi, N=64, T=1.0, dt=dt)
            assert u.shape == (64,), f"Expected shape (64,), got {u.shape}"
            err = np.max(np.abs(u - self.u_ref))
            errors.append(err)

        order1 = np.log2(errors[0] / errors[1])
        order2 = np.log2(errors[1] / errors[2])

        assert 3.0 < order1 < 5.5, (
            f"Expected order ~4, got {order1:.2f} "
            f"(errors: {errors[0]:.2e}, {errors[1]:.2e})"
        )
        assert 3.0 < order2 < 5.5, (
            f"Expected order ~4, got {order2:.2f} "
            f"(errors: {errors[1]:.2e}, {errors[2]:.2e})"
        )

    def test_accuracy_fine_dt(self):
        from solver import solve_ks
        u = solve_ks(L=32 * np.pi, N=64, T=1.0, dt=0.0625)
        max_err = np.max(np.abs(u - self.u_ref))
        assert max_err < 0.01, f"Max error {max_err:.2e} exceeds 0.01"


# ---------------------------------------------------------------------------
# KS solution property tests (pure Python)
# ---------------------------------------------------------------------------

class TestKSProperties:
    """Test physical properties of the KS solution."""

    def test_solution_is_real(self):
        from solver import solve_ks
        u = solve_ks(L=32 * np.pi, N=64, T=1.0, dt=0.25)
        assert np.all(np.isfinite(u)), "Solution contains non-finite values"

    def test_mean_conservation(self):
        from solver import solve_ks
        from problem import setup

        params = setup(L=32 * np.pi, N=64)
        u0_mean = np.mean(np.fft.ifft(params["u0_hat"]).real)

        u = solve_ks(L=32 * np.pi, N=64, T=1.0, dt=0.25)
        final_mean = np.mean(u)

        assert abs(final_mean - u0_mean) < 1e-8, (
            f"Mean not conserved: initial={u0_mean:.2e}, final={final_mean:.2e}"
        )

    def test_correct_shape_and_type(self):
        from solver import solve_ks
        u = solve_ks(L=32 * np.pi, N=64, T=0.5, dt=0.25)
        assert isinstance(u, np.ndarray), "solve_ks must return numpy.ndarray"
        assert u.shape == (64,), f"Expected shape (64,), got {u.shape}"

    def test_different_parameters(self):
        from solver import solve_ks
        u = solve_ks(L=32 * np.pi, N=32, T=0.5, dt=0.25)
        assert u.shape == (32,), f"Expected shape (32,), got {u.shape}"
        assert np.all(np.isfinite(u)), "Solution contains non-finite values"
