"""
Extract an 8-bit S-box from a stripped ELF binary and decompose it as
S = A . X . B where A,B are GF(2)-linear and X(y) = a*y + b mod 256 (a odd).

Phase 1 (Binary Extraction):
    Parse the objdump .rodata hex dump to locate the 256-byte permutation
    table, distinguishing it from other constant data (rcon, xtime tables).

Phase 2 (Staircase Decomposition):
    1. Compute algebraic degrees of all 255 nontrivial linear combinations
       of S-box output bits.
    2. Build degree staircase: subspaces of output masks bounded by degree d
       for d = 1, 2, ..., 6.  Each level adds rows of A^(-1).
    3. Enumerate ordered bases for the degree-1 subspace.
    4. At each higher level, try coset representatives from the previous-
       degree space.  At each step, verify that the partial XB = A^{-1}(S)
       satisfies XB(x) = a * B(x) + b mod 2^k with B GF(2)-linear, pruning
       invalid branches.
    5. Output the first valid (A, B, a, b) found.
"""


import json
import re
import subprocess
import sys


# ---------------------------------------------------------------------------
# Phase 1: Binary extraction using objdump
# ---------------------------------------------------------------------------

def extract_sbox_from_objdump(dump_path):
    """Parse an objdump -s hex dump file and find the 256-byte permutation."""
    with open(dump_path) as f:
        content = f.read()

    # Parse hex bytes from objdump output lines
    # Format: " <addr> <hex16> <hex16> <hex16> <hex16>  <ascii>"
    all_bytes = []
    for line in content.split("\n"):
        m = re.match(r"\s+[0-9a-f]+\s+((?:[0-9a-f]+ ?)+)\s{2}", line)
        if m:
            hex_part = m.group(1).replace(" ", "")
            for i in range(0, len(hex_part), 2):
                all_bytes.append(int(hex_part[i : i + 2], 16))

    # Search for 256-byte permutation of 0..255
    expected = list(range(256))
    for start in range(len(all_bytes) - 255):
        candidate = all_bytes[start : start + 256]
        if sorted(candidate) == expected:
            print(f"Found S-box permutation at byte offset {start} in .rodata dump")
            return candidate

    raise ValueError("No 256-byte permutation block found in .rodata dump")


def extract_sbox_from_binary_direct(binary_path):
    """Fallback: read binary directly and search for permutation block."""
    with open(binary_path, "rb") as f:
        data = f.read()

    expected = list(range(256))
    for i in range(len(data) - 255):
        candidate = list(data[i : i + 256])
        if sorted(candidate) == expected:
            print(f"Found S-box at binary offset {i} (0x{i:x})")
            return candidate

    raise ValueError("No S-box permutation found in binary")


def extract_sbox():
    """Extract S-box using objdump, with direct binary read as fallback."""
    dump_path = "/app/rodata_dump.txt"
    binary_path = "/app/sbox_engine"

    # Try objdump output first (generated by solve.sh)
    try:
        return extract_sbox_from_objdump(dump_path)
    except (FileNotFoundError, ValueError) as e:
        print(f"objdump parse failed ({e}), trying direct binary read...")

    # Run objdump ourselves
    try:
        result = subprocess.run(
            ["objdump", "-s", "-j", ".rodata", binary_path],
            capture_output=True,
            text=True,
        )
        with open(dump_path, "w") as f:
            f.write(result.stdout)
        return extract_sbox_from_objdump(dump_path)
    except (FileNotFoundError, ValueError):
        pass

    # Direct binary read
    return extract_sbox_from_binary_direct(binary_path)


# ---------------------------------------------------------------------------
# Phase 2: Algebraic decomposition (staircase analysis)
# ---------------------------------------------------------------------------

def compute_anf(func_values):
    """Mobius transform: truth table -> ANF coefficients."""
    N = 256
    anf = list(func_values)
    for i in range(8):
        step = 1 << i
        for j in range(N):
            if j & step:
                anf[j] ^= anf[j ^ step]
    return anf


def anf_degree(func_values):
    anf = compute_anf(func_values)
    return max(
        (bin(idx).count("1") for idx in range(256) if anf[idx]),
        default=0,
    )


def get_output_func(sbox, mask):
    """Boolean function: x -> popcount(S(x) & mask) mod 2."""
    return [bin(sbox[x] & mask).count("1") % 2 for x in range(256)]


def gf2_reduce(masks):
    """Row-reduce a set of masks to get a GF(2) basis."""
    basis = []
    for m in sorted(masks):
        r = m
        for b in basis:
            r = min(r, r ^ b)
        if r > 0:
            basis.append(r)
            basis.sort(reverse=True)
            for i in range(len(basis)):
                for j in range(i):
                    basis[j] = min(basis[j], basis[j] ^ basis[i])
    return sorted(basis)


def gf2_inverse(M):
    n = len(M)
    aug = [M[i][:] + [1 if i == j else 0 for j in range(n)] for i in range(n)]
    for col in range(n):
        pivot = -1
        for row in range(col, n):
            if aug[row][col] == 1:
                pivot = row
                break
        if pivot == -1:
            return None
        aug[col], aug[pivot] = aug[pivot], aug[col]
        for row in range(n):
            if row != col and aug[row][col] == 1:
                for j in range(2 * n):
                    aug[row][j] ^= aug[col][j]
    return [row[n:] for row in aug]


def mat_vec_mul_gf2(M, v):
    return [sum(M[i][j] * v[j] for j in range(len(v))) % 2 for i in range(len(M))]


def int_to_bits(x, n=8):
    return [(x >> i) & 1 for i in range(n)]


def bits_to_int(bits):
    return sum(b << i for i, b in enumerate(bits))


def all_nonzero_elements(basis):
    elems = []
    for mask in range(1, 1 << len(basis)):
        val = 0
        for i in range(len(basis)):
            if mask & (1 << i):
                val ^= basis[i]
        elems.append(val)
    return sorted(elems)


def is_independent(rows):
    n = len(rows)
    mat = [[int(bool(m & (1 << bit))) for bit in range(8)] for m in rows]
    tc = [r[:] for r in mat]
    rank = 0
    for col in range(8):
        piv = -1
        for row in range(rank, n):
            if tc[row][col]:
                piv = row
                break
        if piv == -1:
            continue
        tc[rank], tc[piv] = tc[piv], tc[rank]
        for row in range(n):
            if row != rank and tc[row][col]:
                for j in range(8):
                    tc[row][j] ^= tc[rank][j]
        rank += 1
    return rank == n


def check_arithmetic(sbox, rows_masks, mod):
    """Check whether partial XB is consistent with arithmetic structure."""
    n_rows = len(rows_masks)
    xb = [0] * 256
    for x in range(256):
        y = sbox[x]
        val = 0
        for bit_idx in range(n_rows):
            mask = rows_masks[bit_idx]
            v = bin(y & mask).count("1") % 2
            val |= v << bit_idx
        xb[x] = val

    b_val = xb[0]
    results = []
    for a_val in range(1, mod, 2):
        a_inv = pow(a_val, -1, mod)
        B_cols = [(a_inv * ((xb[1 << i] - b_val) % mod)) % mod for i in range(8)]
        valid = True
        for x in range(256):
            Bx = 0
            for i in range(8):
                if x & (1 << i):
                    Bx ^= B_cols[i]
            if (a_val * Bx + b_val) % mod != xb[x]:
                valid = False
                break
        if valid:
            results.append((a_val, b_val, B_cols))
    return results


def solve(sbox):
    # Step 1: build degree spaces
    degree_spaces = {}
    for d in range(1, 7):
        masks = set()
        for mask in range(1, 256):
            if anf_degree(get_output_func(sbox, mask)) <= d:
                masks.add(mask)
        degree_spaces[d] = masks

    # Step 2: compute bases
    degree_bases = {}
    for d in range(1, 7):
        degree_bases[d] = gf2_reduce(degree_spaces[d])

    # Step 3: find new representative mask at each level
    new_rep = {}
    cum_basis = list(degree_bases[1])
    for d in range(2, 7):
        for m in sorted(degree_spaces[d]):
            r = m
            for b in cum_basis:
                r = min(r, r ^ b)
            if r > 0:
                new_rep[d] = m
                cum_basis.append(m)
                cum_basis.sort(reverse=True)
                for i in range(len(cum_basis)):
                    for j in range(i):
                        cum_basis[j] = min(cum_basis[j], cum_basis[j] ^ cum_basis[i])
                break

    deg1_all = all_nonzero_elements(degree_bases[1])

    # Step 4: enumerate ordered bases for degree-1 space, extend with pruning
    for r0 in deg1_all:
        for r1 in deg1_all:
            if r1 == r0:
                continue
            for r2 in deg1_all:
                if r2 == r0 or r2 == r1 or r2 == (r0 ^ r1):
                    continue

                rows = [r0, r1, r2]
                res8 = check_arithmetic(sbox, rows, 8)
                if not res8:
                    continue

                for a8, b8, _ in res8:

                    def try_extend(rows, a_prev, prev_mod, depth):
                        if depth > 6:
                            res = check_arithmetic(sbox, rows, 256)
                            for a256, b256, Bcols256 in res:
                                if a256 % prev_mod == a_prev:
                                    return rows, a256, b256, Bcols256
                            return None

                        base = new_rep.get(depth)
                        if base is None:
                            return None
                        cur_mod = prev_mod * 2

                        prev_deg_basis = degree_bases[depth - 1]
                        n_prev = len(prev_deg_basis)

                        for coset_mask in range(1 << n_prev):
                            extra = 0
                            for i in range(n_prev):
                                if coset_mask & (1 << i):
                                    extra ^= prev_deg_basis[i]
                            candidate = base ^ extra
                            new_rows = rows + [candidate]
                            if not is_independent(new_rows):
                                continue

                            res = check_arithmetic(sbox, new_rows, cur_mod)
                            for a_cur, _, _ in res:
                                if a_cur % prev_mod == a_prev:
                                    result = try_extend(
                                        new_rows, a_cur, cur_mod, depth + 1
                                    )
                                    if result:
                                        return result
                        return None

                    result = try_extend(rows, a8, 8, 2)
                    if result:
                        final_rows, a_final, b_final, Bcols_final = result

                        A_inv_mat = [
                            [int(bool(m & (1 << bit))) for bit in range(8)]
                            for m in final_rows
                        ]
                        A_mat = gf2_inverse(A_inv_mat)
                        B_mat = [[0] * 8 for _ in range(8)]
                        for col in range(8):
                            for row in range(8):
                                B_mat[row][col] = (Bcols_final[col] >> row) & 1

                        # Verify
                        ok = True
                        for x in range(256):
                            xb = int_to_bits(x)
                            bxb = mat_vec_mul_gf2(B_mat, xb)
                            bx = bits_to_int(bxb)
                            xx = (a_final * bx + b_final) % 256
                            xxb = int_to_bits(xx)
                            axb = mat_vec_mul_gf2(A_mat, xxb)
                            ax = bits_to_int(axb)
                            if ax != sbox[x]:
                                ok = False
                                break

                        if ok:
                            return A_mat, B_mat, a_final, b_final

    return None


def main():
    print("Phase 1: Extracting S-box from stripped binary...")
    sbox = extract_sbox()
    assert len(sbox) == 256, "S-box must have 256 entries"
    assert sorted(sbox) == list(range(256)), "S-box must be a permutation"
    print(f"S-box extracted successfully. First 16 values: {sbox[:16]}")

    # Verify against binary CLI for a few values
    print("\nVerifying extraction against binary CLI...")
    try:
        for test_input in [0x00, 0x01, 0xFF]:
            result = subprocess.run(
                ["/app/sbox_engine", f"{test_input:02x}"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            if result.returncode == 0:
                cli_output = int(result.stdout.strip(), 16)
                if cli_output == sbox[test_input]:
                    print(f"  S(0x{test_input:02x}) = 0x{cli_output:02x} [OK]")
                else:
                    print(
                        f"  S(0x{test_input:02x}): extracted={sbox[test_input]}, "
                        f"cli={cli_output} [MISMATCH]"
                    )
    except (subprocess.TimeoutExpired, FileNotFoundError) as e:
        print(f"  CLI verification skipped: {e}")

    print("\nPhase 2: Algebraic decomposition (staircase analysis)...")
    result = solve(sbox)
    if result is None:
        print("ERROR: No decomposition found", file=sys.stderr)
        sys.exit(1)

    A_mat, B_mat, a_val, b_val = result
    answer = {"A": A_mat, "B": B_mat, "a": a_val, "b": b_val}

    with open("/app/answer.json", "w") as f:
        json.dump(answer, f, indent=2)

    print(f"\nDecomposition found: a={a_val}, b={b_val}")
    print("Written to /app/answer.json")


if __name__ == "__main__":
    main()
